### ISSUE TITLE
[WEB] Samostudium - překlepy a další chyby

### ISSUE THREAD

**Issue by milansav** [ssps-cajthaml/issues#1]
Na následujících stránkách naleznete různ**é** => (různá, ta samostudia) předpřipraven**é** => (předpřipravená, ta samostudia) samostudia, kter**é** => (která, ta samostudia) můžete používat k opakování látky. Existují samostudia, kter**é** => (která, ta samostudia) obsahují otázky, na které můžete odpovídat - a mohou se objevit **se v zkoušeních** => (při zkouškách, 6.p zkouška, se v zkoušeních není čeština). Další typ samostudia jsou tzv. knížky, které obsahují delší texty s postupem na vytvoření různých prací. ~Milan Savickij

**Comment by Vojtysek** [comment]
cenim!

**Comment by cajthamlmatej** [comment]
Opraveno. Bude nahráno společně s další verzi.
