### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by dyyy69** [ssps-cajthaml/issues#101]
### Popis problémů

PO vyskoceni chyboveho okna a znovunacteni stranky se ukol automaticky hodnoti pres 5 minut (normalne to trvalo tak 5s) a nejde se z toho nijak dostat

### Reprodukce problému

![Snímek obrazovky 2022-09-12 195600](https://user-images.githubusercontent.com/112863222/189723654-21500c24-eef7-4bbe-9783-144edc77b04c.png)

### Stránka

https://ssps.cajthaml.eu/2-pva/work/4-prvni-program

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![Uploading Snímek obrazovky 2022-09-12 195600.png…]()

### Vaše jméno

David Vanek

**Comment by cajthamlmatej** [comment]
Vyřešeno mimo GitHub.
