### ISSUE TITLE
[WEB] Percentil

### ISSUE THREAD

**Issue by VasAli06** [ssps-cajthaml/issues#102]
### Popis problémů

Divný výpočet percentilu. Neodpovídá realitě

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "osobní profil"
4. Profit.

### Stránka

https://ssps.cajthaml.eu/2-pva/profile

### Zařízení

Operační systém: **Windowsd**
Prohlížeč: **Google Chrome.**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![unknown](https://user-images.githubusercontent.com/43419807/189812138-154cb32d-0f84-444f-8144-b6913a95bc84.png)

### Vaše jméno

Alex Naxera

**Comment by cajthamlmatej** [comment]
Neodpovídá realitě díky tomu, že většina studentů v tomto předmětu má bodový základ 0, se kterým se špatně cokoliv počítá.
