### ISSUE TITLE
Formátování kódu v sandboxu 

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#103]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Přidání možnosti formátovat kód v sandboxu na webovém portálu 

### Zdůvodnění

Ulehčení psaní kódu a jeho čitelnosti

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Systém již používá monaco editor.
