### ISSUE TITLE
[NÁPAD] redo/undo tlačítka pro mobilní zařízení v sandboxu

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#104]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Přidání redo/undo tlačítek pro sandbox

### Zdůvodnění

Na mobilních zařízeních není možné používat klávesové zkratky

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Monaco editor toto již řeší afaik.
