### ISSUE TITLE
Přidání možnosti přidat testy a zkoušení do kalendáře pomocí iCal

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#106]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Bylo by dobré mít na webu přehled naplánovaných testů pro předmět s možností je přidat do kalendáře. 

### Zdůvodnění

Přehlednost

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Nový portál přidává "upozornění", ve kterých se testy budou ohlašovat, které se do kalendáře automaticky přidávají.
