### ISSUE TITLE
[WEB] nesmyslné zobrazování percentilu

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#108]
### Popis problémů

V tuto chvíli percentil vypisuje procenta, která ale nejsou uplně čitelná a nepůsobí správně. Pokud například v tuto chvíli jsem nejlepším studentem v předmětu a tedy mám nejvíce bodů, percentil píše že 3,4% studentů má lepší výsledek, ale předpokládám že ty 3,4% jsem pouze já sám. 

Osobně bych jako řešení problému navrhl místo procent používat čísla. Tedy pokud bych byl pátý nejlepší z dvaceti lidí, zobrazil bych zprávu typu: "Patnáct studentů mají horší výsledek než ty a 4 studenti mají výsledek lepší", v případě nejlepšího výsledku bych vypsal něco ve smyslu "V tuto chvíli máte nejlepší výsledek a 19 dalších studentů mají horší výsledek"

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na Osobní profil
3. hover na ukazatel percentilu
4. Zmatení ?????

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf/profile

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome.**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![percentil](https://user-images.githubusercontent.com/82168954/189895210-9a1a8a2b-c3a6-4c22-9a94-bb001c199a90.PNG)

### Vaše jméno

Lukaš Kníže

**Comment by cajthamlmatej** [comment]
Percentily jsou takto neurčité schválně. Samotné seřazení studentů mi nepřijde vhodné a může to být velmi demotivující. Prozatím je necháme. Percentily mají velmi mnoho edge-case, které právě to, že jste v těch 3.4% nejlepších studentů ničí - a proto jsem tu hlášku odstranil.
