### ISSUE TITLE
[NÁPAD] Toolbox u nejlepšího studenta

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#109]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Pokud najedeme na progress bar u v sekci nejlepší student a jsme nejlepším studentem daného předmětu, tak se zobrazí hláška "Nejlepší student tohoto předmětu má o 0 bodů více" což je divné a nahradil bych to něčím jako "Máte nejvíce bodů z tohoto předmětu" nebo třeba pro motivaci "Druhý nejlepší student tohoto předmětu má o X bodů méně"

### Zdůvodnění

Bude to obecně lepší a teď to vypadá divně
![wtf](https://user-images.githubusercontent.com/82168954/189904897-6e021a3b-51cc-481e-8fa8-10e25da3b9a9.PNG)

### Vaše jméno

Lukaš Kníže

**Comment by cajthamlmatej** [comment]
To je (znovu) chyba se zaokrouhlením. Jste nejlepším studentem daného předmětu (a normálně se to tam zobrazuje).

**Comment by cajthamlmatej** [comment]
Nový portál nemá nejlepší studenty a proto nemá smysl evidovat.
