### ISSUE TITLE
[WEB] pravopisné chyby

### ISSUE THREAD

**Issue by MrMartix** [ssps-cajthaml/issues#111]
### Popis problémů

1. Při zapnutí webu > podmínky používání > poslední věta > návštévníci (má být ě)
2. Informace > řešení úloh > prohokoliv (pro kohokoliv)
3. Zkoušení > často kladené dotazy > Jak fungují zkoušení > pismených testů (písemných)
4. Zkoušení > často kladené dotazy > Co se stane,... > ukočeno (ukončeno), zakázano (zakázáno), učely (účely)
5. Zkoušení > často kladené dotazy > Jaké otázky se mohou v testu objevit? > nebo i žadné (žádné)
6. Pískoviště > často kladené dotazy > k čemu tato stránka je? > škoního roku (školního)
7. WBA > Hosting > Vytvoření hostingu webové stránky > předposlední bod > zakázano (zakázáno)

### Stránka

1. https://ssps.cajthaml.eu/
2. https://ssps.cajthaml.eu/2-pva/page/reseni-uloh
3. https://ssps.cajthaml.eu/2-pva/exam/list
4. https://ssps.cajthaml.eu/2-pva/exam/list
5. https://ssps.cajthaml.eu/2-pva/exam/list
6. https://ssps.cajthaml.eu/playground
7. https://ssps.cajthaml.eu/2-wba/hosting

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Vaše jméno

Martin Šíma

**Comment by cajthamlmatej** [comment]
Bod č. 6 byl asi dříve opraven, ta chyba tam nikde není. Děkuji za zbytek. :)
