### ISSUE TITLE
[MATERIÁL] pravopisné chyby (zase :D)

### ISSUE THREAD

**Issue by MrMartix** [ssps-cajthaml/issues#112]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 4. ročník

### Materiál

Samostudium

### Popis problémů

1. Centrlaizovaný přístup... (asi by mělo být Centralizovaný)
2. nepravne: (nesprávně:)
3. Všichni vědi (vědí)
4. ... i se souborý (soubory)
5. Pro Issues se doporučje (doporučuje), pod tím Projects: ...boardy automatizovan (automatizovat asi)
6. ...verze a metada (metoda asi)
7. ...ale zjednodušene (zjednodušeně), ...kód však býva (bývá)
8. ... a nebo napřikladi (například)
9. ... v daném objektu se nacházi (nachází)
10. ...uložená v konstatě (konstantě)
11. něco neměného, stáleho (neměnného, stálého), Tudiž nemají... (Tudíž), nestatickým věcím (věcem)
12. Gettery nemájí (nemají)
13. V praxi to hlavně znemaná (znamená), dispozici vlatnosti (vlastnosti), Animal a tudiž (tudíž), K tomu abysme (abychom), stát nekonzitence (nekonzistence)
14. číslo reprezentujicí (reprezentující), přijmení (příjmení), správnou dedičnost (dědičnost)
15. vždy v obdelníkovém (obdélníkovém), v prním (prvním), v níže uvedém (uvedeném)
16. jste obyčený (obyčejný)
17. Váším (Vaším), řádků obsahujicí (obsahující)
18. nachází nejznámnější (nejznámější), však přijimána (přijímána), bude slouži (sloužit), představujici (představující), obsahujicí (obsahující)
19. 4x nápsáno obdelník (obdélník)
20. Mezi režimi (režimy)

### Lokace

1. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-opakovani-3-rocniku/vue-62f63cd430ee5205a5346869
2. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/sestaveni-vue-aplikace
3. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-verzovaci-systemy/verzovac%C3%AD-syst%C3%A9my-62e19fc0f2b1b9d5c8e4ca23
4. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-verzovaci-systemy/commit-62e19fc0f2b1b9d5c8e4ca27 (speciální soubory gitu)
5. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-verzovaci-systemy/gitov%C3%A9-slu%C5%BEby-62e19fc0f2b1b9d5c8e4ca2c (Issues)
6. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-verzovaci-systemy/spr%C3%A1vn%C3%A1-dokumentace-62e19fc0f2b1b9d5c8e4ca2d
7. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/motivace-619f89ca49a3dd45d022a0a6
8. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/objekty-619f89ca49a3dd45d022a0a7
9. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/t%C5%99%C3%ADdy-619f89ca49a3dd45d022a0a8
10. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/instance-619f89ca49a3dd45d022a0a9
11. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/statick%C3%A9-v%C4%9Bci-uvnit%C5%99-t%C5%99%C3%ADdy-619f89ca49a3dd45d022a0ab
12. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/gettery-a-settery-619f89ca49a3dd45d022a0ac
13. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/d%C4%9Bdi%C4%8Dnost-619ff09b49a3dd45d022a4fb
14. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/objektove-orientovane-programovani/p%C5%99%C3%ADklady-619ffa9049a3dd45d022a5ba
15. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni
16. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni/posloupnost-61881460769f7bb70cfc4aa5
17. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni/zlo%C4%8Dinec-yoko-61881460769f7bb70cfc4aa6
18. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni/%C3%BAt%C4%9Bk-v-ko%C4%8Di%C4%8D%C3%AD-z%C3%A1toce-618ebd91769f7bb70cfce8e4
19. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni/chycen%C3%AD-yendy-6248bfeb4f4d7f20374ef502
20. https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/logicke-mysleni/n%C3%A1vrat-ptactva-627a6b38f37fda5b044d281a

### Vaše jméno

Martin Šíma

**Comment by cajthamlmatej** [comment]
Děkuji.
