### ISSUE TITLE
[MATERIÁL] Překlepy v lekci samostudia

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#113]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

LEKCE: Verzovací systémy

### Popis problémů

Překlepy a pár gramatických chybek v samostudiu.

### Lokace

- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/verzovac%C3%AD-syst%C3%A9my-62e19fc0f2b1b9d5c8e4ca23
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/%C3%BAvod-gitu-62e19fc0f2b1b9d5c8e4ca24
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/nastaven%C3%AD-a-n%C3%A1pov%C4%9Bda-gitu-62e19fc0f2b1b9d5c8e4ca25
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/repozit%C3%A1%C5%99-62e19fc0f2b1b9d5c8e4ca26
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/commit-62e19fc0f2b1b9d5c8e4ca27
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/historie-62e19fc0f2b1b9d5c8e4ca28
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/n%C3%A1vrat-do-p%C5%99edchoz%C3%ADho-stavu-62e19fc0f2b1b9d5c8e4ca29
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/v%C4%9Btve-62e19fc0f2b1b9d5c8e4ca2a
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/vzd%C3%A1len%C3%A9-repozit%C3%A1%C5%99e-a-v%C4%9Btve-62e19fc0f2b1b9d5c8e4ca2b
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/gitov%C3%A9-slu%C5%BEby-62e19fc0f2b1b9d5c8e4ca2c
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/spr%C3%A1vn%C3%A1-dokumentace-62e19fc0f2b1b9d5c8e4ca2d
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/z%C3%A1sady-gitu-62e19fc0f2b1b9d5c8e4ca2e
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-verzovaci-systemy/git-klienti-62e19fc0f2b1b9d5c8e4ca2f

### Oprava

podle jednotlivých stránek:

### Verzovací systémy
- ­1. věta 2. odstavce: slovo "individuálně" nesedí do té věty, spíše něco jako "**jednotlivci**"
- ­4. odstavec: spojení "jako příklad můžeme uvést například …" nedává smysl, chtělo by to smazat to druhé "**například**"
- odstavec Historie verzí: v 1. větě špatná koncovka: "Obecně existuje pouze dva typy" -> "Obecně **existují** pouze dva typy"
- odstavec Historie verzí: v 1. větě vypadlo slovo "Obecně existují pouze dva typy **historií** verzí ve … "
- odstavec Verzovací systémy: "Známe verzovací systémy jsou:" -> "**Známé**"
<hr>

### Úvod Gitu
- cíle gitu, bod 4 na konci: "akce trvali" -> "**trvaly**"
<hr>

### Nastavení a nápověda Gitu
- odstavec pod 1. kódem: "více slovná" -> "**víceslovná**"
- odstavec pod 2. kódem: 1. věta nedává moc smysl, možná by pomohlo změnit závorku na čárky. Nebo místo "ale i s ním" dát "**ale může být i globální**"
<hr>

### Repozitář
- ­2. odstavec: přesunout čárku před "a" -> "**úkol, a to je sledovat …**"
- poslední odstavec, 2. věta: jsou zde 2 "a" ve výčtu. To první by nejspíš chtělo nahradit čárkou, ale asi whatever
<hr>

### Commit
- ­3. věta: "commitu" -> "**commitů**"
- předposlední věta téhož odstavce: "commitu" -> "**commitů**"
- odstavec pod obrázkem: přidat čárku za "repozitář" -> "**Pro zjištění, v jakém stavu je aktuálně repozitář, lze použít příkaz**"
- odstavec Přesné změny revize: "formatu" -> "**formátu**"
- sekce Zapsání změn, odstavec pod kódem: v závorce přidat čárku za "vypadat" -> "**o tom, jak by zpráva měla vypadat, si povíme v jiné kapitole**"
- odstavec Speciální soubory gitu, 1. věta: "souborý" -> "**soubory**"
- odstavec Speciální soubory gitu, 2. věta: "souboru" -> "**souborů**"
<hr>

### Historie
- odstavec Určení počtu výsledků: "přepínačů" -> "Pomocí **přepínače** `-x`"
<hr>

### Návrat do předchozího stavu
- odstavec o Resetování: přidat "se" -> "**, které se v daném**"
- odstavec o Resetování: "stali" -> "**staly**"
<hr>

### Větve
- ­3. odstavec: nahradit dvě tečky v závorce třemi, nebo trojtečkou (**…**)
- konec téhož odstavce: přidat čárku mezi "podrobně" a "si"
- ­3. odstavec části Vytvoření větve: v příkazu mají být jenom dvě pomlčky, v textu jsou 3
- odstavec V jaké větvi jsme: do poslední věty přidat čárku: "**můžeme vidět, v jaké větvi jsme.**"
<hr>

### Vzdálené repozitáře a větve
- ­1. věta: "mohl" -> "**může**"; aby byl čas všech těch sloves stejný
- ­4. odstavec: "větve, tím říkáme" -> "**těm** říkáme"
- stejný odstavec: "s větvi komunikovat" -> "**větví**"
- stejná věta: "do našich lokálních větvích" -> "**větví**"
- odstavec Implementace změn ze vzdáleného repozitáře: chtělo by to zvýraznit i zmíněný příkaz `git pull`, protože všechny ostatní jsou v code blocích
- na začátku dalšího odstavce by to chtělo také
- týž odstavec: "jaký je jejich kopie" -> "**jaká**"
- odstavec Nahrání verze do vzdáleného repozitáře: "větev v zdáleném" -> "**větev ve vzdáleném**"
<hr>

### Gitové služby
- odstavec GitLab: "Je velmi jednoduché" -> "**jednoduchá**"
- stejný odstavec: "hezké" -> "**hezká**"
- část o Issues, 2. odstavec: "Každý Issue má svoje číslo" -> "**Každá**"
- odstavec Projects, poslední věta: "automatizovan" -> "**automatizovat**"
- ­2. odstavec v Pull Request, začátek 3. věty: "Jako issues" -> "Jako **(v/u)** issues"
- tamtéž: kapitalizovat "i" ve slově "**Issue**", protože výše v textu to používáte s velkým i
<hr>

### Správná dokumentace
- ­1. odstavec: přidat čárku -> "**Jedná se o doporučení, jak**"
- odstavec za vysvětlením čísel verzí: "Za těmito čísli" -> "**čísly**"
- odstavec Dokumentace: "je však myslet i na externí" -> "je však **potřeba** myslet i na externí"
- další odstavec: "Gitové nástroje dovoluje" -> "**dovolují**"
- tentýž odstavec: "by měli být ty" -> "**měly**" 
- tentýž odstavec: "poskytnou další" -> "**poskytnout**"
<hr>

### Zásady Gitu
- odstavec Typy větví, 2. věta: "a to stále" -> "**stálé**"
<hr>

### Git klienti
- konec 1. odstavce: "To vede, že tyto nástroje používají" -> "To vede **k tomu**, že"
- hned další řádek: "Známé Gitoví klienti" -> "**Známí** Gitoví klienti"
- ­1. bod seznamu Výhod: "v jaké stavu" -> "**jakém**"
- ­1. bod nevýhod: "za vás" -> "Vás" - všude jinde máte V kapitalizované

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Děkuji.
