### ISSUE TITLE
[MATERIÁL] Pravopisné chyby

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#117]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Opakování — konvertování, matematické operace | PVA Cajthaml (5. hodina)

### Popis problémů

1 - druhý bod - "přesnost či nějaká data"

### Lokace

1 - https://api-ssps.cajthaml.eu/file/2022-2023/2-pva/presentations/5.html#/2/4/1 (slide 8)

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
Děkuji.
