### ISSUE TITLE
[WEB] Pravopisné chyby

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#118]
### Popis problémů

1 - "malé písmena" a "velké písmena" -> "malá písmena" a "velká písmena"
2 - "prázdné místa" -> "prázdná místa"
3 - "pomocí meto Write a WriteLine" -> "pomocí metod Write a Writeline"
4 - Code blockům chybí grafické obarvení

### Reprodukce problému

Postup k reprodukci:
1. Prostě stránku otevřít

### Stránka

1 - https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/textov%C3%A9-funkce-6302169b2f6bb1446c0487c7 (druhý code block, řádek 6 a 7)
2 - https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/textov%C3%A9-funkce-6302169b2f6bb1446c0487c7 (první code block, řádek 6)
3 - https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/kurzor-v-konzoli-6302169b2f6bb1446c0487cc (druhý odstavec (3. řádek), první věta)
4 - https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/pr%C3%A1ce-s-%C5%99et%C4%9Bzci-6302169b2f6bb1446c0487cd

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
Děkuiji.
