### ISSUE TITLE
[WEB] Po odevzdání práce ztratí klient připojení

### ISSUE THREAD

**Issue by Goubermouche** [ssps-cajthaml/issues#119]
### Popis problémů

Po odevzdání [práce](https://ssps.cajthaml.eu/dvop-wbb/work/6-prvni-repozitar) ztratí klient připojení k serveru. 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Přejděte na stránku [práce](https://ssps.cajthaml.eu/dvop-wbb/work/6-prvni-repozitar).
3. Odevzdejte .zip soubor s touto strukturou: 
```
.zip
├ .git
└ index.html
```
4. Po odevzdání server reaguje následovně: 
![image](https://user-images.githubusercontent.com/71839692/190959579-f81e0554-f524-4ff1-8e4b-dd6b68e19483.png)
5. Po návratu na stránku je uživatel zaseklý ve fázi kontroly úkolu. 

### Stránka

https://ssps.cajthaml.eu/dvop-wbb/work/6-prvni-repozitar

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Firefox Developer edition**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

see screenshots

### Screenshoty

![image](https://user-images.githubusercontent.com/71839692/190960306-73af199c-0879-49eb-8744-4680b3b64061.png)

### Vaše jméno

Šimon Tupý 4.C

**Comment by cajthamlmatej** [comment]
Opraveno. Za pár minut bude fix.
