### ISSUE TITLE
[MATERIÁL] Překlep

### ISSUE THREAD

**Issue by tomasborek** [ssps-cajthaml/issues#121]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 3. ročník

### Materiál

Prezentace webový frontend 7. hod slide 37

### Popis problémů

Místo import important

### Lokace

slide 37

### Oprava

wooo

### Screenshoty

ne

### Vaše jméno

Tomáš Bořek

**Comment by cajthamlmatej** [comment]
Děkuji.
