### ISSUE TITLE
Prezentace MVOP

### ISSUE THREAD

**Issue by Bonsaie** [ssps-cajthaml/issues#122]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 3. ročník

### Materiál

7.hod Opakování WBA (pozicování, psudotřídy, selektory)

### Popis problémů

!import nemá byt vidět "!import*"

### Lokace

Na straně 37

### Screenshoty

![Screenshot 2022-09-19 143008](https://user-images.githubusercontent.com/94934141/191017527-4a35f784-96c2-46c9-a559-a24c452feb86.jpg)

### Vaše jméno

Dalibor Lžičař

**Comment by cajthamlmatej** [comment]
Duplikát #121
