### ISSUE TITLE
[MATERIÁL] Gramatické chyby

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#124]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Lekce: Opakování 1. ročníku - Pole ( https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/pole-6302169b2f6bb1446c0487ce )

### Popis problémů

1 - "postupné" -> "postupně"
2 - řádek navíc
3 - Věta asi nedokončená? "Představte si, že byste museli pro každé zadané jméno mít speciální proměnnou, která je ještě velmi omezena tím."
4 - Místo "a" -> "ale?" - "Oproti ostatním typům cyklu zde neurčujeme jak pole procházíme a prostě pouze jedním směrem."

### Lokace

1 - První odstavec, ke konci
2 - druhý codeblock
3 - šestý text
4 - poslední text

### Screenshoty

2 - 
![image](https://user-images.githubusercontent.com/101324454/191093041-055939a0-33db-45b6-a4b3-8ef8fa18bb1e.png)

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
2) je pouze vizuální bug, který aktuálně nemá žádnou prioritu a ničemu to nevadí. 
4) nedává smysl ani po opravě, opravil jsem to.

Děkuji.
