### ISSUE TITLE
[WEB] Problémy s názvem odevzdaného souboru

### ISSUE THREAD

**Issue by MarekProkopec** [ssps-cajthaml/issues#125]
### Popis problémů

Při odevzdání souboru který má háčky a čárky se jméno změní na něco absolutně cursed a automatické známkování pro daný soubor nefunguje.

### Reprodukce problému

Postup k reprodukci:
1. odevzdat soubor, který má v názvu háčky a čárky
2. Jméno se změní na minecraft enchanting table, automatické známkování nefunguje

### Stránka

https://ssps.cajthaml.eu/dvop-wbb/work/6-prvni-repozitar

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

![image](https://user-images.githubusercontent.com/51177304/191332812-b5cbf0ee-92f2-4092-bad3-1be1e75532cc.png)
![image](https://user-images.githubusercontent.com/51177304/191332825-cbae4a02-0ccb-410d-a55c-e027b2cc6b85.png)

### Vaše jméno

Marek Prokopec

**Comment by cajthamlmatej** [comment]
Nový portál již vyřešil - diakritika je odstraněna i s enchanting language znaky.
