### ISSUE TITLE
[MATERIÁL] chyba v kódu

### ISSUE THREAD

**Issue by MrMartix** [ssps-cajthaml/issues#126]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Samostudium

### Popis problémů

V ukázce kódu chybí středník

### Lokace

https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/slo%C5%BEen%C3%A9-p%C5%99i%C5%99azen%C3%AD-a-matematick%C3%A9-operace-6302169b2f6bb1446c0487c6

### Screenshoty

![image](https://user-images.githubusercontent.com/113117044/191333081-ea662877-e50d-4da9-bf32-ac3cf8f6cb03.png)

### Vaše jméno

Martin Šíma

**Comment by cajthamlmatej** [comment]
Děkuji.
