### ISSUE TITLE
[WEB] Chyba v responzivnosti

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#127]
### Popis problémů

Zvýrazněný text je neresponzivní a tím zvětšuje celou stránku, takže se v ní hůře pohybuje na mobilu

### Reprodukce problému

Postup k reprodukci:
1. Prostě stránku otevřít na mobilu.

### Stránka

https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zakladni-pojmy-webovych-stranek/world-wide-web-a-domény-62b488bb2a11e23d3e26b38a

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![8EB8B978-004A-4D14-95AF-AB61AAA3EC94](https://user-images.githubusercontent.com/101324454/191666130-431615d5-b276-472d-82ad-0ba107b909a2.jpeg)

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
#89 duplikát
