### ISSUE TITLE
[MATERIÁL] Gramatické chyby

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#128]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Lekce: základní pojmy webových stránek

### Popis problémů

1 - “To by šlo odejít” -> “To by šlo obejít”?
2 - “Společnost CZ.NIC, která českou doménu spravuje pravidelně dělá dotazník, kde se na tuto technologii ptá.” -> “Společnost CZ.NIC, která českou doménu spravuje, pravidelně dělá dotazník, kde se na tuto technologii ptá.” (čárka)
3 - “URL (uniform resource locator) je řetězec znaků s definovanou, který se používá pro adresaci na WWW.” 

### Lokace

1 - Subpage World wide web a domény (třetí odstavec, druhý bod)
2 - Subpage World wide web a domény (poslední odstavec)
3 - Subpage URL adresa (první odstavec)

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
Děkuji, i když je to již opravené (asi z minule někdy).
