### ISSUE TITLE
[MATERIÁL] 

### ISSUE THREAD

**Issue by JakubHrbek** [ssps-cajthaml/issues#129]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

LEKCE: Základní HTML

### Popis problémů

Pár pravopisných chyb v části HTML.

Hyper Text Markup Language, ve zkratce HTML je značkovací jazyk. Nejedná se tedy o klasický programovací (jako C#) nebo skriptovací (JavaScript/Lua) jazyk, ale o jazyk, který jenom definuje určité data a to v XML s vlastními definicemi tagů. Technologií XML se v předmětu WBA zabývat ale nebudeme — není nutné si to ani pamatovat.

HTML bylo představeno v roce 1990. Od té doby vznikli různé verze, ta nejdůležitější je HTML5 z roku 2012, kterou se ve WBA budeme zabývat. Tato verze se hlavně zaměřila na to, aby šel multimediální obsah spouštět na webu. Cílilo se i na to, aby webové stránky byly přehledné i pro počítače a mohli se jednodušeji crawlorat, resp. indexovat.

HTML se používají zejména pro webové stránky, protože definují různé tagy, které vytváří na stránce různé prvky, které může uživatel vidět. Tyto soubory mají obvykle příponu .html.

-->

Hyper Text Markup Language, ve zkratce HTML je značkovací jazyk. Nejedná se tedy o klasický programovací (jako C#) nebo skriptovací (JavaScript/Lua) jazyk, ale o jazyk, který jenom definuje určité data a to v XML s vlastními definicemi tagů. Technologií XML se v předmětu WBA zabývat ale nebudeme — není nutné si to ani pamatovat.

HTML bylo představeno v roce 1990. Od té doby **vznikly** různé verze, ta nejdůležitější je HTML5 z roku 2012, kterou se ve WBA budeme zabývat. Tato verze se hlavně zaměřila na to, aby šel multimediální obsah spouštět na webu. Cílilo se i na to, aby webové stránky byly přehledné i pro počítače a **mohly** se jednodušeji **crawlovat**, resp. indexovat.

HTML se používají zejména pro webové stránky, protože definují různé tagy, které vytváří na stránce různé prvky, které může uživatel vidět. Tyto soubory mají obvykle příponu .html.

### Lokace

HTML

### Oprava

Hyper Text Markup Language, ve zkratce HTML je značkovací jazyk. Nejedná se tedy o klasický programovací (jako C#) nebo skriptovací (JavaScript/Lua) jazyk, ale o jazyk, který jenom definuje určité data a to v XML s vlastními definicemi tagů. Technologií XML se v předmětu WBA zabývat ale nebudeme — není nutné si to ani pamatovat.

HTML bylo představeno v roce 1990. Od té doby **vznikly** různé verze, ta nejdůležitější je HTML5 z roku 2012, kterou se ve WBA budeme zabývat. Tato verze se hlavně zaměřila na to, aby šel multimediální obsah spouštět na webu. Cílilo se i na to, aby webové stránky byly přehledné i pro počítače a **mohly** se jednodušeji **crawlovat**, resp. indexovat.

HTML se používají zejména pro webové stránky, protože definují různé tagy, které vytváří na stránce různé prvky, které může uživatel vidět. Tyto soubory mají obvykle příponu .html.

### Screenshoty

<img width="1440" alt="Screen Shot 2022-09-23 at 7 26 57" src="https://user-images.githubusercontent.com/94190837/191897000-11ae5128-e3c8-4d46-8047-515e594fd549.png">

### Vaše jméno

Jakub Hrbek

**Comment by cajthamlmatej** [comment]
Příště bych radši viděl nějaký přehlednější zápis změn, tady je hromada textu na tři chyby. Ale děkuji.
