### ISSUE TITLE
[MATERIÁL] LEKCE: Základní HTML

### ISSUE THREAD

**Issue by JakubHrbek** [ssps-cajthaml/issues#130]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

LEKCE: Základní HTML

### Popis problémů

Je tam napsáno že jsou rastrové nebo rastrové obrázky. Opravil jsem to na rastrové nebo vektorové.

### Lokace

Soubory na webových stránkách

### Oprava

Na webových stránkách chceme například i obrázky. Nejzákladnější typy jsou rastrové obrázky, které uvnitř ukládají jednotlivé pixely a v případě komprimace nějaké zmenšené data. Druhé jsou vektorové obrázky, které místo jednotlivých pixelů ukládají rovnice, podle kterých se obrázek na počítači vykreslí. Rovnice jsou různého typu a způsobují, že se obrázky mohou nekonečně zvětšovat bez ztráty kvality. Na druhou stranu bývají (když jich máte desítky na webových stránkách), pomalé, protože se musí CPU zapojit v počítání. Pro rastrové obrázky známe přípony (resp. typy) .jpg, .png, .gif, .webp a pro **rastrové** .svg.

-->

Na webových stránkách chceme například i obrázky. Nejzákladnější typy jsou rastrové obrázky, které uvnitř ukládají jednotlivé pixely a v případě komprimace nějaké zmenšené data. Druhé jsou vektorové obrázky, které místo jednotlivých pixelů ukládají rovnice, podle kterých se obrázek na počítači vykreslí. Rovnice jsou různého typu a způsobují, že se obrázky mohou nekonečně zvětšovat bez ztráty kvality. Na druhou stranu bývají (když jich máte desítky na webových stránkách), pomalé, protože se musí CPU zapojit v počítání. Pro rastrové obrázky známe přípony (resp. typy) .jpg, .png, .gif, .webp a pro **vektorové** .svg.

### Screenshoty

<img width="1440" alt="Screen Shot 2022-09-23 at 7 31 33" src="https://user-images.githubusercontent.com/94190837/191897368-43bb1bf7-9ebe-4be0-b83b-ef13de1c5b67.png">

### Vaše jméno

Jakub Hrbek

**Comment by cajthamlmatej** [comment]
Děkuji.
