### ISSUE TITLE
[NÁPAD] Moznost filtrovani ukolu na strance "Práce"

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#131]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Pridani tlacitka nebo dropdownu (zalezi co bude vhodnejsi) pro filtrovani ukolu, ktere jsou po deadlinu/hotove/zadane na strance [Prace](https://ssps.cajthaml.eu/work).

Mohlo by to byt v horni casti v-card, kde je header.

### Zdůvodnění

Hodne ukolu by mohla zpusobit neprehlednost a delsi loading times (napr. na konci skolniho roku, kdyz bylo zadano hodne ukolu).
Kdyby byl filtr aktivni, zobrazi se mene ukolu a tudiz by to bylo prehlednejsi. Nemyslim si, ze je uplne nutne ukazovat ukoly, ktere jsou po deadlinu.

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Deadline vidíte po pravé straně. Úkoly jsou taktéž dle vašeho deadline seřazené a ty neaktivní jsou vždy dole. To nestačí dle vás? Aktuálně to není high priority, uvidíme, jak to bude fungovat ke konci roku s počtem úkolů. Minulý rok měla jedna třída dva předměty a bylo to OK.

**Comment by ItsOKayCZ** [comment]
Vim ze jsou serazene, ale matne si pomatuji (jelikoz to bylo na konci skolniho roku), ze se ukoly na strance nejakou dobu nacitali. Mozna se to uz nedeje.

Myslel jsem si, ze by to byl nice QoL feature pro ty, kteri nechteji videt vsechno najednou a chteji napr. videt jenom aktivni ukoly ze vsech predmetu.

**Comment by cajthamlmatej** [comment]
Načítá se to pomalu, protože je tam prostě spousta věcí. Museli by se nějak redukovat a to mi zabere hodně práce. Nechvam tu issue žít, ale silné pochybuji že se k tomu teď dostanu. :/

**Comment by cajthamlmatej** [comment]
Nový portál nemá tuto stránku, na hlavní stránce ma však overview aktivních úkolů, které mají brzy deadline a klikáním lze načíst celý list. Nemá tedy již smysl evidovat.
