### ISSUE TITLE
[WEB] Graf bodů ukazuje špatně s předvídačem

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#132]
### Popis problémů

Při přidání bodů nebo bodového základu do Předvídače na Osobním profilu graf ukazuje nové body na časové ose špatně - směrem vlevo.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na osobní profil
3. V Předvídači přidat nové body nebo bodový základ (kladné či záporné)
4. Přepnout si statistiky na Graf
5. Vidíme chybu

### Stránka

https://ssps.cajthaml.eu/dvop-wbb/profile
(nebo profil kteréhokoliv předmětu, kde už student má nějaké body)

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/Firefox/Brave/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

N/A

### Screenshoty

![image](https://user-images.githubusercontent.com/53367954/192104236-04cfd13a-f9f7-4e54-b9eb-6da6aca19de1.png)

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Nový portál již vyřešil.
