### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by Miconaut** [ssps-cajthaml/issues#133]
### Popis problémů

V lekci _LEKCE: Opakování předmětu Webové aplikace_ v sekci _Základní tagy_ chybí u tabulky u tagu _tr_ označení písmene _r_.

### Reprodukce problému

Postup k reprodukci:
1. LEKCE: Opakování předmětu Webové aplikace
2. Základní tagy
3. projet tagy až k `table / tr / td / th / tbody / thead / tfoot`

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/selfstudy/lekce-opakovani-wba/z%C3%A1kladn%C3%AD-tagy-62fbc75a2f6bb1446c035c0a

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://user-images.githubusercontent.com/71273636/192164649-d3a47096-5f61-4119-8541-c52af5ddc28b.png)

### Vaše jméno

Zdena Morávková

**Comment by cajthamlmatej** [comment]
Děkuji.
