### ISSUE TITLE
úkol 8

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#134]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

8. hodina, práce

### Popis problémů

přetékání textu

### Lokace

![6D23AE19-08CC-444C-93FB-94B24504AC2A](https://user-images.githubusercontent.com/73675802/192251823-ce5021f6-d064-43f3-a535-fa7d1b6c2ce8.png)

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Duplikát #89
