### ISSUE TITLE
Přidat základní formátování pro psaní poznámek pod lekce a další

### ISSUE THREAD

**Issue by lennerjiri** [ssps-cajthaml/issues#135]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Bylo by velkým zpříjemněním kdyby bylo možné v psaných poznámkách používat základní formátovaní jako:
H1
H2
H3
- 
1. 
Bold
Italic
Apod...

### Zdůvodnění

Když si píši poznámky pod lekce, jsou často velmi nepřehledné, kdyby bylo možné je více zpřehlednit pomocí těchto drobností bylo by to velké zpříjemnění. 

Taktéž bych navrhoval přidat podporu markdown (osobně jsem velkým **.md**  "enjoyerem" a věřím že  jsou tu další, kteří by to také ocenili právě nyní ale i v budoucnu!)

### Vaše jméno

Jiří Lenner

**Comment by cajthamlmatej** [comment]
Nový portál již vyřešil.
