### ISSUE TITLE
[MATERIÁL] Chybky v zadání úkolu

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#136]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

8. Kurzy - práce

### Popis problémů

Vloudilo se pár chybek ve shodách přísudků s podměty a tak

### Lokace

https://ssps.cajthaml.eu/dvop-wbb/work/8-kurzy

#### ZADÁNÍ
- bod 2: Rozdělit dlouhou druhou větu, takto nedává moc smysl - "Zapomněla se přidat hláška, když se vytváří soubor, přidejte hlášku." -> Navrhuji dát tečku mezi slova "soubor" a "Přidejte"
- bod 3: Ve 3. větě vypadlo slovo -> " Požadujeme, aby v souboru **byly** minimálně tři řádky […]"
- bod 7:
  * ­1. věta -> "dostal**y**" (soubory se dostaly)
  * ­3. věta -> doplnit čárku před "že" před "řešit"
  * ­4. věta -> "nemohl**y**" (soubory se dostat)
- předposlední bod: "na více" -> "**navíc**" (tohle je trošku diskutabilní, ale "na více" zní podstatně více archaicky a "navíc" je běžnější, srozumitelnější)
<hr>

#### ODEVZDÁNÍ
- nejvíce vnořený bod: zvýraznit jméno větve `main` codeblockem stejně, jako to je zvýrazněné všude jinde v zadání

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Děkuji.
