### ISSUE TITLE
[MATERIÁL] chyby v samostudiu

### ISSUE THREAD

**Issue by MrMartix** [ssps-cajthaml/issues#137]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Samostudium -> LEKCE: Základy CSS

### Popis problémů

1. si můžeme předsatvit (představit)
2. založeny na vlastnotech (vlastnostech)
3. Nejjednoduší zápis...(Nejjednodušší)
4. níčíme (ničíme)
5. Má přímonu (příponu)
6. a další speciálnít agy (speciální tagy)
7. uvedená ukazka (ukázka)
8. které definujií (definují)
9. existuje ješte (ještě)
10. Vlastnose nazývá (Vlastnost)
11. více jmén (jmen)
12. fontu.Vlastnost (fontu. Vlastnost)
13. nadpis Zloušťka textu (Tloušťka)
14. bude.Vlastnost (bude. Vlastnost)
15. je nejtenší (nejtenčí)
16. na Všechn prvích (nevím co tu má být správně)
17. na strance (stránce)
18. má větši (větší)
19. máme nékolik (několik)
20. však redudantní (redundantní)
21. o vlastno (vlastnost)
22. složených vlastnostích (vlastnostech)

### Lokace

1. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css
2.-5. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/z%C3%A1pisy-css-62c09ee856ef17b20d716597
6.-7. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/z%C3%A1kladn%C3%AD-selektory-62c09ee856ef17b20d716598
8.-9. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/koment%C3%A1%C5%99e-a-jednotky-62c09ee856ef17b20d716599
10.-16. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/z%C3%A1kladn%C3%AD-vlastnosti-62c09ee856ef17b20d71659a
17.-18. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/kask%C3%A1da-62c09ee856ef17b20d71659b
19.-20. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/z%C3%A1pis-barev-62c09ee856ef17b20d71659c
21.-22. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-zaklady-css/slo%C5%BEen%C3%A1-vlastnost-62c2fab656ef17b20d71c52d

### Vaše jméno

Martin Šíma

**Comment by cajthamlmatej** [comment]
Pár věcí v samostudium i po vašem zásahu zůstalo, ale velmi děkuji.
