### ISSUE TITLE
[MATERIÁL] Chybky v prezentaci "Git 3"

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#139]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

 9. hod | Git 3 (Gitové služby, dokumentace, zásady, klienti) 

### Popis problémů

Pár chyb v prezentaci "Git 3"

### Lokace

https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/
Prezentace na 9. hodinu

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/2/6/3
- "členi" → mn.č. je správně "členové"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/2/8/1
- "které" → "která" (spisovně)
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/2/8/5
- "zpětna" → "zpětná"
- "pompatibilita" → "kompatibilita"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/2/16
- "se ztrácíte" → "se vzdáváte"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/3/1/3
- "dovoluji" → "dovolují"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/4/2
- přidat čárku mezi "reprezentovat" a "co", ale tady si nejsem moc jistý
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/4/6
- "ve kterých se daná issues tvoří" → "ve kterých se daná **issue** tvoří"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/5/3/1
- přidat čárku před "co se změnilo"
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/5/4/0
- kapitalizovat 'v' ve "Vás", aby to bylo stejné jako poslední řádek minulého slidu. Nebo v tom minulém dát malé 'v'
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/6/0/7
- tento řádek se nevejde na klasickou 16:9 obrazovku, naštěstí je to jenom "a další...", takže to mc nevadí
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/6/1
- přidat čárku mezi "způsob" a "jak" a odebrat čárku před "když" → "Nejlepší způsob, jak se učit, je se učit za běhu když něco děláte a Googlit!"
- tbh tady si taky nejsem úplně jistý
<hr>

### https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/9.html#/7
- odebrat "tak" → "Git nyní bude v různých samostatných i týmových pracích vyžadován a kontrolován."
<hr>

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Děkuji.
