### ISSUE TITLE
[WEB] Počítačka kruhu - matoucí práce s kurzorem (drobná chyba v zadání)

### ISSUE THREAD

**Issue by Atlasik1** [ssps-cajthaml/issues#141]
### Popis problémů

V níže zmíněné práci se dole v sekci odevzdání píše, že "v úkolu nepracujte s pohybem kurzoru (není potřeba).", přitom se nahoře píše, že "v této fázi není vidět kurzor, po pokračování se znova zobrazí.", tedy je to sice drobná chyba, ale může být matoucí, a proto se jí vyplatí napravit.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Přepnout se do "Programování a vývoj aplikací" (2. ročník)
3. Kliknout na "Práce"
4. Zobrazit si práci "(6.) Počítačka kruhu"

### Stránka

https://ssps.cajthaml.eu/2-pva/work/6-pocitacka-kruhu

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

<img width="205" alt="4dwq6d489wqd" src="https://user-images.githubusercontent.com/81028632/193550749-ae4daa90-4569-485c-b268-0a46ff4697bd.PNG">
<img width="414" alt="dwqdqwdqwd" src="https://user-images.githubusercontent.com/81028632/193550753-7271a50a-e681-4c97-9f70-c114b08313de.PNG">

### Vaše jméno

Beneš Ondřej

**Comment by cajthamlmatej** [comment]
Píše se tam, že se nemá hýbat s kurzorem, nemluvíme v té větě o jeho viditelnosti.
