### ISSUE TITLE
[NÁPAD] Nastavení textového pole na přihlašování na portál na typ e-mail

### ISSUE THREAD

**Issue by therealrufus** [ssps-cajthaml/issues#142]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Při vyplňování emailu na přihlášení na webový portál se nevyplňuje automaticky email, protože textové pole má typ text. 

### Zdůvodnění

Jsem líný psát svůj email ručně a věřím že nejsem sám.

### Vaše jméno

Filip Brož

**Comment by cajthamlmatej** [comment]
Zajímavé, že nic takové ještě nebylo. Přidáno. :)
