### ISSUE TITLE
[MATERIÁL] Chybky v informacích k předmětům

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#143]
### Jméno předmětu pro který byl materiál vytvořen

Ostatní

### Materiál

Stránka Informace ve všech předmětech + homepage

### Popis problémů

V informacích k předmětu se nacházejí drobné chyby v textu.

### Lokace

1. chybka je na základní stránce, která se zobrazí při otevření portálu.
Zbytek je v záložce "Informace" u všech předmětů (nebo alespoň u těch 2, co jsem kontroloval)

### https://ssps.cajthaml.eu/
- záložka "Přihlášení": 2. věta: "jsou účty vytvořen" -> "vytvořen**y**"
<hr>

*věci níže platí pro všechny předměty, kde jsou dané podstránky na záložce Informace, přikládám odkazy na DVOP, protože to je můj předmět*

### https://ssps.cajthaml.eu/dvop-wbb/page/konzultace
- odstavec Průběh: "najednou, případně potřeby samostatně" -> "**v případě**"
<hr>

### https://ssps.cajthaml.eu/dvop-wbb/page/nahlasovani-chyb-a-testovani
- 3­. odstavec: "V těchto hlášení musíte být velmi přesný a" → "velmi přesn**í**" (a možná "hlášení" → "hlášeních")
- 4­. odstavec: "Studuje-li student více předmětu," → "předmět**ů**"
<hr>

### https://ssps.cajthaml.eu/dvop-wbb/page/reseni-uloh
- 2­. odstavec: "veřejně a prohokoliv k dispozici." -> "**pro kohokoliv**"
- poslední odstavec: přidat čárku mezi "**nezkoumají**" a "**proč to neměli dobře**"

### https://ssps.cajthaml.eu/dvop-wbb/page/automaticke-hodnoceni
- konec 1. věty: "předpřipraveným systém" -> "**systémem**"
- 2­. věta 2. odstavce: "a pro studenty" -> "**a studenti**"
- odstavec pod výčtem výhod: "program, které odevzdání hodnotí" -> "**který**"
- 3­. odstavec v Zadání, 2. věta: "dostaly málo body" -> "**bodů**"
- předposlední odstavec: přidat čárku do "při zaseknutí si přečíst celé zadání je totiž skoro jisté" mezi "**zadání**" a "**je**"
- Možná by to chtělo upravit genderovou neutralitu posledních 2 odstavců, ale to je taková blbost trošku.
<hr>

### https://ssps.cajthaml.eu/dvop-wbb/page/kriteria-hodnoceni
- Bodový systém, bod 6: nepíše se "mimo hodinový" spíš jako jedno slovo? not sure tbh, protože to není normální slovo
- Bodový systém, bod 6: "které zvyšují bodový základ, ale zlepšují studentovi známku." -> "**ne**zvyšují bodový základ"
- poslední bod části Práce: odkaz na portál by nejspíš měl být označený jako odkaz, když tak jsou všechny ostatní zmínky na stránce

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Homepage již tento text nemá. Ostatní jsem opravila brzy zpropaguji do dalších předmětů. Body dávno uděleny. Můžete si zažádat o tlapky.
