### ISSUE TITLE
[MATERIÁL] Chybky v informacích k STP a MAP

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#144]
### Jméno předmětu pro který byl materiál vytvořen

Studentské a maturitní projekty, 3. a 4. ročník

### Materiál

záložka Informace v předmětu STP&MAP

### Popis problémů

Drobné chyby v informacích k předmětu STP a MAP

### Lokace

- https://ssps.cajthaml.eu/projekty-a-prace/page/informace-o-projektech-a-pracich
- https://ssps.cajthaml.eu/projekty-a-prace/page/harmonogram
- https://ssps.cajthaml.eu/projekty-a-prace/page/analyza

### https://ssps.cajthaml.eu/projekty-a-prace/page/informace-o-projektech-a-pracich
- 3­. odstavec: vypadlo slovo "žáci", kdo bude prezentovat. nebo spíš slovo "**studenti**". Nebo tam místo "budou" dát "**budete**"
- 2­. odstavec pod seznamem bodů: "ve které se nacházejí" → "**kterém**"
<hr>

### https://ssps.cajthaml.eu/projekty-a-prace/page/harmonogram
- 4­. odstavec: "dohromady dávali" → "dával**y**"
- další věta: odebrat "a" mezi "**2 výstupy**" a "**celkově za 40b**"
- odstavec s podtrženými body: "popisy by neměli" → "neměl**y**"; to je v té větě 2x
- poslední odstavec: "pro řešitelé" → "řešitel**e**"
- 1­. bod toho odstavce: "vánocích" má být velké **V**
- 2­. bod: "řešitelé" → "řešitel**e**"
- stejný bod: "zamezíte tím velmi možných problémů" → ???, not sure co tam má být, asi "zamezíte tím velkému množství problémů."
<hr>

### https://ssps.cajthaml.eu/projekty-a-prace/page/analyza
- 3­. odstavec: "Pan ředitel sepsat" → "sepsa**l**"
- seznam částí analýzy: Popis stávajícího stavu: přidat "kde" → ", **kde** popíšete, "

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Děkuji.
