### ISSUE TITLE
[MATERIÁL] Gramatické chyby

### ISSUE THREAD

**Issue by vojtahajek** [ssps-cajthaml/issues#145]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 4. ročník

### Materiál

Git 3 9. hod

### Popis problémů

Slovo nejzámější – neni N, jednou Váš velké v podruhé vaše malé v, nějaká dokumentace lze generovat – nějakou dokumentaci

### Lokace

snímek 5, snímek 9, snímek 22, 

### Screenshoty

![unknown](https://user-images.githubusercontent.com/91019978/195039995-b541ecf1-81ce-4e6b-bc49-ffb894091092.png)
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/91019978/195041965-a0b4f55e-8516-4c2c-bf18-e7eb2e5801c1.png">
 
<img width="992" alt="image" src="https://user-images.githubusercontent.com/91019978/195042078-824c5890-48f8-418e-9281-c1bdfc83cf10.png">

### Vaše jméno

Hájek Vojtěch

**Comment by cajthamlmatej** [comment]
Děkuji.
