### ISSUE TITLE
[MATERIÁL] chyby v samostudiu WBA 2.A

### ISSUE THREAD

**Issue by MrMartix** [ssps-cajthaml/issues#147]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

WBA 2. ročník - LEKCE: Obrázky, listy a tabulky

### Popis problémů

1. špatně napsán kód (viz. screenshot)
2. je definovaný a vysvéětlený (vysvětlený)

### Lokace

1. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-obrazky-mapy-listy/celostr%C3%A1nkov%C3%A1-str%C3%A1nka-63138647351319513ca297d9
2. https://ssps.cajthaml.eu/2-wba/selfstudy/lekce-obrazky-mapy-listy/seznamy-631df010976aa4cca641a5a1

### Oprava

    <div class="part1"></div>
    <div class="part2"></div>

### Screenshoty

![image](https://user-images.githubusercontent.com/113117044/195132743-79150759-2779-4a6d-a5ae-87400e3456af.png)

### Vaše jméno

Martin Šíma

**Comment by cajthamlmatej** [comment]
Děkuji.
