### ISSUE TITLE
[MATERIÁL] Chybky v lekci samostudia "HTTP, Api"

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#148]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

LEKCE: HTTP, API, formáty

### Popis problémů

Pár pravopisných chyb a překlepů.

### Lokace

- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/dekompozice-webov%C3%BDch-str%C3%A1nek-63145de8351319513ca2c160
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/http-6314639e351319513ca2c3be
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/vlastnosti-po%C5%BEadavk%C5%AF-63146907351319513ca2c6c2
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/form%C3%A1ty-dat-632057008b7ee73c1acd4d8e
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/verzov%C3%A1n%C3%AD-api-632247851f8d6eb4e9c222ac
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-http-api-formaty/ajax-6322d6841f8d6eb4e9c24782

#### Dekompozice webových stránek
- 2­. věta odstavce Frontend: "Je to důležití část webu" → "důležit**á**"
<hr>

#### HTTP
- 1­. věta "slouží především k přesunutu" → "k přesunu/přesunutí"
- odstavec Požadavek, bod Hlavičky: "která určuje různé metadata" → "kter**é** určují různá metadata"
- odstavec Požadavek, seznam metod, poslední bod: slovo "**ZDE**" není na nic nalinkované
- odstavec Odpověď, bod Hlavičky: "která určuje různé metadata" → "kter**é** určují různá metadata"
- poslední odstavec: "různé data" → "různ**á** data"
<hr>

#### Vlastnosti požadavků
- 1­. věta: "Pro požadavky by měli platit následující vlastnosti." → "měl**y**"
- bod 3: "a volat je později či opakovaně" → "volat **jej**"       ?? tbh nejsem si moc jistý záměrem původní věty
<hr>

#### Formát dat
- 1­. věta: " budou data odesílány a přijímány serverem" → "odesílán**a** a přijímán**a**"
- o 2 věty dál: "i jiná API, které používají" → "kter**á**"
- 3­. věta odstavce XML: "Všechny data musí být obalená" → "Všechna"
- 2­. odstavec části o XML: " Nevýhody XML již byly zmíněné - je velmi výřečný" → "výřečn**é**" (o kousek výš o xml mluvíte ve středním rodě)
- další věta "čitelný" → "čitelné" (stejný důvod)
<hr>

#### Verzování API
- hned začátek: "Důležitou součásti" → "součást**í**"
- začátek 2. odstavce: "s daty, které" → "kter**á**"
<hr>

#### AJAX
- 1­. věta 2. odstavce: "bez dat, které se doplní" → "kter**á**"
- poslední věta: "by vyhledávače nemohli" → "nemohl**y**"
<hr>

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Opraveno. Body byly již dříve uděleny, pokud chcete, řekněte si o tlapky, až opravím další issues.
