### ISSUE TITLE
[NÁPAD] Kalendář na úkoly

### ISSUE THREAD

**Issue by Matej2525** [ssps-cajthaml/issues#149]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Když v práci kliknu na kalendář, tak to zobrazí kalendář, ale už to nemá možnost zobrazit zpět seznam prací.
Proto bych přidal ikonku zpět na stejné místo jako je kalendář. 

### Zdůvodnění

Lenost hledat seznam prací v bočním panelu/menu. 

### Vaše jméno

Arazim Matěj

**Comment by cajthamlmatej** [comment]
Nový portál neukazuje kalendář na stejném místě, nemá smysl evidovat.
