### ISSUE TITLE
[NÁPAD] Cookie bar

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#155]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Od 1.1.2022 platí vyhláška, že všechny weby sbírající jakoukoliv formu cookies **musí** mít cookie bar, kde uživatel potvrzuje souhlas s použitím. Váš web tento element nemá a od 1.1 může být pokutován. Vím, že to máte napsané v podmínkách používání, ale správně, by to stačit nemělo.

### Zdůvodnění

**Nová povinnost od 1.1.2022.**

Buď se může přidat cookie bar a uživatel ho bude odklikávat. Nebo při úplně prvním přihlášením uživatele / prvním přihlášení po vydání updatu, by uživatel musel toto povolení udělit.

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Cookie bar je v portálu od začátku jeho vzniku, jen nebyl zapnut.
