### ISSUE TITLE
Gramatické chyby v zadání

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#157]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

20. Uvítání na ocenu

### Popis problémů

1) Na začátku příběhu je čtenář oslovován vypravěčem (...probudil ses v navlhlém oblečení...), dále ve třetím odstavci je příběh podáván ich formou (dodal jsem).

2) Druhý odstavec, cca v polovině "... spánku, kam v roce 3492 poslalo lidstvo studovat vědce." 
část věty za čárkou moc nedává v kontextu smysl.

3)O pár slov dál "Je velmi podobná té naší,..." spíš se hodí "té vaší"

4)Konec druhého odstavce "Víš, proč lidstvo poslalo právě tebe?" chybí čárka za "víš"

5)Třetí odstavec, cca v polovině "...studentem informačních technologií”, vyhrkl." nesedí do vyprávěcího stylu, ještě před chvílí to bylo z jiného pohledu.

6)O kousek dál, "Oběma se rozjasnily oči ale zároveň to vypadalo tak, že se oba snaží zadržet smích." před ALE chybí čárka

7)Další věta "Mimochodem, já jsem Ofélie a tohle je vedoucí mise Jeos" Jeos je název mise, nebo jméno vedoucího? pokud název mise tak v pořádku, jinak by před slovem Jeos měla být čárka.

8)Poslední věta čtvrtého odstavce "Ryby a vodní tvorové se totiž na této planetě chovají jinak, než u nás, a zpravidla platí, že jejich pohyb je předem daný." před než nebude čárka, před a taky ne (tady si nejsem jistá, ale jsem o tom vážně přesvědčená)

9) "Máme několik týmu vědců a analytiků..." týmů chybí koužek nad u

10) "Nástroj na sledování ryb umí sledovat právě čtvercové místa uvnitř obdélníkového tvaru". čtvercovÁ místa

11)"...dvourozměrné pole rozdělené na stejně velké čtvercové místa. " stejně velkÁ čtvercovÁ místa

12)"V daném místě zachytíme v prvním sledování právě tři typy ryb, které vždy plavou pouze na jedné ose (horizontální / vertikální). Třetí typ ryb je takový,... " Spíš dva typy plavou,... Třetí je takový... takhle je to matoucí

13) V části VÝSTUP, "číslo, reprezentuje čas (s neurčitou jednotkou času) od prvního měření, po kterém byly monitorované ryby na pozicích dle zadání" za slovem číslo nebude čárka

14) část "testování", vstupní data jsou pojmenovanÁ

### Lokace

definováno výše

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Děkuji.
