### ISSUE TITLE
Gramatická chyba v prezentaci [MATERIÁL] 

### ISSUE THREAD

**Issue by restfulcone96** [ssps-cajthaml/issues#158]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Tabulky 15. hodina WBA 

### Popis problémů

gramatická chyba ve slově

### Lokace

slide 8/36

### Oprava

Využívaly*

### Screenshoty

<img width="1087" alt="Screenshot 2022-11-03 at 14 01 41" src="https://user-images.githubusercontent.com/111734876/199727896-2f963117-55bc-46e6-b388-f3dc3859e048.png">

### Vaše jméno

Mia Neumanová

**Comment by cajthamlmatej** [comment]
Děkuji.
