### ISSUE TITLE
Překlep v materiálu[MATERIÁL] 

### ISSUE THREAD

**Issue by restfulcone96** [ssps-cajthaml/issues#159]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

LEKCE: Vícedimenzionální pole, výjimky a listy - struktury

### Popis problémů

překlep: po místo pro

### Lokace

LEKCE: Vícedimenzionální pole, výjimky a listy - struktury
(konec textu ke 4. obrázku)

### Oprava

pro

### Screenshoty

<img width="735" alt="Screenshot 2022-11-03 at 16 04 15" src="https://user-images.githubusercontent.com/111734876/199757753-15beaa34-ed10-4c7f-8dca-78f9fe779c88.png">

### Vaše jméno

Mia Neumanová

**Comment by cajthamlmatej** [comment]
Děkuji.
