### ISSUE TITLE
[WEB] Drag and drop soubory u domácích úkolů

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#16]
### Popis problémů

Možnost drag & drop souborů do domácích úkolů.
![Drap and drop example](https://user-images.githubusercontent.com/19969112/138743596-1c2e5cec-91d3-483e-baa0-d6d67e9a58cc.gif)

### Reprodukce programu

Nejedná se o chybu

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/work/21-webova-stranka-s-sass
nebo jakýkoliv domácí úkol v sekci **Práce**.

### Zařízení

Operační systém: Windows
Prohlížeč: Firefox Developer Edition
Je prohlížeč aktualizován na nejnovější verzi: Yes

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Přidáno ve verzi v3.0.4
