### ISSUE TITLE
[MATERIÁL] Úloha pro (20. ) Uvítání na oceánu

### ISSUE THREAD

**Issue by matysekDrak2** [ssps-cajthaml/issues#160]
### Jméno předmětu pro který byl materiál vytvořen

Studentské a maturitní projekty, 3. a 4. ročník

### Materiál

(20. ) Uvítání na oceánu testovací soubory

### Popis problémů

Poslední soubor test5.IN Má jako předpokládaný výstup třetí sítě před koncem "NEJDE".  Však dle programu a mé rychlé kontroly mi připadá že je již vyřešená  a tak by pŘedpokládaný výstup měl být "0".

### Lokace

Testovací materyály pro ulohu (20. ) Uvítání na oceánu

### Oprava

nahradit předposlední řádek test5.out "NEJDE" -> "0"

### Screenshoty

![obrázek_2022-11-04_151415907](https://user-images.githubusercontent.com/39623227/199996364-d6ab9054-0697-4ec9-8a67-fd41901e04cf.png)
![image](https://user-images.githubusercontent.com/39623227/199996506-6eb6e997-13c4-4d25-926f-49601cae14b6.png)

### Vaše jméno

Matyáš Novák 4.K

**Comment by cajthamlmatej** [comment]
Pátý test opravdu splnit nejde. Podívejte pozorněji. Poslední pozice # nikdy nebude splněna.

**Comment by matysekDrak2** [comment]
> Pátý test opravdu splnit nejde. Podívejte pozorněji. Poslední pozice # nikdy nebude splněna.
V tom případě se omlouvám za zbytečné issue. 
Mohl bych však poprosit o vysvětlení?  

Poslední # je na pozici 0;3 když začínám v levo nahoře. 
Druhé # je 0;1.

Ryby jsou 
Nepohzbující se na 0;1, ta plní první bod.
Druhá směřující v pravo stojí na 0;2, a nic nedělá (točí se doprava a doleva)
A třetí ryba je na 0;3 kde směřuje doprava ale také se jako druhá jen točí. + Její souřadnice se shodují s druhám bodem (0;3)

Chápu že nejspíš někde dělám chybu ale bohužel netuším kde.

**Comment by cajthamlmatej** [comment]
Třetí test vypadá takto:

```
4 1
 
x
>
>
 
#
 
#
```

Z toho přečteme, že máme ryby na pozicích `(1, 2)`, `(1, 3)` a `(1,4)`.  Zádání po nás chce, aby všechny ryby byly na pozicích `(1, 2)` a `(1, 4)`. Všechny ryby se však nehýbou, zůstávají na pozici, a poslední dvě se jenom otáčejí směrem. Na pozici `(1, 4)` nemáme žádnou rybu (zadání požaduje) a na pozici `(1,3)` naopak rybu máme, což zadání nepovoluje.
