### ISSUE TITLE
[MATERIÁL] Chybky v lekci samostudia o JS

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#161]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

LEKCE: JavaScript

### Popis problémů

Překlepy a pár gramatických chybek v samostudiu.

### Lokace

- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/%C3%BAvod-62a8f18737320f930b652407
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/prom%C4%9Bnn%C3%A9-631e3c7a887a07b14c19b8be
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/textov%C3%A9-hodnoty-631e3c7a887a07b14c19b8bf
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/cykly-632621909300ced0f177a2b9
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/porovn%C3%A1n%C3%AD-632627709300ced0f177ab68
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/objekt-632627709300ced0f177ab69
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-javascript/pole-632627709300ced0f177ab6a

### Úvod
- 2­. odst: "všechny"-> " všechn**o**"
- 2­. odst před "Často" bych dal "Nebo se"
- 2­. odst: "ukládané desetinné čísla." -> "**ukládána** desetinn**á** čísla."
- 3­. odst: "se weby posunuli" -> "posunul**y**"
poslední odst: "zvláštní z mnoha způsobů." -> "na mnoho způsobů"/"několika způsobů" idk 

### Proměnné
- 1­. odst: "dva typy a to" -> čárku před "a"
- 1­. odst: "jméno, které budeme [...] referovat" -> pravděpodobně by tam mělo být "na které", ale ono to slovo "_referovat_" v češtině znamena trošku neco jineho, než v angličtině (ze které jste to, předpokládám, bral) 
- 3­. odst: "a proměnné pomocí const" -> "a konstanty"
- ten kód je nějaký divný, nikdy se tam nepřiřazuje do welcome, úplně ten výstup nedává smysl
<hr>

### Textové hodnoty
- konec 1. odst: čárku před posledním "můžeme" bych změnil na tečku
- předposlední bod: `toUpperCass` -> `toLowerCase`
<hr>

### Cykly
- 1­. odst: "obecně platí že každý" -> přidat čárku před "**že**"
- odstavec Do While: "do" v druhé větě bych dal do code bloku, aby se nepletlo s normálním slovem
- stejná věta: "zvolá" mělo asi být "zavolá"
- body o částech cyklu for - 2.bod: "definujeme podmínku, velmi často závislou na té z inicializátoru" -> " závislou na **proměnné** z ..."
<hr>

### Porovnání
- 2­. odst: "hodnot a to tak, že" -> carka před "a"
- nad seznamem nerovnítek: čárku před "a to"
- poslední dva body toho seznamu: vypadlo slovo "se rovná" -> "větší než nebo **se rovná**"
<hr>

### Objekt
- "Jméno je vždy textové hodnoty" -> asi by to mělo být buď "textová hodnota" nebo "textového typu", 
- čárka za "C#"
- další odstavec: "Po klíčí" -> "Po klíč**i**"
- konec posledního kódu: "Objec.tkeys(" -> "Object.keys("
<hr>

### Pole
- konec textu: dal bych [] do code tagu, takhle je to v té závorce takové matoucí + to tak máte i nahoře

### Screenshoty

N/A

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
> ten kód je nějaký divný, nikdy se tam nepřiřazuje do welcome, úplně ten výstup nedává smysl
Protože to není možné, je to tam za komentované. Message je jen deklarována a potom se upravuje. Number je deklarována a inicializována ihned na místě. 

Stejná zpráva jako z minule - body dávno již uděleny, můžete si požádat o tlapky.
