### ISSUE TITLE
[NÁPAD]  Automatická konverze na velká písmena při zadávání kódu

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#162]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Přidání funkcionality, kdy se přemění písmena na velká písmena při zadávání přihlašovacího kódu -> https://ssps.cajthaml.eu/auth/validate

### Zdůvodnění

Každé písmeno v kódu je vždy velké písmeno a tudíž mi přijde, že je zbytečné mít možnost zadávat malá písmena

Je to spíš QoL feature.

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Nový portál tento problém vyřešil oklikou.
