### ISSUE TITLE
Překlep  v Samostudiu[MATERIÁL] 

### ISSUE THREAD

**Issue by MarekDudas** [ssps-cajthaml/issues#163]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

...

### Popis problémů

V Lekci: Vícedimenzionální pole, výjimky alisty
V sekci listy u .count a .capacity chybí závorka

### Lokace

https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-vicedimenzionalni-pole-vyjimky-listy/listy-6319d0e9976aa4cca63faa86

### Screenshoty

![Screenshot_20221124-101249_Samsung Internet](https://user-images.githubusercontent.com/118970485/203754977-3de3209f-7946-44e1-80a6-548ada6e0f33.jpg)

### Vaše jméno

Marek Dudáš

**Comment by cajthamlmatej** [comment]
Děkuji.
