### ISSUE TITLE
[MATERIÁL] 

### ISSUE THREAD

**Issue by MarekDudas** [ssps-cajthaml/issues#165]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Poselství

### Popis problémů

V zadání Poselství je překlep

### Lokace

-

### Screenshoty

<img width="89" alt="Snímek obrazovky 2022-11-27 115657" src="https://user-images.githubusercontent.com/118970485/204131678-73430dca-5316-41e3-bbc2-a20b97691c7f.png">

### Vaše jméno

Marek Dudáš

**Comment by cajthamlmatej** [comment]
To je tam schválně :(
