### ISSUE TITLE
[MATERIÁL] Překlep v prezentaci

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#167]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Express 1 Slide 4

### Popis problémů

Jednoudchý

### Lokace

Slide 4

### Oprava

Jednoduchý

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Děkuji.
