### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#169]
### Popis problémů

V dobrovolném úkolu *Vánoční přání* chybí jaký font se má použít

### Reprodukce problému

V zadání to není napsané

### Stránka

https://ssps.cajthaml.eu/2-wba/work/vanocni-prani

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Vaše jméno

Šulc Vojtěch

**Comment by cajthamlmatej** [comment]
To je zcela žádaná věc. Font naleznete na Google Fonts.
