### ISSUE TITLE
[MATERIÁL] Nová kategorie issues - "Nápady/zlepšení webu"

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#17]
### Jméno předmětu pro který byl materiál vytvořen

Ostatní

### Materiál

Github issues

### Popis problémů

Při vytváření issue na githubu není kategorie pro nápady či zlepšení webu.

### Lokace

Github :)

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Přidáno.
