### ISSUE TITLE
[MATERIÁL] 

### ISSUE THREAD

**Issue by Shell3** [ssps-cajthaml/issues#170]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 4. ročník

### Materiál

LEKCE: Opakování 3. ročníku

### Popis problémů

JWT -> BASE64 -> nejedná se o hash

### Lokace

https://ssps.cajthaml.eu/4-mvop-wbf/selfstudy/lekce-opakovani-3-rocniku/autentizace-a-autorizace-62f6476630ee5205a5346ac0

### Vaše jméno

Daniel Mulač

**Comment by cajthamlmatej** [comment]
Děkuji.
