### ISSUE TITLE
[MATERIÁL] Express 4

### ISSUE THREAD

**Issue by michalhejd** [ssps-cajthaml/issues#171]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Express 4

### Popis problémů

- Vrsty(chybí v)

### Lokace

17. slide

### Oprava

Vrstvy

### Screenshoty

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/71251670/212716461-4a956f01-0807-4765-b0c7-0dcf3330a798.png">

### Vaše jméno

Michal Hejduk

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Body jsem dávno uložil.
