### ISSUE TITLE
PVA- 2.r. - 31. hodina | Datum a čas

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#172]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

31. hodina | Datum a čas (prezentace)

### Popis problémů

24. slide --> místo Počet dní v roce je počet měsíců v roce

### Lokace

24. slide

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Opraveno. Body dávno uděleny. Můžete si zažádat o tlapky.

**Comment by krystinkad** [comment]
plsky plsky vzdy jjj
