### ISSUE TITLE
Item zustane equipnuty po trade-upu

### ISSUE THREAD

**Issue by MarekProkopec** [ssps-cajthaml/issues#173]
### Popis problémů

Kdyz si dam item co mam zrovna vybrany na profilovce to trade-upu, tak mi zustane na profilovce ikdyz ho uz nemam, z inventare zmizi a nelze ho vybrat

### Reprodukce problému

Postup k reprodukci:
Vybrat item
Dat ho do trade-upu

### Stránka

Sidebar

### Zařízení

Operační systém: **Android**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Marek Prokopec

**Comment by cajthamlmatej** [comment]
Nový portál již vyřešil.
