### ISSUE TITLE
Chyba v prezentaci 

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#175]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 4. ročník

### Materiál

Express 4

### Popis problémů

Chyba na 17 straně 

### Lokace

17

### Oprava

Vrsty změnit na vrstvy 

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Duplikát.
