### ISSUE TITLE
[WEB] Předvídač chyba s desetinnými čísly

### ISSUE THREAD

**Issue by milansav** [ssps-cajthaml/issues#18]
### Popis problémů

Při sčítání specifických čísel (např: 36.6 + 0.2) se výsledek v předvídači nezaokrouhluje

### Reprodukce programu

Postup k reprodukci:
a)
1. console.log(36.6+0.2)
2. Profit.
b)
1. Mít 36.6 bodů
2. Jít do osobního profilu -> předvídač
3. Zadat 0.2 získaných bodů
4. Profit

### Stránka

https://ssps.cajthaml.eu/2-wba/profile

### Zařízení

Operační systém: **Manjaro**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![IEEE754_1](https://user-images.githubusercontent.com/47496309/140478376-8950b1e3-12c8-4231-a945-d934d53f68fa.png)
![IEEE754_2](https://user-images.githubusercontent.com/47496309/140478382-6d86c5dd-3761-4aae-837b-a4cbf42ef691.png)

### Vaše jméno

Milan Savickij

**Comment by cajthamlmatej** [comment]
Oprava bude nahrána v další verzi. Děkuji za nahlášení.
