### ISSUE TITLE
Lekce: Vue

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#187]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 3. ročník

### Materiál

Lekce: Vue

### Popis problémů

Aktuální stav: je zde napsané "jedením" v druhé části v prvním odstavci 

### Lokace

https://ssps.cajthaml.eu/3-mvop-wbf/selfstudy/lekce-vue

### Oprava

Požadovaný stav: napsané jedním

### Screenshoty

![Screenshot_20230519-081237-612~2](https://github.com/ssps-cajthaml/issues/assets/107812788/57c28ef2-0014-4412-87a7-485b7a4e96b9)

### Vaše jméno

Vojtěch Šulc

**Comment by cajthamlmatej** [comment]
Opraveno. Body dávno uděleny. Můžete si zažádat o tlapky.
