### ISSUE TITLE
LEKCE: Asynchronní JS

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#189]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

LEKCE: Asynchronní JS

### Popis problémů

Označením funkce jako asynchronní se nyní změnění její návratový typ na slib.
->
Označením funkce jako asynchronní se nyní změní její návratový typ na slib.

### Lokace

LEKCE: Asynchronní JS, kapitola Asynchronní funkce

**Comment by cajthamlmatej** [comment]
Opraveno. Body dávno uděleny. Můžete si zažádat o tlapky.
