### ISSUE TITLE
[WEB] Nový časovač se nesprávně scaluje

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#19]
### Popis problémů

Text časovače se nescaluje, když se s oknem hýbe (nebo na mobilu)

### Reprodukce programu

Postup k reprodukci:
1. Jít na ssps.cajthaml.eu/timer
2. Jakkoliv upravit velikost okna
3. :tada

### Stránka

https://ssps.cajthaml.eu/timer

### Zařízení

Operační systém: **macOS**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

<img width="576" alt="image" src="https://user-images.githubusercontent.com/59232422/140644957-cffac30a-9d30-43bc-8dc3-38891dd40e86.png">

### Vaše jméno

Sebastian H.

**Comment by cajthamlmatej** [comment]
Nahráno.
