### ISSUE TITLE
prezentace

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#190]
### Jméno předmětu pro který byl materiál vytvořen

OSE Informatické semináře, 3. ročník

### Materiál

prezentace o zdrojování,...

### Popis problémů

zdorjů

### Lokace

![IMG_6577](https://github.com/ssps-cajthaml/issues/assets/73675802/7e5667b4-b27f-47c9-9376-2b89a1f54c5e)

### Vaše jméno

Kristýna D

**Comment by cajthamlmatej** [comment]
Opraveno. Děkuji - bodíky na cestě.
