### ISSUE TITLE
[WEB] Překlepy, formulace, ...

### ISSUE THREAD

**Issue by Silhavi** [ssps-cajthaml/issues#191]
### Bc. Matěj Cajthaml
https://ssps.cajthaml.eu/
4. odstavec, poslední slovo - "pozivitně"

### Podmínky používání
https://ssps.cajthaml.eu/legal/terms-of-use
‎1. odstavec, 1. řádek - chybí tečka za trojkou "3 řádu"

### Automatické hodnocení
https://ssps.cajthaml.eu/2-wba/announcements/automaticke-hodnoceni-64d9ee5979dad891e8a06f60
7. bod, 3. řádek - "viz."
8. odstavec, 3. řádek - "viz."
_v český textech se používá "viz" bez tečky_

### Řešení úloh
https://ssps.cajthaml.eu/2-wba/announcements/reseni-uloh-64d9ee8479dad891e8a06f8c
zelený rámeček, 2. řádek - "viz."

### Nahlašování chyb a testování
https://ssps.cajthaml.eu/2-wba/announcements/nahlasovani-chyb-a-testovani-64d9eebd79dad891e8a06ff2
		2. odstavec, 5. řádek - namísto "a nebo", použít "nebo"/"anebo"
		pod "Nahlášení mají další pravidla:", 2. bod, 2. řádek - čárka před "ale"
		5. odstavec, 4. řádek - "kontaktování"

### Konzultace
https://ssps.cajthaml.eu/2-wba/announcements/konzultace-64d9eef779dad891e8a07058
		(pod _Přihlášení:_)
			3. bod - "a nebo"

### Využití umělé inteligence
https://ssps.cajthaml.eu/2-wba/announcements/vyuziti-umele-inteligence-64f623761f7d9ac487d14cf4
		2. odstavec, 1. řádek - "uměle inteligence"
		2. odstavec, 2. řádek - namísto "na více", použít "navíc"
		2. odstavec, 3. řádek - "uměle inteligence"

### Jak fungují zkoušení?
https://ssps.cajthaml.eu/2-wba/exams/
		2. odstavec, 2. řádek - čárka před "po"
		
### Jak se připravit na zkoušení?
https://ssps.cajthaml.eu/2-wba/exams/
		1. odstavec, 3. řádek - přepsat "do celoobrazovém (fullscreen) módu"
		
### Kdo zkoušení hodnotí a jak?
https://ssps.cajthaml.eu/2-wba/exams/
		2. odstavec, 1. řádek - přepsat "vysvětleno u jednotlivých otázkách"
		
### S hodnocením nesouhlasím / chci se na vyplněný test podívat.
https://ssps.cajthaml.eu/2-wba/exams/
		1. odstavec, 3. řádek - "převedy"
		1. odstavec, 4. řádek - "nato"
		2. odstavec, 2. řádek - "a nebo"

### Reprodukce problému

spuštění stránky a přečtení textu

### Stránka

již uvedeno v popisu problémů

### Zařízení

Operační systém: Windows
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Vaše jméno

Petr Saksun

**Comment by cajthamlmatej** [comment]
Děkuji. Tyto chyby byly opraveny. Bude vidět následující verzi a snad brzy dobublá i do jiných předmětů. Body budou uděleny.
