### ISSUE TITLE
Chyba zvětšování kódu v prezentacích 

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#192]
### Jméno předmětu pro který byl materiál vytvořen

Ostatní

### Materiál

Každá prezentace s kódem 

### Popis problémů

Když si uživatel chce rozkliknout kód v prezentaci tak se kod nezvetsi na celou stránku avšak jen kód se přiblíží.

### Lokace

Každá prezentace y kódem.

### Oprava

Kód se roztáhne.

### Screenshoty

![Screenshot_20230911-150414](https://github.com/ssps-cajthaml/issues/assets/107812788/3d078ce1-2a0d-42af-b1ce-a1e567df8b3c)

### Vaše jméno

Vojtěch Šulc

**Comment by NewSulc** [comment]
Stále neopraveno.

**Comment by cajthamlmatej** [comment]
Opravdu to nebylo opraveno. Je nutné počkat a ne zbytečně problém upovat.

Řešení není jednoduché. Ono to funguje, jen to nefunguje pomocí iframe na portálu. Je lepší, když na to šahat nebudu.
