### ISSUE TITLE
Úvodní prezentace překlik

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#193]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

1. prezentace

### Popis problémů

apliakce

### Lokace

slide 21
![IMG_6784](https://github.com/ssps-cajthaml/issues/assets/73675802/81d7eced-69d3-4bc6-b19f-9dcf138ea505)

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Opraveno. Děkuji - bodíky na cestě.
