### ISSUE TITLE
[WEB] Špatně viditelné předměty v customizaci

### ISSUE THREAD

**Issue by Dusicek** [ssps-cajthaml/issues#194]
### Popis problémů

Černé filtry a rámečky, při upravování profilu, nejsou v tmavém režimu vidět.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na přepnutí do tmavého režimu (pokud ho už nemáme)
3. Kliknout na tlapky (dostat se na úpravu profilu)
4. Kliknout na úpravu filtru/rámečku
5. Pokud máme černé filtry/rámečky tak vidím jen název bez vizualizace

### Stránka

https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Opera/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano i ne (školní počítač)**

### Chyba

\```...```

### Screenshoty

![Výstřižek](https://github.com/ssps-cajthaml/issues/assets/91528299/55157705-a234-4fff-afa2-ebddc08a01f7)
![Výstřižek2](https://github.com/ssps-cajthaml/issues/assets/91528299/5175446d-0d23-4a57-811c-918173f46138)

### Vaše jméno

Kristián Š.

**Comment by cajthamlmatej** [comment]
Nápad, jak toto vyřešit? Nic dobrého mě nenapadá.

**Comment by cajthamlmatej** [comment]
Prozatím jsem jen zesvětlil barvy. Děkuji. Body udělím. Bude viditelné v další verzi.
