### ISSUE TITLE
[WEB] Nelze vypočítat hodnocení po obnovení stránky

### ISSUE THREAD

**Issue by Reblexis** [ssps-cajthaml/issues#198]
### Popis problémů

Pokud se podívám u jakéhokoli předmětu na své hodnocení (získané body), tak se nejprve ukazuje bodové hodnocení správně, ale když se manuálně obnoví stránka, tak se hodnocení neukáže se zprávou, že "nelze vypočítat" a podobné věci, prostě se to "nerefreshne".

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na jakýkoli předmět v selekci "Změna předmětu".
3. Kliknout na hodnocení.
4. Po načtení stránky zmáčknout F5 či jinak obnovit stránku.

### Stránka

Např. [https://ssps.cajthaml.eu/4-ose-pvs/grading/](https://ssps.cajthaml.eu/4-ose-pvs/grading/)

### Zařízení

Operační systém: Linux
Prohlížeč: Firefox a Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

text: nelze vypočítat

### Screenshoty

Před
![image](https://github.com/ssps-cajthaml/issues/assets/80317928/eff05e5a-e201-4669-aa7a-97fa2d262290)
Po
![image](https://github.com/ssps-cajthaml/issues/assets/80317928/be651b68-6c78-41f6-9223-595ced3b33b9)

### Vaše jméno

Viktor Číhal

**Comment by cajthamlmatej** [comment]
Opraveno. Bude viditelné v další verzi. Děkuji - udělil jsem body. :)
