### ISSUE TITLE
Chyba ve slově licence - Dvop 3 opakování 

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#199]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

DVOP 3 opakování 

### Popis problémů

Ve slidu o autorském zákonů, ve 4 bodě je místo slova LICENCI napsáno slovo LINCENCI

### Lokace

https://ssps.cajthaml.eu/3-dvop-wbb/lesson/opakovani/part/64df7c7eef51274005f98320

### Vaše jméno

Vojtěch Šulc

**Comment by NewSulc** [comment]
Již opraveno. **Žádám o body.**

**Comment by cajthamlmatej** [comment]
Opraveno. Body přidělím.

Prosím, nespamujte neuzavřené issues. Problém byl vyřešen až dnes.
