### ISSUE TITLE
[WEB] problém s kalendářem

### ISSUE THREAD

**Issue by Jiri-Lenner** [ssps-cajthaml/issues#20]
### Popis problémů

Problém s nově přidaným kalendářem.
Vypisuje se 21 před rokem přidání úkolu.
Odkaz více informací nemá žádný kontrast.
Netestoval jsem u jiných tříd, nebyly zatím přidány jiné eventy nežli ten u MVOPU, je možné že problém platí pro všechny třídy (MVOP, WBA, PVA).

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se
2. Kliknout na práce
3. Kliknout na iknonku kalendáře (odkaz, který nás přesměruje na kalendář)
4. Kliknout na daný event
5. Problémy se nyní vyobrazí

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/calendar

### Zařízení

Operační systém: *iOS**
Prohlížeč: **Firefox i Google**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Screenshot 2021-11-07 at 16 54 46](https://user-images.githubusercontent.com/78266342/140652241-6850eca7-e53e-478c-bb6d-92abe2bdca67.png)
![Screenshot 2021-11-07 at 16 54 48](https://user-images.githubusercontent.com/78266342/140652242-8cd3c856-f73c-4b32-aa6e-b61edb10083c.png)
![Screenshot 2021-11-07 at 16 54 52](https://user-images.githubusercontent.com/78266342/140652243-e4404dfa-f86b-41d3-8628-88c8fcbaf526.png)

### Vaše jméno

Jiří Lenner

**Comment by cajthamlmatej** [comment]
Opraveno.
