### ISSUE TITLE
[WEB] Špatně roztažené menu 

### ISSUE THREAD

**Issue by Dusicek** [ssps-cajthaml/issues#200]
### Popis problémů

Border menu na straně není až dolů. 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Koukat
3. Profit.

### Stránka

jakákoliv defakto

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/OperaGX...**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91528299/662b154c-4438-4278-b4ee-8f0a3a013de5)

### Vaše jméno

Kristián Š.

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím. Bude viditelné v další verzi.
