### ISSUE TITLE
[MATERIÁL] Překlep v prezentaci o grafech

### ISSUE THREAD

**Issue by Reblexis** [ssps-cajthaml/issues#201]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Grafová teorie

### Popis problémů

Ve úkolu, kdy máme nakreslit doplňky grafů je napsáno dvakrát G_2, místo jednou G_3.

### Lokace

19

### Vaše jméno

Viktor Číhal

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Body přidělím.
