### ISSUE TITLE
[WEB] gramatika a pravopis 

### ISSUE THREAD

**Issue by Matej2525** [ssps-cajthaml/issues#202]
### Popis problémů

Práce ještě nebyla zadána a proto ji nelze odevzdávat. Chybí čárka -> a proto 

### Reprodukce problému

bez přihlášení, i s přihlášením 

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit/work/grafy-1-grafu-na-vrcholech

### Zařízení

ios, safari, akt. ano 

### Chyba

\```...```

### Vaše jméno

Arazim Matěj 4.A

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím.
