### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#203]
### Popis problémů

Ve stavu úkolu je pravopisná chyba.

Práci:
máte neodevzdánou.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "DVOP4 Práce".
3. Rozkliknout práci.
4. Vidět.

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit/work/grafy-1-grafu-na-vrcholech

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114414946/70d2ad3f-6ef6-4c09-a911-47828d95f954)

### Vaše jméno

Kiripolský Pavel

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím.
