### ISSUE TITLE
[WEB] Odevzdávání úkolů 

### ISSUE THREAD

**Issue by Matej2525** [ssps-cajthaml/issues#204]
### Popis problémů

Nejde smazat vybraný soubor před odevzdáním, jinak než f5. Stažení posledního odevzdání je ve formátu .bin na macu bez stažení programu nezobrazitelné. Nejdou smazat předchozí odevzdání (co když tam omylem někdo dá zip. bombu a chce ji dát pryč). Shrnutí starý portál byl funkční, lepší, graficky přijatelnější - vlastní názor.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Jít do úkolu.
3. Vybrat soubor na odevzdání a odevzdat ho.
4. Zbytek je popsán v "popis problému"

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit/work/grafy-1-grafu-na-vrcholech

### Zařízení

Operační systém: ios
Prohlížeč: safari
Je prohlížeč aktualizován na nejnovější verzi: ano

### Screenshoty

<img width="524" alt="Snímek obrazovky 2023-09-20 v 21 26 29" src="https://github.com/ssps-cajthaml/issues/assets/84710956/a5bf1c40-be53-456f-9827-aa1343b5af19">

<img width="363" alt="Snímek obrazovky 2023-09-20 v 21 16 17" src="https://github.com/ssps-cajthaml/issues/assets/84710956/454df97f-e265-4caa-a66b-3b9d845616f6">

### Vaše jméno

Arazim Matěj 4.A

**Comment by cajthamlmatej** [comment]
Nemožnost mazat staré odevzdání je featura, jak jsem již zmiňoval na Discordu. Lidé s tím minulé roky akorát dělali blbosti. To co nahrajete, musí být vaše finální práce a další mají být jen inkrementální opravy. Tímhle zaručím, že po zhodnocení to nikdo nesmaže a už to nebude vyhledatelné. 

Smazání souboru po volbě jsem přidal, bude viditelné až bude nahrána nová verze.

Ke stahování (resp. přípony) jsou tam větší problémy, pokusil jsem se je vyřešit, můžete zkontrolovat až se nahraje nová verze.

Aktualizace je důležitá pro inovaci a vše se bude posouvat kupředu, snad v dobrém směru. Život je plný změn a je důležité je respektovat.

Děkuji. Body udělím.
