### ISSUE TITLE
[WEB] Špatný popis při najetí na ikonku tisku ve skriptech

### ISSUE THREAD

**Issue by TERROR-404** [ssps-cajthaml/issues#205]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Týká se to všech skript, ale našel jsem to ve skriptech pro Verzovací systémy

### Popis problémů

Při najetí na ikonku tiskárny/tisku se zobrazí popisek "Zpět k lekci"

### Lokace

Skripta

### Oprava

Prostě to přepiš lol

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/69761253/87da675a-859e-4589-8ed8-4990b80f004a)

### Vaše jméno

Bohumil Čmerda

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím. Bude viditelné v další verzi.
