### ISSUE TITLE
[WEB] Scrollovaní ve skriptech

### ISSUE THREAD

**Issue by TERROR-404** [ssps-cajthaml/issues#206]
### Popis problémů

Když ve skriptech v jedné sekci např. "Verzovací systémy" scrollnu dolů, a pak překliknu na jinou sekci např. "Historie", tak stránka místo toho aby začínala nahoře, tak je scrollnutá dolů už předem o takovou část, jakou jsem scrollnul u první sekce.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "Lekce"
3. Kliknout na "studovat lekci"
4. Kliknout na "Skripta"
5. Scrollnout trochu dolů
6. Kliknout na "Historie"
7. Profit.

### Stránka

https://ssps.cajthaml.eu/3-dvop-wbb/lesson/verzovaci-systemy/part/64df7f48ef51274005f99812/verzovaci-systemy

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

nejde démone

### Vaše jméno

Bohumil Čmerda

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím. Bude viditelné v další verzi.

**Comment by MasterJay8** [comment]
nn, neopravil to

**Comment by TERROR-404** [comment]
![image](https://github.com/ssps-cajthaml/issues/assets/69761253/8386bc4e-7228-448a-b111-9f7682b8224e)

**Comment by TERROR-404** [comment]
![image](https://github.com/ssps-cajthaml/issues/assets/69761253/c1822d10-b99d-476a-a604-b827e8653030)
![image](https://github.com/ssps-cajthaml/issues/assets/69761253/bbb4bb0d-23e8-47b4-8e48-253343c33ad8)

**Comment by cajthamlmatej** [comment]
Snad již opraveno.
