### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by fanda857** [ssps-cajthaml/issues#207]
### Popis problémů

Po vybrání typu známky v předvídači se výběr známky nezavře a je posunutý

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na hodnocení > předvídač
3. změnit typ známky
4. typ známky se změní ale vyběr se nezavře

### Stránka

https://ssps.cajthaml.eu/2-wba/grading/

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome, Opera**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Capture](https://github.com/ssps-cajthaml/issues/assets/65150803/d58151ac-f3a0-4515-ba15-ad1f1a730b85)

### Vaše jméno

František Václavek

**Comment by cajthamlmatej** [comment]
Výběr se zavírat nemá, to je takový stav, který jsem se rozhodl mít. To, že je to špatné umístěné již problém je. 


Děkuji. Body udělím. Bude viditelné v další verzi.
