### ISSUE TITLE
[WEB] Mínus tlapky

### ISSUE THREAD

**Issue by MasterJay8** [ssps-cajthaml/issues#208]
### Popis problémů

nejdou mínus tlapky

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Vybrat kód s mínus tlapkami
3. stránky down
4. Profit.

### Stránka

cajthaml.eu

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

chyba

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/113784571/c1df7e59-07a7-408b-ac47-d3f1258ee782)

### Vaše jméno

Jiří Paďour

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím. Bude viditelné v další verzi.
