### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by AntonBrodman** [ssps-cajthaml/issues#209]
### Popis problémů

Student nemůže mít mínusové tlapky

### Reprodukce problému

Postup k reprodukci:
1. Uplatnění qr kódu
2. Body na stránce se nemění
3. ?
4. Testasticular cancer.

### Stránka

Stránka kustomizace

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

QR kód nefunguje

**Comment by cajthamlmatej** [comment]
Duplikát #208.
