### ISSUE TITLE
[WEB] Nepřehlednost kalendáře 

### ISSUE THREAD

**Issue by Mifik11** [ssps-cajthaml/issues#21]
### Popis problémů

Při více dú najednou kalendář se stává nepřehledným. Různé dú si mezi sebou protínají a pro jejích rozlišování se musí číst název. Pro vyřešení problému stačí pro každé dú dávat svojí barvu.

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na práce
3. Kliknout na ikonu kalendáře
4. Profit.

### Stránka

https://ssps.cajthaml.eu/2-pva/calendar

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Screenshoty

![unknown](https://user-images.githubusercontent.com/71230387/140987729-ae7a95a7-d7fc-44d2-95af-6037b0e87645.png)

### Vaše jméno

Oleksandr Petriv

**Comment by cajthamlmatej** [comment]
Děkuji, nějaký nástřel je již nahrán
