### ISSUE TITLE
[WEB] Mínus tlapky

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#210]
### Popis problémů

QR kód na mínus body nelze použít, pokud má student 0 bodů.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Naskenovat QR kód a mít bodů
3. Nefunguje

### Stránka

https://ssps.cajthaml.eu/user/customization/claim

### Zařízení

Operační systém: Windows
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

**Comment by cajthamlmatej** [comment]
Duplikát #208.
