### ISSUE TITLE
[WEB] floating point čísla

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#211]
### Popis problémů

Po nedávném získání bodů se mi na účet přičetlo taktéž 0.0000000000000007 bodu, tyto body se ukazují pouze u tlapek. To znamená, že do další tlapky mi aktuálně zbývá 2.9499999999999993 bodu. Jedná se teda o chybu čistě estetickou. Myslím si, že by měli čísla být zaokrouhlena na např. 2 desetinné místa, čili by zbývalo 2.95 bodu do další tlapky. Taktéž, celkový součet bodů profilu neukazuje přebytečných 0.0000000000000007 bodu.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na ikonku tlapky
3. podívat se kolik zbývá bodů do další tlapky
4. Profit 0.0000000000000007 bodu
5. Pomoc jak odstraním toto nehezké číslo 

### Stránka

https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Opera GX**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/90583f0c-f6f4-4952-aa82-375379db1ac5)
![image](https://github.com/ssps-cajthaml/issues/assets/114053327/d5d6690d-ecbe-4250-8358-37635ca12a4b)

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Snad opraveno. Děkuji. Body udělím. Bude viditelné v další verzi.
