### ISSUE TITLE
[NÁPAD] Nápověda při najetí

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#212]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Nápad by bylo podtržení tohohle místa určitým stylem, aby bylo vidět, že se na to dá najet myší.
![image](https://github.com/ssps-cajthaml/issues/assets/73956350/59a79beb-afed-4f47-a5b0-23731f117b33)

Mělo by to vypadat nějak takhle:
![image](https://github.com/ssps-cajthaml/issues/assets/73956350/5d0aca9b-aa4d-4fd7-90e0-238356da8e36)

Mohlo by to být na všech místech, kde se objevuje tooltip po tom, co se na určitý text najede myší.

### Zdůvodnění

Je to více intuitivní. Někteří lidé ani nevěděli (nebo neví), že se na to dá ukázat kurozrem a že se pak objeví tooltip.

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
Děkuji. Body udělím. Bude viditelné v další verzi.
