### ISSUE TITLE
[WEB] Překlepy, formulace, ...

### ISSUE THREAD

**Issue by Silhavi** [ssps-cajthaml/issues#213]
### Popis problémů

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/soubory-na-webovych-strankach
1. odstavec, 1. řádek - my si ukážeme jenom "hrstu"
3. odstavec, 1/2. řádek - nějaká zmenšená data, ne nějaké zmenšené data
4. odstavec, 2. řádek - "případě"
poslední odstavec - přepsat větu "Diakritika je špatná zejména na uživatelé z jiných zemích"
poslední odstavec, poslední řádek - "řadu problému" -> "řadu problémů"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/tag
2. odstavec, 1. řádek - chybí čárka před "že"
předposlední řádek - "pojme" namísto "pojem"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/atributy
1. odstavec, 1. řádek - "nějaké další data, které" -> "nějaká další data, která"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/html-entity
1. odstavec, 1. řádek - přepsat větu "HTML entita je zkratka pro znak, který se z různých důvodů těžko v prohlížeči zobrazují."

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/zakladni-struktura-html
HTML - přepsat 2. větu
poslední odstavec, 1. věta - "Když byste" -> "Kdybyste"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/vyvojove-prostredi
2. odstavec - "Jedná se o např. o kompilátor, debugger a další věci.", použít "o" jenom jednou
3. odstavec, 1. věta - "nesprávné" namísto "nesprávně"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/zakladni-tagy-k-formatovani-textu
Přeškrtnutí, 2. věta - "Často se používá pro to, když už něco není platné, ale je možné, že tuto informaci ještě někdo potřebovat." -> "bude potřebovat"
Vodorovná čára, 1. věta - "část." -> "částí."

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da25e73bc9e3c268e19a0d/nadpisy
1. odstavec, 2. věta - "test" -> "text"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/css
3. odstavec - "výhody" -> "výhod"
"Pravidla se skládá ze:" -> "Pravidla se skládají ze:"
poslední odstavec, 2. řádek - "Za každou vlastnosti" -> "vlastností"
poslední odstavec, 2. řádek - "Jako první vlastnosti" -> "vlastnost"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/zapisy-css
External, 2. řádek - "obdobě" -> "obdobně"
v bloku kódu, 2. link - "slozce"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/zakladni-selektory
2. odstavec, 1. řádek - "nepoužívanější" -> "nejpoužívanější"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/komentare-a-jednotky
2. odstavec, 1. řádek - přepsat větu "Absolutní jsou ty, které se velikosti zařízení či na ničem jiném nezáleží."

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/zakladni-vlastnosti
nadpis - "Zarovnáni textu" -> "Zarovnání textu"
Zarovnání textu, 2. věta - "Vlastnost nazývá" -> "Vlastnost se nazývá"
nadpis - "Zloušťka textu" -> "Tloušťka textu"
Dekorace textu, 1. věta - "Jedná se o složenou vlastnosti" -> "vlastnost"
Dekorace textu, poslední bod - "a nebo" -> "anebo"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/kaskada
1. odstavec, na konci - "úrovní" -> "úrovních"

https://ssps.cajthaml.eu/2-wba/lesson/uvod-do-html-a-css/part/64da26333bc9e3c268e19b99/zapis-barev
RGB - chybí rámeček "255, 255, 255"
RGB - "bíla" -> bílá
HEXA - "stejně jakou o rgba." -> "stejně jako u rgba."

### Reprodukce problému

spuštění stránky a přečtení textu

### Stránka

již uvedeno v popisu problémů

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Petr Saksun

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Body udělím.
