### ISSUE TITLE
[NÁPAD] Otevření home page pomocí loga

### ISSUE THREAD

**Issue by Silhavi** [ssps-cajthaml/issues#214]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Například na Youtube, při middle-clicku (nebo pravé tlačítko a otevřít odkaz na nové kartě) Youtube loga se otevře nový tab s Youtube homepage. To samé by mohlo fungovat s logem portálu.

### Zdůvodnění

Když procházím materiály, často potřebuji otevřít v novém tabu home page portálu, abych otevřel jinou directory materiálů a bylo by to takhle efektivnější. Myslím, že je to užitečná funkce a minimálně já ji využívat budu :D.

### Vaše jméno

Petr Saksun

**Comment by cajthamlmatej** [comment]
Děkuji. Přidáno, uvidíte v další verzi. Body udělím.
