### ISSUE TITLE
[WEB] Čas v kalendáři

### ISSUE THREAD

**Issue by MasterJay8** [ssps-cajthaml/issues#215]
### Popis problémů

Čas se zobrazuje o 2 hodiny dříve

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na kalendář
3. Čas odevzdání

### Stránka

cajthaml.eu

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Opera.**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

Chyba, čas je blbě, není čas ztrácet čas

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/113784571/cd4e6222-859f-47df-89af-fd99efc58342)

### Vaše jméno

Jiří Paďour

**Comment by cajthamlmatej** [comment]
Google s tím má obecně problémy, jedná se o problém s časovým pásmem. Google ignoruje přiřazené časové pásmo, zkusil jsem ho přidat ke každé události. Zkontrolujte, jestli funguje v následující verzi. Body udělím.

**Comment by MasterJay8** [comment]
Doslova ne, skill issue
