### ISSUE TITLE
[WEB] Předměty hvězdička

### ISSUE THREAD

**Issue by MasterJay8** [ssps-cajthaml/issues#216]
### Popis problémů

hvezdička na dalším řádku, špatné UI

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na Změnit předmět
3. Chyba UI

### Stránka

cajthaml.eu

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Opera GX**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

ano, OSE Příprava na vysokoškolské studium a informatika má hvězdičku špatně

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/113784571/83f6c3ed-c23a-4fa4-aefa-e38d47032cad)

### Vaše jméno

Jiří Paďour

**Comment by Erag7** [comment]
[me_when_no_mommy_gf.webm](https://github.com/ssps-cajthaml/issues/assets/113784463/1339437e-15cc-43e8-8bb3-3bcb50359d64)

**Comment by cajthamlmatej** [comment]
Děkuji. Opraveno, uvidíte v další verzi. Body udělím.
