### ISSUE TITLE
[WEB] Špatně vyskloňované body

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#217]
### Popis problémů

Je to vyobrazováno jako 3.36 **body**, ale spíše by to mělo být **bodů**.

Pokud je momentální počet bodů 1, tak by to mělo být "bod".
Pokud je 2, 3, nebo 4, tak by to mělo být "body".
Pokud cokoliv jiného, tak "bodů".

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na tlapky pro zobrazení dodatečných souvisejících informací
3. Použít zrakové smysly a vidět, že stránka zní jako vietnamec z večerky přes ulici (/j)
4. Antiprofit

### Stránka

https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: Všechny
Prohlížeč: Doslova všechny
Je prohlížeč aktualizován na nejnovější verzi: Je to vůbec podstatné?

### Chyba

-

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/73956350/01fb594c-5042-4c00-93a6-405de299590e)

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
"K získání další tlapky vám chybí 3.32 body." Zní špatně z vašeho pojetí skloňování - to dle mého funguje jen na celočíselné skloňování, které tam již je.

Když je tam desetinné, dal jsem to, že se to skloňuje jako "1.32 bodů", "0.31 bodu", "4.34 bodů", "12.39 bodů".

Děkuji. Bude viditelné v další verzi. Body přidělím.
