### ISSUE TITLE
Floating point error v celkovém hodnocení

### ISSUE THREAD

**Issue by quertzuiop** [ssps-cajthaml/issues#218]
### Popis problémů

V hodnocení se počet bodů zobrazuje špatně, float issue

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Podívat se do hodnocení
3. Celkové hodnocení nefunguje správně

### Stránka

https://ssps.cajthaml.eu/2-wba/grading/

### Zařízení

Operační systém: Android
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

### Screenshoty

![Screenshot_20231002_085215_Chrome](https://github.com/ssps-cajthaml/issues/assets/115795209/a44ebd2e-ed83-4be1-a051-0338a1ec36f4)

### Vaše jméno

Robert Shea

**Comment by cajthamlmatej** [comment]
Děkuji. Opraveno, uvidíte v další verzi. Body udělím.
