### ISSUE TITLE
[NÁPAD] Zobrazování prací po přihlášení 

### ISSUE THREAD

**Issue by Matej2525** [ssps-cajthaml/issues#219]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Mohlo by dobré hned  po přihlášení, zobrazit veškeré probíhající úkoly. (Ne až po kliknutí na předmět.)

### Zdůvodnění

- Přehlednost 
- Rychlost 
- Zlepšení práce 

### Vaše jméno

Arazim Matěj

**Comment by cajthamlmatej** [comment]
Z popisu mi vůbec nebylo jasné o co jde, protože z toho jak to popisujete, to tam již dávno je. Jen se to nenačítalo bez vybraného předmětu.

Děkuji. Přidáno, uvidíte v další verzi. Body udělím.
