### ISSUE TITLE
[MATERIÁL] Otevření prezentace - pohybování 

### ISSUE THREAD

**Issue by Matej2525** [ssps-cajthaml/issues#220]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Veškeré prezentace 

### Popis problémů

Když se otevře prezentace, nejde se pohybovat šipkami, ale musí se kliknut na obrazovku a poté už se může pohybovat 

### Lokace

Začátek každé prezentace 

### Vaše jméno

Arazim Matěj

**Comment by cajthamlmatej** [comment]
Tohle moderní prohlížeče nepodporují. Prezentace je vložená v iframu.
