### ISSUE TITLE
[WEB] Překlep domácí kvíz 4. týden.

### ISSUE THREAD

**Issue by Lukas-Novotny** [ssps-cajthaml/issues#221]
### Popis problémů

chybí "i" ve slově "vlastnosti"

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf/exams/

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano*

### Chyba

\```...```

### Screenshoty

![Snímek obrazovky 2023-10-04 112451](https://github.com/ssps-cajthaml/issues/assets/92518124/43cfbd6d-9315-4f1f-ac1c-98c71d71c419)

### Vaše jméno

Novotný Lukáš

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji.
