### ISSUE TITLE
[NÁPAD] Scrollování na webu při překliku mezi stránkami.

### ISSUE THREAD

**Issue by Lukas-Novotny** [ssps-cajthaml/issues#222]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Když scrolluji na stránce a pak překliknu na jinou, tak zůstanu na scroll pozici co jsem byl předtím. Očekával bych, že budu "vyscrollovaný" nahoru.

### Zdůvodnění

Předvídatelnost. Lepší feeling ze stránky.

### Vaše jméno

Novotný Lukáš

**Comment by Lunarien** [comment]
Podle mě je to více předvídatelné právě když to scrolluje tam, kde to bylo předtím. Navrhuji udělat nějaký vypínač (toggle) téhle funkcionality.
Předvídatelnost asi záleží na zkušenostech uživatelů z ostatních stránek.

Dodatečný point: Kdyby byla stránka dlouhá, tak nechci znovu scrollovat až dolů. To by bylo otravné.

**Comment by Lukas-Novotny** [comment]
Přijde mi, že když scrolluji na spodek stránky "zkoušení" a pak přejdu na stránku "nástěnka", tak přeci chci být na začátku stránky "nástěnka". Možná jsme se úplně nepochopili.

**Comment by cajthamlmatej** [comment]
Asi záleží kde a kdo co dělá. Dle mého je taktéž vhodné mít scrollování a proto jsem ho přidal. Přizpůsobení tohoto chování zatím neplánuji.

Děkuji. Přidáno, uvidíte v další verzi. Body udělím.
