### ISSUE TITLE
[MATERIÁL] pravopisná chyba v názvu fontu

### ISSUE THREAD

**Issue by PIDRegulator** [ssps-cajthaml/issues#223]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Úvod do HTML a CSS

### Popis problémů

V části Scripta CSS - Základní vlastnosti - odstavec Font textu je v označených fontech napsáno sans-ser**F**if místo sans-serif

### Lokace

V části Scripta CSS - Základní vlastnosti - odstavec Font textu

### Oprava

sans-ser**F**if ---> sans-serif

### Screenshoty

![Screenshot_20231006_110701](https://github.com/ssps-cajthaml/issues/assets/114053414/0d422880-5844-43da-acf1-2b43854f68be)

### Vaše jméno

Jáchym Kubata

**Comment by cajthamlmatej** [comment]
Nejedná se o pravopisnou chybu, ale o překlep. 

Opravil jsem. Body udělím.
