### ISSUE TITLE
[WEB] Přetékání textu v pracích

### ISSUE THREAD

**Issue by marekvks** [ssps-cajthaml/issues#224]
### Popis problémů

Přetékání textu v pracích - konkrétně DVOP3 WBB, práce "kurzy"

### Reprodukce problému

Postup k reprodukci:
1. Být na mobilním zařízení
2. Jít na https://ssps.cajthaml.eu/3-dvop-wbb/work/kurzy
3. Scrollnout doprava

### Stránka

https://ssps.cajthaml.eu/3-dvop-wbb/work/kurzy

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![pretekani-textu](https://github.com/ssps-cajthaml/issues/assets/84468808/796c2a8f-f273-46b8-8f08-9bfee9d329ec)

### Vaše jméno

Marek Vykysalý

**Comment by cajthamlmatej** [comment]
Problém není jen zde, ale všude.

Děkuji. Opraveno, uvidíte v další verzi. Body udělím.
