### ISSUE TITLE
[WEB] Špatné koncovky u odevzdání

### ISSUE THREAD

**Issue by jaywor1** [ssps-cajthaml/issues#225]
### Popis problémů

Při uploadu se koncovka změní na `.bin`, ale nejedná se o žádnou kompresi.

Example `soubor.*` --> `soubor.bin`

### Reprodukce problému

Postup k reprodukci:
1. Odevzdat zadání například `Program.cs`
2. Stáhnout zadání (dostal jsem `.bin` a ne `.cs`, přitom se nejedná o žádnou kompresi, ale jen změnu koncovky)

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit/work/grafy-4-cesta-pomoci-dfs

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Vaše jméno

Michal Javor

**Comment by cajthamlmatej** [comment]
Myslím si, že konečně opraveno.
