### ISSUE TITLE
[NÁPAD] Kvízy

### ISSUE THREAD

**Issue by MasterJay8** [ssps-cajthaml/issues#227]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Stránkování na kvízy, ať to je přehledné 
![image](https://github.com/ssps-cajthaml/issues/assets/113784571/2dce3a3f-9fa9-44d5-8925-fb78f7062b78)

### Zdůvodnění

Když děláme 2 kvízy týdně, tak se stránka přeplní, a musí se scrollovat 1km dolů

### Vaše jméno

Jiří Paďour

**Comment by cajthamlmatej** [comment]
Děkuji. Přidáno.
