### ISSUE TITLE
[MATERIÁL] Překlep

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#228]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

skripta Verzovací systémy - Větve

### Popis problémů

Ve skriptech Verzovací systémy - Větve - sekce Vytvoření větve je v posledním řádku napsáno comimit místo commit

### Lokace

sekce Vytvoření větve

### Oprava

comimit --> commit

### Screenshoty

![Snímek obrazovky 2023-10-07 213605](https://github.com/ssps-cajthaml/issues/assets/91782441/38e3b646-6fd7-4c33-a0a4-ac1dd98b5412)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Opraveno.
