### ISSUE TITLE
[MATERIÁL] PŘEKLEP!!!!

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#23]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

https://api-ssps.cajthaml.eu/file/2021-2022/2-wba/presentations/14.html

### Popis problémů

Překlep
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/35110087/141080185-cf85a6bd-d34f-49f4-b0d2-08da789de7a9.png">

### Lokace

https://api-ssps.cajthaml.eu/file/2021-2022/2-wba/presentations/14.html

### Oprava

**Resetuje**

### Screenshoty

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/35110087/141080185-cf85a6bd-d34f-49f4-b0d2-08da789de7a9.png">

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Těch obrázku tam nemusí být tolik... :) Taktéž příště lepší název, ať se nám to tu neztratí (a Vám se kvůli tomu nesnižují body).
