### ISSUE TITLE
[WEB] Nasazen předmět, který není v inventáři 

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#233]
### Popis problémů

Po konvertování předmětu, který máte aktuálně nasazený, se předmět nesundá. V praxi to znamená, že můžete mít nasazeny itemy, které nevlastníte.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "tlapky/profil"
3. konvertovat itemy
4. podívat se na nasazené itemy a itemy v inventáři 
5. Actual profit (but illegal?)

### Stránka

kdekoliv kde je vidět profil 
respektive https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Opera GX.**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/06949cde-a3fa-4144-925f-f11b6c18809a)

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Děkuji. Opravil jsem, bude vidět po nahrání.
