### ISSUE TITLE
[MATERIÁL] Překlep 

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#234]
### Jméno předmětu pro který byl materiál vytvořen

OSE Příprava na VŠ, 4. ročník

### Materiál

Univerzity a vysoké školy, 2. - 6. hodina, prezentace Vysoké školy

### Popis problémů

Překlep ve slově akademický, v prezentaci je "akademická senát".
Dále ve slově akademičtí, v prezentaci je "akademický pracovníci"

### Lokace

Slide 18 a 19.
Slide 24.

### Oprava

"akademická senát" --> "akademický senát"
"akademický pracovníci" --> "akademičtí pracovníci"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114414946/86888fe7-b641-40db-8761-c681c9a3bb84)
![image](https://github.com/ssps-cajthaml/issues/assets/114414946/c8b78611-fea0-4965-8b1a-748c60ba06a2)
![image](https://github.com/ssps-cajthaml/issues/assets/114414946/3dbecc07-4819-41e7-b423-fe9d7ef7dc2b)

### Vaše jméno

Kiripolský Pavel

**Comment by cajthamlmatej** [comment]
Děkuji. Opraveno. Bude vidět po nahrání.
