### ISSUE TITLE
[WEB] Diskriminace mého systému

### ISSUE THREAD

**Issue by jaywor1** [ssps-cajthaml/issues#235]
### Popis problémů

Na slidu 70 v prezentaci Grafová teorie se neukazuje obrázek grafu

### Reprodukce problému

1. https://archive.ssps.cajthaml.eu/2023-2024/4-dvop-pit/03_graph.html#/9/17
2. Jít na slide 70

### Stránka

https://archive.ssps.cajthaml.eu/2023-2024/4-dvop-pit/03_graph.html#/9/17

### Zařízení

Operační systém: **Arch Linux**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Vaše jméno

Michal Javor

**Comment by cajthamlmatej** [comment]
To může být úplně čímkoliv, moc to nesouvisí s weby. Tohle se děje i na nějakých PC, kde je divný monitor. Jste zatím jediný, tak uzavírám.
