### ISSUE TITLE
[WEB] Překlep

### ISSUE THREAD

**Issue by KickLock** [ssps-cajthaml/issues#236]
### Popis problémů

Překlep na stránce Informace a upozornění u skupiny PVA v okně využití umělé inteligence. Ve druhém odstavci je = místo é.

### Reprodukce problému

Postup k reprodukci:
1. otevřít tab informace a upozorněni
2. Kliknout na "Využití umělé inteligence"
3. je vidět překlep

### Stránka

https://ssps.cajthaml.eu/2-pva/announcements/vyuziti-umele-inteligence-64f6236a1f7d9ac487d14c79

### Zařízení

Operační systém: **MacOs**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Kryštof Khek

**Comment by cajthamlmatej** [comment]
Opraveno.
