### ISSUE TITLE
[MATERIÁL] Překlep

### ISSUE THREAD

**Issue by Lukas-Novotny** [ssps-cajthaml/issues#238]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 4. ročník

### Materiál

Lekce Projekty > prezentace Projekty

### Popis problémů

překlep ve slově testů

### Lokace

3. slide od konce

### Oprava

přepsat

### Screenshoty

![Snímek obrazovky 2023-10-24 151330](https://github.com/ssps-cajthaml/issues/assets/92518124/0916ffba-9e68-4acf-92a4-874bc6fdf091)

### Vaše jméno

Novotný Lukáš

**Comment by cajthamlmatej** [comment]
Děkuji. Opraveno. Bude vidět po nahrání.
