### ISSUE TITLE
[NÁPAD] Úprava materiálu

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#239]
### V jaké aplikaci se nachází nápad?

Prezentace

### Popis nápadu

V prezentaci na DVOP4 PIT, Grafová teorie, 3. - 20. hodina, bych na stránce 94 upravil text, aby byl pochopitelnější.
Momentálně je napsáno:
strom má všechny úrovně plné, kromě poslední
poslední úroveň je plná zleva doprava

A rád bych to nějak vylepšil například:
strom má všechny úrovně plné, až na poslední, která být nemusí
poslední úroveň se plní zleva doprava

### Zdůvodnění

Na hodině se řešilo jak to na první pohled není pochopitelné a přišlo mi to matoucí.
I když jde jenom o změnu pár slov, myslím že je to více srozumitelné.

### Vaše jméno

Kiripolský Pavel

**Comment by cajthamlmatej** [comment]
Děkuji. Opraveno. Bude vidět po nahrání.
