### ISSUE TITLE
[WEB] halloweenský speciál

### ISSUE THREAD

**Issue by PIDRegulator** [ssps-cajthaml/issues#240]
### Popis problémů

překlep v sekci žebříček hráčů v čase kdy se žebříček restuje

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "halloweenský speciál"
3. žebříček hráčů

### Stránka

https://ssps.cajthaml.eu/season/halloween-2023

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![Screenshot_20231029_201542](https://github.com/ssps-cajthaml/issues/assets/114053414/d9ab27be-511e-4981-b614-8da025e4795b)

### Vaše jméno

Jáchym Kubata

**Comment by cajthamlmatej** [comment]
To jsem asi opravil před vámi, ale započítám vám to.
