### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by TimmothyNguyen** [ssps-cajthaml/issues#241]
### Popis problémů

V zadání pro 2.A sk2 jde o minimálně jednu gramatickou chybu. Jedná se o koncovku 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "práce" a dále "seznam studentů"
3. část "Design" v podsekci "nabídka" v druhé odrážky
4. původní podoba věty je "uživatel se vypíší čtyři možnosti, které může provést:"
5. upravit větu na "uživateli se vypíší čtyři možnosti, které může provést:"

### Stránka

https://ssps.cajthaml.eu/2-pva/work/seznam-studentu

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![Screenshot 2023-10-29 at 10 48 00 PM](https://github.com/ssps-cajthaml/issues/assets/135013855/0b93d0de-2bd9-4b52-bf7e-5bd9b46bfa43)

### Vaše jméno

Nguyen Thái Son Timmothy

**Comment by cajthamlmatej** [comment]
Opraveno.
