### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by TimmothyNguyen** [ssps-cajthaml/issues#242]
### Popis problémů

V sekci "informace a upozornění" ve složce "využití umělé inteligence" se nachází překlep ve 2. odstavci 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "informace a upozornění" > "využití umělé inteligence" 
3. 2. odstavec na konci
4. Profit

### Stránka

https://ssps.cajthaml.eu/2-pva/announcements/vyuziti-umele-inteligence-64f6236a1f7d9ac487d14c79

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

původní podoba "samotný chat z uměl= inteligence"
správná podoba "samotný chat z umělé inteligence"

### Screenshoty

<img width="578" alt="Screenshot 2023-11-01 at 6 31 48 PM" src="https://github.com/ssps-cajthaml/issues/assets/135013855/d3c04770-63ac-4245-a678-1b15701e1f09">

### Vaše jméno

Timmothy Nguyen

**Comment by cajthamlmatej** [comment]
Opraveno.

**Comment by cajthamlmatej** [comment]
Duplikát #236, body vám nebudou přidány za tento issue.
