### ISSUE TITLE
[WEB] "Helloween" - překlep ve slově halloween

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#243]
### Popis problémů

Na webu je překlep na tooltipu u halloweenského tlačítka,

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Ukázat na tlačítko pro otevření halloweenské minihry
3. viz tooltip
4. Profit

### Stránka

jakákoliv ssps.cajthaml.eu kromě ssps.cajthaml.eu/user/* . Na user části stránky se to nezobrazuje.

### Zařízení

Operační systém: **Windows, linux, macos, co víc si můžeš přát?**
Prohlížeč: **Všechny**
Je prohlížeč aktualizován na nejnovější verzi: **nerelevantní**

### Chyba

ne

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/73956350/4fdb59fe-bd2f-4070-b1ee-2f875198db2b)

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
Opraveno. Bude vidět v další verzi.
