### ISSUE TITLE
Momospace font v Programovacím hřišťátku [NÁPAD] 

### ISSUE THREAD

**Issue by TERROR-404** [ssps-cajthaml/issues#245]
### V jaké aplikaci se nachází nápad?

Služby (hosting, databáze, spouštěč kódu, ...)

### Popis nápadu

Ve vstupu a výstupu by byl monospace font.

### Zdůvodnění

![image](https://github.com/ssps-cajthaml/issues/assets/69761253/cfa26563-ee9a-4ad8-9a8b-7a9a504785e9)
Protože při výpisu map není jednoduše bez počítání po jednom znaku zřejmé, jestli je mapa správně velká a je matoucí, když je některá řádka kratší, jen kvůli tomu, že tam jsou 1.

### Vaše jméno

Bohumil Čmerda

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Bude viditelné v další verzi. Body udělím.
