### ISSUE TITLE
[MATERIÁL] název algoritmu

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#246]
### Jméno předmětu pro který byl materiál vytvořen

OSE Informatické semináře, 4. ročník

### Materiál

Prezentace Grafová teorie 3. - 20. hodina

### Popis problémů

Špatné písmeno v nadpisu FELLMANŮV-FORDŮV ALGORITMUS

### Lokace

Slide 132

### Oprava

BELLMANŮV-FORDŮV ALGORITMUS

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114414946/b8594cd1-be0e-412f-bb3c-e18e367cb2c3)

### Vaše jméno

Pavel Kiripolský

**Comment by cajthamlmatej** [comment]
Velmi vám děkuji, bohužel již nemám jak odměnit :(
