### ISSUE TITLE
[MATERIÁL] název funkce

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#247]
### Jméno předmětu pro který byl materiál vytvořen

OSE Informatické semináře, 4. ročník

### Materiál

Prezentace Hašovací algoritmy a vyhledávání 21. - 24. hodina

### Popis problémů

Špatné písmeno v nadpisu LINEÁRNÍ KONGURENCE

### Lokace

Slide 11

### Oprava

LINEÁRNÍ KONGRUENCE

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114414946/c98dd985-6bdf-4bbd-846f-24d8defc8d27)

### Vaše jméno

Pavel Kiripolský

**Comment by cajthamlmatej** [comment]
Velmi vám děkuji, bohužel již nemám jak odměnit :(
