### ISSUE TITLE
[MATERIÁL] pravopisná chyba

### ISSUE THREAD

**Issue by Kiripolsky** [ssps-cajthaml/issues#248]
### Jméno předmětu pro který byl materiál vytvořen

OSE Informatické semináře, 4. ročník

### Materiál

Prezentace Hašovací algoritmy a vyhledávání 21. - 24. hodina

### Popis problémů

Písmeno navíc ve slově _polyonomiální_

### Lokace

Slide 14

### Oprava

polynomiální

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114414946/9254eb8a-f31d-4d25-aaaa-35c780af8144)

### Vaše jméno

Pavel Kiripolský a Viktor Číhal

**Comment by cajthamlmatej** [comment]
Velmi vám děkuji, bohužel již nemám jak odměnit :(
