### ISSUE TITLE
[WEB] Chyba v sekci "CHYBY A NÁVRHY"

### ISSUE THREAD

**Issue by krystofbruth** [ssps-cajthaml/issues#249]
### Popis problémů

Na hlavním panelu v sekci "CHYBY A NÁVRHY" ve druhé větě je čtvrté slovo od začátku věty napsané pravopisně špatně. Jedná se o slovo "pravipisně", které má správně být (dle [Internetové jazykové příručky Ústavu pro jazyk český](https://prirucka.ujc.cas.cz/?slovo=pravopisn%C4%9B)) napsáno "pravopisně".

### Reprodukce problému

Postup k reprodukci:
1. Přejít na stránku [https://ssps.cajthaml.eu/](https://ssps.cajthaml.eu/).
2. Kliknout na "Panel".
3. Zvolit v levé části obrazovky záložku "CHYBY A NÁVRHY".
4. Chyba je patrná.

### Stránka

https://ssps.cajthaml.eu/

### Zařízení

Operační systém: **MacOS**
Prohlížeč: **Brave browser (Chromium based)**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

<img width="1015" alt="Snímek obrazovky 2023-12-07 v 11 50 39" src="https://github.com/ssps-cajthaml/issues/assets/61594751/c8893bc0-d0fc-43f2-97e8-04284dac8b80">

### Vaše jméno

Kryštof Bruthans

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Bude viditelné v další verzi. Body udělím.
