### ISSUE TITLE
[MATERIÁL] Nepřesné informace ve skriptách WBA

### ISSUE THREAD

**Issue by krystofbruth** [ssps-cajthaml/issues#250]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Úvod do webových stránek (2. - 4. hodina)

### Popis problémů

Je napsáno, že se v roce 1992 připojila "Česká vysoká univerzita technická (ČVUT)".

### Lokace

Ve skriptách pod záložkou "Historie internetu".

### Oprava

Opravit na **"České vysoké učení technické v Praze (ČVUT)"**.

### Screenshoty

<img width="1015" alt="Snímek obrazovky 2023-12-07 v 13 19 24" src="https://github.com/ssps-cajthaml/issues/assets/61594751/a182fce2-c56b-4f0e-9367-82e905ea2b43">

### Vaše jméno

Kryštof Bruthans

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód pro tlapky: ISSUES2024-B
