### ISSUE TITLE
[WEB] Nesprávné datum u winter event QnA

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#251]
### Popis problémů

Hra, která začala v prosinci nemůže skončit v listopadu, that's all.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na winter event logo a poté na "Do kdy je možné získávat odměny?"
4. Akce už skončila?! :(

### Stránka

https://ssps.cajthaml.eu/season/winter-2023

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Opera GX**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/57490ea2-4ddb-48b0-b22e-078ab53bd7f6)

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Děkuji, snad to bude vidět (:). Body připíšu.
