### ISSUE TITLE
Chyba/překlep v skiptách[WEB] 

### ISSUE THREAD

**Issue by Lukas-Novotny** [ssps-cajthaml/issues#252]
### Popis problémů

Chyba/překlep v skiptách, věta nedává smysl, pravděpodobně mělo být napsáno "nejčastěji bývá s pozicí spojováno například" místo "nejčastěji bývá s pozici spojováno na"

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf/lesson/search-engine-optimizations/part/64e25f4aef51274005fe5726/urcovani-pozice-pri-vyhledavani

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Arc**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

<img width="685" alt="Snímek obrazovky 2024-01-09 v 15 14 14" src="https://github.com/ssps-cajthaml/issues/assets/92518124/87e0394a-f420-46fc-913f-11c6fc56986c">

### Vaše jméno

Lukáš Novotný

**Comment by cajthamlmatej** [comment]
Velmi vám děkuji, bohužel již nemám jak odměnit :(
