### ISSUE TITLE
Překlep v SEO prezentaci [MATERIÁL] 

### ISSUE THREAD

**Issue by MasterJay8** [ssps-cajthaml/issues#253]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 4. ročník

### Materiál

SEO Prezentace

### Popis problémů

Překlep v textu
n -> ň

### Lokace

20/90

### Oprava

Může pozici ovlivňovat rychlost načtení stránky?

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/113784571/2eb94463-b2a1-4ee9-8dac-ed80aef52ba5)

### Vaše jméno

Jiří Paďour

**Comment by cajthamlmatej** [comment]
Opraveno.
