### ISSUE TITLE
Chnybné označení procent[WEB] 

### ISSUE THREAD

**Issue by ThatLazyGuyTech** [ssps-cajthaml/issues#254]
### Popis problémů

v tabulce převodů procentuální úspěšnosti na známku se píše: "více jak 80 %<85; +∞)"

### Reprodukce problému

1. Jít na stránku https://ssps.cajthaml.eu/2-pva/announcements/kriteria-hodnoceni-64db58223bc9e3c268e32d88
2. kliknout informace a upozornění
3. kritéria hodnocení
4. scrollovat úplně dolů

### Stránka

https://ssps.cajthaml.eu/2-pva/announcements/kriteria-hodnoceni-64db58223bc9e3c268e32d88

### Zařízení

Operační systém: Windows
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Vaše jméno

Teodor Manić

**Comment by cajthamlmatej** [comment]
Děkuji, v novém roce jsem celé kritéria přepisoval, takže tohle již není potřeba řešit.
