### ISSUE TITLE
[MATERIÁL] Překlep v prezentaci

### ISSUE THREAD

**Issue by 3rikWeg** [ssps-cajthaml/issues#255]
### Jméno předmětu pro který byl materiál vytvořen

OSE Příprava na VŠ, 4. ročník

### Materiál

Prezentace - Práce s informacemi

### Popis problémů

Překlep ve slově zdroje, je tam "zdorjů" místo "zdrojů"

### Lokace

Prezentace - Práce s informacemi - slide 3

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/103307244/d31df638-726e-4812-8607-f31b2846ef10)

### Vaše jméno

Erik Weglarz

**Comment by cajthamlmatej** [comment]
Děkuji! :)
