### ISSUE TITLE
[MATERIÁL] Chybí odkaz na dokumentaci pro fs

### ISSUE THREAD

**Issue by CodeInwader** [ssps-cajthaml/issues#256]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Webové servery - Soubory a JSON v JS

### Popis problémů

Chybí zde odkaz na dokumentaci fs. V materiálech je napsáno : Balíček má dobrou dokumentaci, která je k dispozici zde. Na textu zde odkaz chybí.

### Lokace

24. - 34. hodina v materiálech Webové servery.

### Oprava

Přidat odkaz.

### Screenshoty

<img width="1439" alt="Screenshot 2024-01-22 at 19 23 32" src="https://github.com/ssps-cajthaml/issues/assets/97461517/4a3ab53a-b537-47ad-8a72-52369b3113f0">

### Vaše jméno

Kryštof Ježdík (3.B)

**Comment by cajthamlmatej** [comment]
Děkuji, JS lekce již v DVOPu není, tedy už není co opravovat.
