### ISSUE TITLE
[MATERIÁL] Překlep v skriptách o responzivitě 

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#257]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Responzivita (skripta)

### Popis problémů

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/d9db0343-e485-4879-8d9f-aa5852693883)

### Lokace

Skripta(Responzivita) sekce responzivita, 4 řádek

### Oprava

překlep by měl být opraven z "mi" na "my"

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Fujky. Opraveno, děkuji. Kód pro tlapky: ISSUES2024-A
