### ISSUE TITLE
Chybějící písmenko - (ZP) 1. kontrolní bod

### ISSUE THREAD

**Issue by Neptuuno** [ssps-cajthaml/issues#258]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Zadání - (ZP) 1. kontrolní bod

### Popis problémů

Chybějící písmenko 'm' ve slově kontrolní(m).

### Lokace

Zadání - (ZP) 1. kontrolní bod - 3 slovo vě větě u první odrážky.

### Screenshoty

![opravapismenko](https://github.com/ssps-cajthaml/issues/assets/101596263/1f0ef3c1-760c-4ae8-a72c-b1f82ea48a67)

### Vaše jméno

Adam Peer

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno pro další roky.
