### ISSUE TITLE
[MATERIÁL] Chybná interpunkce v prezentaci o frameworcích

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#259]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Frameworky

### Popis problémů

překlep (chybná interpunkce) ve slově **používá** ve větě "Na co se tedy Bootstrap používá?"
Ve slově "používá" chybí čárka nad písmenem i

### Lokace

stránka 9/32

### Oprava

slovo "použivá" by mělo být změněno na slovo "používá"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/f6cb8133-c680-4b6a-9011-026304c95838)

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Tlapky viz minulý issue
