### ISSUE TITLE
[WEB]Chybné formátování textu u úkolu

### ISSUE THREAD

**Issue by vojtahajek** [ssps-cajthaml/issues#26]
### Popis problémů

Chybné formátování textu u úkolu OOP Discord (různé barvy textu)

### Reprodukce programu

Rozdílné barvy textu

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/work/30-oop-discord

### Zařízení

Operační systém: macOS
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

### Screenshoty

![Snímek obrazovky 2021-11-19 v 15 07 23](https://user-images.githubusercontent.com/91019978/142636588-9809b75f-30eb-4ead-bebc-e16c51564c67.png)

### Vaše jméno

Vojtěch Hájek

**Comment by cajthamlmatej** [comment]
Opraveno ve verzi v3.0.4
