### ISSUE TITLE
[MATERIÁL] 

### ISSUE THREAD

**Issue by capekpetr** [ssps-cajthaml/issues#260]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Prezentace o formulářích

### Popis problémů

překlep na 43. slajdu v prezentaci. Chyba ve slově umisťují - chybí zde háček nad t. 

### Lokace

43. slajd v prezentaci FORMULÁŘE

### Oprava

přepsat slovo umistují na slovo umisťují

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/96550589/809d12b5-6fa8-4391-8af3-30384da10275)

### Vaše jméno

Petr Čapek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód pro tlapky: ISSUES2024-A
