### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by fanda857** [ssps-cajthaml/issues#261]
### Popis problémů

pokud z materiálů jdu zpět (né pomocí tlačítka ale pomocí browseru zpět) tak se dostanu zpět ale chybí materiály

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Přejít na [Informace o projektech](https://ssps.cajthaml.eu/3-stp/lesson/informace-o-projektech/)
3. Kliknout na jakoukoliv položku
4. v browseru kliknout na tlačítko zpět

### Stránka

https://ssps.cajthaml.eu/3-stp/lesson/informace-o-projektech/

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/65150803/6e50dac1-493c-4344-a1e8-0ea616de8ccd)

### Vaše jméno

František Václavek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno v další verzi. Kód pro tlapky: ISSUES2024-A
