### ISSUE TITLE
[MATERIÁL] Překlep v prezentaci o Formulářích (Pozicování)

### ISSUE THREAD

**Issue by Janda2304** [ssps-cajthaml/issues#263]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Formuláře (Prezentace)

### Popis problémů

Překlep ve slově umištovat (mělo by být "umisťovat)

### Lokace

42

### Oprava

opravit slovo "umištovat" na "umisťovat"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114053327/3470ceb8-4222-43d8-ae5f-ae101f6104bb)

### Vaše jméno

Ondřej Janoušek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód pro tlapky: ISSUES2024-B
