### ISSUE TITLE
[MATERIÁL] Kritéria hodnocení

### ISSUE THREAD

**Issue by Silhavi** [ssps-cajthaml/issues#264]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Informace a upozornění  - Kritéria hodnocení

### Popis problémů

špatně zapsaná hodnota

### Lokace

https://ssps.cajthaml.eu/2-wba/announcements/kriteria-hodnoceni-64d9ec4579dad891e8a06bb4
úplně dole

### Oprava

85% a více

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/114069417/b7263ae6-f453-4678-8236-f36a9325baee)

### Vaše jméno

Petr Saksun, 2.C

**Comment by cajthamlmatej** [comment]
Děkuji, v novém roce jsem celé kritéria přepisoval, takže tohle již není potřeba řešit.
