### ISSUE TITLE
[WEB] Velikonoční event - hrubka

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#265]
### Popis problémů

![image](https://github.com/ssps-cajthaml/issues/assets/73956350/8e7b44c4-e2e2-45ca-b904-4ccb1f9e055b)
Uprostřed obrazovky nahoře je napsáno "Všechn**y** vejce", ale má tam být "Všechn**a**".

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Být v době velikonočního eventu
3. Kliknout na Tlačítko velikonočního eventu
4. Ohodnotit všechna vajíčka co jdou
5. Vidět text "Všechny vajíčka" a pomyslet si, že tak to snad být nemá

### Stránka

https://ssps.cajthaml.eu/season/easter-2024/ranking

### Zařízení

Operační systém: **Pravděpodobně všechny**
Prohlížeč: **Pravděpodobně všechny**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

Obrázek je již výše z kontextuálních důvodů.

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno.
