### ISSUE TITLE
[WEB] Seznam prací není responzivní 

### ISSUE THREAD

**Issue by krystofbruth** [ssps-cajthaml/issues#267]
### Popis problémů

Stránka "práce" ať už v přihlášeném či nepřihlášeném stavu není na menších zařízeních responzivní, kvůli textu o stavu odevzdání a termínu odevzdání, které se špatně přizpůsobují.

### Reprodukce problému

Postup k reprodukci:
1. Snížit rozlišení obrazovky (dev tools nebo zobrazení na mobilním zařízení).
2. Přejít na hlavní stránku.
3. Kliknout na záložku práce.
4. Profit.

### Stránka

ssps.cajthaml.eu - záložka "Práce".

https://ssps.cajthaml.eu/2-wba/works/

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

![IMG_8945](https://github.com/ssps-cajthaml/issues/assets/61594751/704ccf31-9009-4fd2-8d55-7b84e4e2ce66)

### Vaše jméno

Kryštof Bruthans 2.C

**Comment by cajthamlmatej** [comment]
Děkuji, celou tuto stránku jsem předělal a je nyní více responzivní. Kód pro tlapky: ISSUES2024-A
