### ISSUE TITLE
[WEB] Nefunkční předvídač bodů

### ISSUE THREAD

**Issue by michalwinter** [ssps-cajthaml/issues#27]
### Popis problémů

Při zapnutí předvídače se počet aktuálních bodů přesune do desetinných míst a počet maximálních bodů a získaných bodů z předvídače se přesune do celého čísla výsledku.

### Reprodukce programu

Postup k reprodukci:
1. Kliknout na předvídač  a zadat počty bodů
2. Stonks jaxviň

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/profile

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://user-images.githubusercontent.com/54064888/143778341-a4cd99d2-a137-435b-b259-a2717dbaebb5.png)
![image](https://user-images.githubusercontent.com/54064888/143778364-6cd86906-871a-4cfc-96d4-8284ca7acdea.png)

### Vaše jméno

Michal Winter

**Comment by cajthamlmatej** [comment]
Opraveno ve verzi v3.0.4
