### ISSUE TITLE
[MATERIÁL] Špatné i/y

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#270]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Opakování - HTML

### Popis problémů

Špatné i/y ve slově vznikly
"Od té doby vznikli různé verze"

### Lokace

Skripta Opakování - HTML

### Oprava

"Od té doby vznikli různé verze" -> "Od té doby vznikly různé verze"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91782441/b25aca57-0192-4998-abba-ca18d0055cc9)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Tlapky viz minula issue.
