### ISSUE TITLE
[MATERIÁL] Špatné i/y - git

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#271]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Verzovací systémy - Větve

### Popis problémů

Špatné i/y ve slově proběhly:
"Když ve větvích proběhli velké změny"

### Lokace

Skripta Verzovací systémy - Větve nadpis Slučování větví

### Oprava

"Když ve větvích proběhli velké změny" -> "Když ve větvích proběhly velké změny"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91782441/fedddd61-e5c4-4448-8d58-06636eea984d)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Děkuji, tlapky stále v minulém issue.
