### ISSUE TITLE
[MATERIÁL] Špatné i/y - Databáze

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#272]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Databáze - Databáze

### Popis problémů

Špatné i/y ve slově měly:
"Naše data by měla taktéž chránit a měli by být dostupné." 

### Lokace

Skripta Databáze - Databáze

### Oprava

"Naše data by měla taktéž chránit a měli by být dostupné." -> "Naše data by měla taktéž chránit a měly by být dostupné."

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91782441/4249bef8-72cb-4d41-af2b-8e11f62b9ac9)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód pro tlapky: ISSUES2024-C
