### ISSUE TITLE
[MATERIÁL] Překlep

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#273]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

Databáze - Pojmy SQL databází

### Popis problémů

Vynechané písmena:
"Tabulka je soubor podobný dat"

### Lokace

Skripta Databáze - Pojmy SQL databází

### Oprava

"Tabulka je soubor podobný dat" -> "Tabulka je soubor podobných dat"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91782441/26ffeed2-19dc-4155-8a6d-9128217efc17)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Tlapky viz minulá issue.
