### ISSUE TITLE
[WEB] Špatné číslo v procentuální úspěnosti

### ISSUE THREAD

**Issue by PIDRegulator** [ssps-cajthaml/issues#274]
### Popis problémů

V tabulce převodu procentuální úspěšnosti na známku je napsáno více jak 80%, ale zbytek čísel naznačuje, že by mělo být 85%

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na Informace a upozornění
3. Kliknout na kritéria hodnocení 
5. Scrollovat až dolu

### Stránka

https://ssps.cajthaml.eu/2-wba/announcements/kriteria-hodnoceni-64d9ec4579dad891e8a06bb4

### Zařízení

Operační systém: Linux
Prohlížeč: Brave
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

### Screenshoty

![issue](https://github.com/ssps-cajthaml/issues/assets/114053414/74b7bb2b-2834-4130-a022-14806b00860b)

### Vaše jméno

Jáchym Kubata

**Comment by cajthamlmatej** [comment]
Děkuji, v novém roce jsem celé kritéria přepisoval, takže tohle již není potřeba řešit.
