### ISSUE TITLE
[WEB] Nechtěná změna barevného režimu

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#275]
### Popis problémů

Uživatel, který má nastaven tmavý režim a přejde na stránku Pride a zpět tak se mu nastaví bílý režim.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se na portál
2. Na hoře v liště stisknout tmavý režim (stránka se přepne do tmavého režimu)
3. Přejít na podstránku Pride
4. Stisknout tlačítko zpět
5. Portál se zobrazí bílém režimu

### Stránka

https://ssps.cajthaml.eu/season/pride

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Vaše jméno

Vojtěch Šulc

**Comment by cajthamlmatej** [comment]
Jedná se o chtěnou featuru (resp. wont-fix), je to kvůli konzistenci designu uvnitř pridu nehledě na theme.
