### ISSUE TITLE
[NÁPAD] Presety na portál

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#277]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Přidání kustomizačních presetů na portál.

### Zdůvodnění

Myslím, že by tato funkčnost byla vhodná proto, že by se dalo vytvořit více presetů, mezi kterými by se dalo jednoduše přepínat. Student by si tak mohl udělat preset třeba na vánoce, halloween a nějaký normální.

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
V další verzi snad přibude. Kód pro tlapky: ISSUES2024-D
