### ISSUE TITLE
[MATERIÁL] MVOP3 CSS preprocesory - překlep

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#278]
### Jméno předmětu pro který byl materiál vytvořen

MVOP Webový frontend, 3. ročník

### Materiál

CSS preprocesory - Node.js a npm

### Popis problémů

Drobný překlep:
"výpis budete ten, který zapíšeme pomocí console.log"

### Lokace

CSS preprocesory skripta - Node.js a npm

### Oprava

"výpis budete ten, který zapíšeme pomocí console.log" -> "výpis bude ten, který zapíšeme pomocí console.log"

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/91782441/ce6559eb-5e5e-40a8-bd2e-9ed20ebb9fb4)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Nemůžu opravit, protože daná stránka již neexistuje (a ani Node.js skripta). Kód na tlapky: ISSUES2024-A
