### ISSUE TITLE
[MATERIÁL] Responzivita překlep - "metetag"

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#279]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Responzivita

### Popis problémů

Pravopisná chyba

### Lokace

Skripta - responzivita, sekce 2. (Návrh responzivity), pod obrázky, které ukazují přizpůsobování stránky ruzným zařízením.

### Oprava

"metetag" změnit na:
"tag <meta>"
nebo
"<meta> tag"
popřípadě
tag (<meta>)

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/73956350/30284d00-e7ed-4e57-b2a2-880f104fa15c)

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
Metatag je speciální typ tagu, který je tagem meta. Říkáme mu takto na více místech. Nepřijde mi to jako problém.

**Comment by Lunarien** [comment]
Jako sice uznávám, že jsem to mohl lépe napsat, ale nějakým způsobem jste minul tu pravopisnou chybu.
podívejte se na **4. písmeno**.
![image](https://github.com/user-attachments/assets/f13aedb8-cd89-45f9-bd62-cab9faf10385)

**Comment by Lunarien** [comment]
![cachtl](https://github.com/user-attachments/assets/2e20c417-897f-47bf-bb62-2685c6d196fd)
