### ISSUE TITLE
[WEB] Mizící obsah na telefonu 

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#28]
### Popis problémů

V aplikaci (na androidu), pokud jsem na té úvodní stránce a dám zpět, tak zmizí veškerý obsah. Po znovu načtení je vše v pořádku, takže se nejedná o nic důležitého. Video jsem posílal na discordu.
Verze stránek je: v3.0.3b3

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se. (já byl přihlášen, ale nevím jestli k chybě dojde i když přihlášen nebudu) 
2. Zavřít menu
3. Kliknout na tlačítko zpět, dole v navigaci mobilu 
4. Obsah zmizí

### Stránka

https://ssps.cajthaml.eu/ 

### Zařízení

Operační systém: **Android**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano (verze: 1.32. 112)**

### Chyba

\```...```

### Screenshoty

https://user-images.githubusercontent.com/82168954/144426031-44bf4cc3-0027-4de4-8a79-d9bc88250c7d.mp4

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Opraveno, už by se nemělo stávat.
