### ISSUE TITLE
[MATERIÁL] Nesprávný pravopis - Responzivita

### ISSUE THREAD

**Issue by Lunarien** [ssps-cajthaml/issues#280]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Skripta - Responzivita

### Popis problémů

V sekci "Návrh responzivity" se nachází souvětí, které by šlo pravopisně zapsat lépe.

### Lokace

Lekce > Responzivita > Skripta > Návrh responzivity

### Oprava

Původní text:
Jak jsme si již řekli, často se používá kontejnarizace stránky pro responzivitu, často to tak ale není, a používáme celostránkové stránky a nebo zcela kontejnery ignorujeme.

Lepší text:
Jak jsme si již řekli, často se používá kontejnerizace stránky pro responzivitu. Často to tak ale není a používáme celostránkové stránky, nebo zcela kontejnery ignorujeme.

Změny, postupně:
kontejnArizace -> kontejnErizace
změna druhé čárky na tečku + začátek nové věty
odstranění čárky před "a"
a nebo -> , nebo (tou čárkou si nejsem jistý, takže bych rád, aby to někdo upřesnil)

### Screenshoty

![image](https://github.com/ssps-cajthaml/issues/assets/73956350/4bbe6614-7192-440c-bb97-2999660f8dee)

### Vaše jméno

Matyáš Capák

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód na tlapky: ISSUES2024-A
