### ISSUE TITLE
[WEB] Špatná koncovka v Informacích - Kritéria hodnocení (MVOP4 WBF)

### ISSUE THREAD

**Issue by NewSulc** [ssps-cajthaml/issues#281]
### Popis problémů

Špatné sklonení slova _dobrovolní_ v Kritériích hodnocení u předmětu MVOP4 WBF

### Reprodukce problému

**AS-IS:**
1. Jsem na stránce a vyberu předmět _MVOP4 WBF_
2. Přejdu na _Inforamce a upozornění_
3. Rozkliknu si _Kritéria hodnocení_
4. Přejedu dolů na sekci _Části hodnocení_
5. Zde je špatná koncovka u bodu _"dobrovolní ustní zkoušení"_ - **CHYBA**

**TO-BE:**
Místo _dobrovolní_ bude _dobrovolné_

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf-2024/announcements/kriteria-hodnoceni-667acfa90e3df685b2304d39

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Brave Browser**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

![image](https://github.com/user-attachments/assets/3b29484f-6cb4-4e2b-a5ea-f25d37350a64)

### Vaše jméno

Vojtěch Šulc

**Comment by cajthamlmatej** [comment]
Děkuji, kód: ISSUES2024-THETA
