### ISSUE TITLE
[WEB] chyba animace

### ISSUE THREAD

**Issue by fanda857** [ssps-cajthaml/issues#282]
### Popis problémů

pokud mam vybraný předmět v roce 2024/25 a kliknu na výběr předmětů animace se přehraje (nevím jestli intentional)
![image](https://github.com/user-attachments/assets/caf63a1d-d045-43d8-829b-670b693c3371)

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Vybrat předmět z roku 2024/25
3. otevřít výber předmětů

### Stránka

asi kdekoliv

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Vaše jméno

František Václavek

**Comment by cajthamlmatej** [comment]
Děkuji, kód: ISSUES2024-THETA
