### ISSUE TITLE
[MATERIÁL] Překlep kritéria hodnocení

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#284]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Informace - Kritéria hodnocení

### Popis problémů

Překlep "dobrovolní ústní zkoušení"

### Lokace

Sekce Části hodnocení

### Oprava

"dobrovolní ústní zkoušení" -> "dobrovolné ústní zkoušení"

### Screenshoty

![image](https://github.com/user-attachments/assets/1a9737d2-f052-40e1-a6c8-9cbfd25ec3a1)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód: ISSUES2024-THETA
