### ISSUE TITLE
Responzivita na mobilu

### ISSUE THREAD

**Issue by MightyShrek** [ssps-cajthaml/issues#286]
### Popis problémů

Při otevření ukázkového api a přijímání podmínek si všímám, že stránka přetéká do prava

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

Už jsem přijal podmínky, takže nemůžu reprodukovat

### Stránka

https://ssps.cajthaml.eu/services/api

### Zařízení

Operační systém: **Android**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Screenshot_20240910_123042_Chrome](https://github.com/user-attachments/assets/95acc3d8-acb0-47c7-a148-041edad025b0)

### Vaše jméno

Jan Vojíř

**Comment by cajthamlmatej** [comment]
Opraveno, bude nahráno. Kód: ISSUES2024-THETA
