### ISSUE TITLE
[MATERIÁL]  typo

### ISSUE THREAD

**Issue by Kondor777200** [ssps-cajthaml/issues#287]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Úvod do HTML a CSS

### Popis problémů

typo

### Lokace

https://ssps.cajthaml.eu/2-wba-2024/lesson/uvod-do-html-a-css/part/64da276d3bc9e3c268e19f57/pseudotridy

### Oprava

Fixnout typo aktivnim na aktivni

### Screenshoty

![image](https://github.com/user-attachments/assets/c1ecb604-a9d7-4017-a680-26d0056648a4)

### Vaše jméno

Albert Vala

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód: ISSUES2024-THETA
