### ISSUE TITLE
[WEB] Hover na tlačítko tlapek zaseká kurzor

### ISSUE THREAD

**Issue by krystofbruth** [ssps-cajthaml/issues#288]
### Popis problémů

Při hoverování na tlačítko normálních tlapek ve stránce úpravy profilu se kurzor zasekne v přepínání mezi stavy `cursor` a normálním kurzorem.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na hlavní stránce na tlačítko tlapek.
3. Najet kurzorem na tlačítko normálních tlapek.
4. Profit.

### Stránka

Přizpůsobení profilu uživatele.

https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: **MacOS**
Prohlížeč: **Brave Browser**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Kryštof Bruthans

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno v další verzi: ISSUES2024-THETA
