### ISSUE TITLE
[WEB]  Špatné zapsání bodů

### ISSUE THREAD

**Issue by JohnDoli** [ssps-cajthaml/issues#289]
### Popis problémů

Na stránce hodnocení, v sekci známky, v řádku aktivita je napsáno x/0 bodů.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na stránku hodnocení.
3. Profit.

### Stránka

https://ssps.cajthaml.eu/2-pva-2024/grading/

### Zařízení

Operační systém: **Windows 11**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Screenshot 2024-09-17 085538](https://github.com/user-attachments/assets/d46a3162-830f-4184-9d66-314bd02fdd8c)

### Vaše jméno

Jan Doležal

**Comment by cajthamlmatej** [comment]
Známky s nulovým bodovým základem nyní nemají /0 ve jméně. Děkuji, v další verzi bude. Kód: ISSUES2024-THETA
