### ISSUE TITLE
[WEB] D&D otevře okno se stáhnutím přetáhnutého souboru

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#29]
### Popis problémů

Při přetáhnutí souboru do odevzdání se otevře okno se stáhnutím daného soubor

![D D](https://user-images.githubusercontent.com/19969112/144487650-b6eaf71b-7b79-461b-a1b9-f344caa7c335.gif)
u.

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na nějaký domácí úkol -> [v ukázce](https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code)
3. Přetáhnout soubor na stránku, aby se odevzdal
4. ????
5. Free body [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]

### Stránka

[https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code](https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code)

### Zařízení

Operační systém: **Windows 10**
![image](https://user-images.githubusercontent.com/19969112/144488013-ddeb99eb-5eaf-4778-9a48-8bc1407cc340.png)

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Snad vyřešeno v v3.0.4b1.
