### ISSUE TITLE
Odpočítávání času při incidentu ve zkoušení

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#290]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

10s odpočítávat místo ukazování stále 10s

### Zdůvodnění

nevím jak dlouho trvá můj trest

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
V další verzi to bude. Děkuji. Kód: ISSUES2024-DELTA
