### ISSUE TITLE
[MATERIÁL] Špatný odkaz

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#291]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Lekce - První pololetí

### Popis problémů

Na stránce je špatný odkaz.

### Lokace

Grafová teorie - Průvodce labyrintem algoritmů

### Oprava

Vyměnit špatný odkaz za správný

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Opraveno, kód: https://pruvodce.ucw.cz
