### ISSUE TITLE
[NÁPAD] Potvrzení pro otevření zkoušení

### ISSUE THREAD

**Issue by CrispyBun** [ssps-cajthaml/issues#292]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Při kliknutí na aktivní zkoušení by se hodilo potvrzení, jestli student opravdu zkoušení chce začít

### Zdůvodnění

Bez potvrzení otevření se jednoduše může stát, že student omylem klikne na kvíz (který může udělat např. kdykoliv v týdnu) a hned se otevře a donutí studenta kvíz okamžitě vyplnit, protože se k němu nelze vrátit později

**Comment by cajthamlmatej** [comment]
V další verzi bude. Kód: ISSUES2024-DELTA
