### ISSUE TITLE
[WEB] Oznámení o neodevzdané práci, i když je odevzdaná

### ISSUE THREAD

**Issue by OndrejDudacek** [ssps-cajthaml/issues#293]
### Popis problémů

V upozorněních se mi objevila dvě, která mi připomínají práce, které končí za 3 dny. Zároveň upozorní říkají, že práce nemám odevzdané, což není pravda. Když jsem se koukal do nastavení upozornění, všiml jsem si, že se tam dá nastavit, aby vás portál upozornil, když práci máte odevzdanou, i když ne. Mám zaškrtnuté obě možnosti.

### Reprodukce problému

Postup k reprodukci:
1. zapnout si upozornění
2. odevzdat práci
3. počkat na blížící se termín

### Stránka

Upozornění

### Zařízení

Operační systém: **MacOS 15**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

<img width="578" alt="Screenshot 2024-09-20 at 14 11 41" src="https://github.com/user-attachments/assets/0afb98e4-8d73-4ef4-b92e-05d9e2c875ce">
<img width="1203" alt="Screenshot 2024-09-20 at 14 12 23" src="https://github.com/user-attachments/assets/9bd00342-4f8a-4420-864a-77a86981debb">
<img width="1209" alt="Screenshot 2024-09-20 at 14 13 04" src="https://github.com/user-attachments/assets/fa41cff7-6ead-450a-a6de-748370f6882d">
<img width="598" alt="Screenshot 2024-09-20 at 14 22 22" src="https://github.com/user-attachments/assets/65fa26fb-d69e-45bb-8f63-2d9cffc5227c">

### Vaše jméno

Ondřej Dudáček 3. C

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Kód: ISSUES2024-DELTA
