### ISSUE TITLE
[MATERIÁL] Překlep v úkolu

### ISSUE THREAD

**Issue by OndrejDudacek** [ssps-cajthaml/issues#294]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

práce Kurzy

### Popis problémů

Překlep v _jeden soubory_ místo _jeden soubor_.

### Lokace

V popisu práce v sekci ODEVZDÁNÍ.

### Oprava

Smazat _y_ ve slově soubory.

### Screenshoty

<img width="774" alt="Screenshot 2024-09-20 at 14 34 15" src="https://github.com/user-attachments/assets/01bcfd94-2552-4386-bc3b-901138ecfcc0">

### Vaše jméno

Ondřej Dudáček

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Kód: ISSUES2024-THETA
