### ISSUE TITLE
[WEB] Upozornění na neodevzdaný úkol

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#295]
### Popis problémů

Přišlo mi upozornění, že za 3 dny končí odevzdávání úkolu a že já jej nemám odevzdaný, i když ho odevzdaný mám.

### Reprodukce problému

Postup k reprodukci:
1. Splnit úkol
2. Počkat
3. Dostat upozornění

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit-2024/work/grafy-1-grafu-na-vrcholech

### Zařízení

Operační systém: **Windows 11**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/bd92fbc8-5fd2-4cc2-8397-34b6dd636845)
![image](https://github.com/user-attachments/assets/69278a26-c424-4bd6-bb1f-99df35a8e5f8)

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
Duplikát #293
