### ISSUE TITLE
[WEB] Překlep v oznámení o cookies (ukládájí)

### ISSUE THREAD

**Issue by OndrejDudacek** [ssps-cajthaml/issues#296]
### Popis problémů

V hlášce Informace o lokálních souborech a cookies je překlep ve slově ukládájí, mělo by být ukládají.

### Reprodukce problému

Postup k reprodukci:
1. V prohlížeči smazat cookies k portálu
2. Otevřít portál

### Stránka

 Hláška/upozornění/oznámení s nadpisem Informace o lokálních souborech a cookies.

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Brave.**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

![Výstřižek](https://github.com/user-attachments/assets/0b7965ba-28fe-4b5b-9340-d64e626dbdc1)

### Vaše jméno

Ondřej Dudáček

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno v další verzi. Kód viz minulý issue.
