### ISSUE TITLE
[NÁPAD] Stránka hodnocení by mohla ukazovat rozmezí známek

### ISSUE THREAD

**Issue by CrispyBun** [ssps-cajthaml/issues#297]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Bylo by dobré mít možnost někde na stránce hodnocení rozkliknout nějaký popup (např. pole "aktuální známka") a zobrazit si potřebnou procentuální úspěšnost pro každou známku.

### Zdůvodnění

Rozmezí známek momentálně nejsou na jednodušše dohledatelném místě a při zobrazování aktuálního hodnocení by se hodilo je mít při ruce

**Comment by cajthamlmatej** [comment]
V další verzi bude. Kód na portál: ISSUES2024-THETA
