### ISSUE TITLE
[MATERIÁL] Překlep - Úvod do webových stránek

### ISSUE THREAD

**Issue by misrtjakub** [ssps-cajthaml/issues#298]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník 2. - 4. hodina

### Materiál

Úvod do webových stránek

### Popis problémů

Překlep ve skriptech v podkategorii Phishing. Zkratka pro password **harversting** fishing.

### Lokace

Podkategorie Phishing. 1. Věta.

### Oprava

harversting -> harvesting

### Screenshoty

![phishingchyba](https://github.com/user-attachments/assets/0a26addc-9826-497b-855a-2a44d5e3004f)

### Vaše jméno

Jakub Pokorný

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Kód viz minulá issue.
