### ISSUE TITLE
[NÁPAD] Chyba ve větě - Github issue form - Nahlášení problému v materiálech

### ISSUE THREAD

**Issue by misrtjakub** [ssps-cajthaml/issues#299]
### V jaké aplikaci se nachází nápad?

Ostatní

### Popis nápadu

Nejedná se o nápad, ale není tu kategorie na chyby v github issue forms, proto to píšu tady. Chyba ve větě. 
![chybagithub](https://github.com/user-attachments/assets/5612d422-e9fb-45a6-8581-f5311394f0da)

### Zdůvodnění

Přepsání chyby.

### Vaše jméno

Jakub Pokorný

**Comment by cajthamlmatej** [comment]
Opraveno, kód: ISSUES2024-THETA
