### ISSUE TITLE
[WEB] Nejde smazat soubor po prvním přetáhnutí

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#30]
### Popis problémů

Po odevzdání souboru pomocí D&D se soubor nedá odstrani
![D D](https://user-images.githubusercontent.com/19969112/144488789-9ff55bfa-9586-47af-98e3-eb7dcee64259.gif)
t

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na nějaký domácí úkol -> [v ukázce](https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code)
3. Přetáhnout soubor, aby se odevzdal
4. Zkusit vymazat soubor pomocí ikonky
5. ?????
6. Free body [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]

### Stránka

[https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code](https://ssps.cajthaml.eu/3-mvop-wbf/work/42-advent-of-code)

### Zařízení

Operační systém: **Windows 10**

![image](https://user-images.githubusercontent.com/19969112/144489121-655c5772-5ca3-4619-902e-b01c72d6c4d6.png)

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Nedaří se mi replikovat. Můžete to prosím ještě jednou ověřit? (Možná jsem to nějak opravil). Děkuji! @ItsOKayCZ

**Comment by ItsOKayCZ** [comment]
@cajthamlmatej Muzu potvrdit, je to opraveny. 👍
