### ISSUE TITLE
Překlepy ve skriptech

### ISSUE THREAD

**Issue by filiphorcicka** [ssps-cajthaml/issues#300]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Úvod do webových stránek - skripta

### Popis problémů

Při učení na test jsem narazil na pár chyb, jednalo se o překlep a o dvě špatně formulovaná slova.

### Lokace

Skripta - Malware -  sekce Ransomware - "ale může se stát, že _**randomware**_ bude později aktivován"
Skripta - Prohlížeče - sekce Chromium - "Hlavní nevýhodou Chromia je to, že jej _**využívat**_ již tolik prohlížečů"
Skripta - Prohlížeče - sekce Chromium - "Jediné použitelné možnosti _**je**_ Gecko a Blink" *je asi není vyloženě špatně, ale jsou by se tam hodilo více.

### Oprava

Skripta - Malware -  sekce Ransomware - "ale může se stát, že _**ransomware**_ bude později aktivován"
Skripta - Prohlížeče - sekce Chromium - "Hlavní nevýhodou Chromia je to, že jej _**využívá**_ již tolik prohlížečů"
Skripta - Prohlížeče - sekce Chromium - "Jediné použitelné možnosti _**jsou**_ Gecko a _Blink"

### Screenshoty

![Snímek obrazovky 2024-09-25 v 21 29 46](https://github.com/user-attachments/assets/7e2982f2-d49e-41ca-9afd-ef75155d2c27)
![Snímek obrazovky 2024-09-25 v 21 34 42](https://github.com/user-attachments/assets/abc92b7b-cd9a-4065-a3d0-85f43af95f83)

### Vaše jméno

Filip Horčička

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno. Pro body si aktivujte kód ISSUES2024-THETA.
