### ISSUE TITLE
[WEB] Počet vlastněných předmětů je vždy o 1 vyšší

### ISSUE THREAD

**Issue by BlackPapered** [ssps-cajthaml/issues#301]
### Popis problémů

Při přepočítání jednotlivých předmětů je součet v pravém horním rohu vždy o 1 vyšší.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Přejít na profil
3. Přejít do přizpůsobení profilu

### Stránka

https://ssps.cajthaml.eu/user/customization

### Zařízení

Operační systém: Windows 11
Prohlížeč: Google
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

### Screenshoty

![svablol](https://github.com/user-attachments/assets/97694d6e-1a65-4617-b7cd-3e3dec51e8df)

### Vaše jméno

Magdalena Dobešová

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno v další verzi. Kód: ISSUES2024-THETA
