### ISSUE TITLE
[WEB] Services

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#302]
### Popis problémů

V prohlížeči safari nefunguje služby pro výuku button, při přepsání url to nefunguje, při vložení ano (tf)

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "služby pro výuku"
3. nothing happend

### Stránka

všude tf

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Bohužel, mně se to neděje a dle mého se jedná o nějaký problém s aktualizaci webů, prozatím nechávám otevřené.
