### ISSUE TITLE
[WEB] QR přihlášení

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#303]
### Popis problémů

Při přihlášení pomocí QR kódu nejde přihlásit, pokud máme darkmode

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se pomocí QR.
2. Pokusit se načíst QR

### Stránka

Login

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**
- všude

### Chyba

\```...```

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Nejspíše opraveno? Zkuste v další verzi webu. Kód viz minulý issue.
