### ISSUE TITLE
[NÁPAD] Not-allowed při najetí na tlačítka, která nesmíte používat

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#304]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

<img width="588" alt="image" src="https://github.com/user-attachments/assets/3e28daf2-6628-406d-aeaf-674d49bef597">
při najetí myší se kurzor změní, na not-allowed, když není možné provést konvertování měny

### Zdůvodnění

váš web mě trollí

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Opraveno, kód: ISSUES2024-KAPPA
