### ISSUE TITLE
[WEB] Špatná přehlednost odkazu ve tmavém režimu.

### ISSUE THREAD

**Issue by AntonBrodman** [ssps-cajthaml/issues#305]
### Popis problémů

V informačním bloku s odkazem oranžové barvy, tento odkaz má špatnou viditelnost pokud se používá tmavý režim stránky.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na Informace a upozornění
3. Kliknout na Použití LaTeX pro odevzdání
4. Odkaz je špatně čitelný při využívání tmavého režimu.

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit-2024/announcements/pouziti-latex-pro-odevzdani-668595ed4e6f118cf05cbd9a

### Zařízení

Operační systém: Windows
Prohlížeč: Google Chrome
Je prohlížeč aktualizován na nejnovější verzi: idk brah

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/96aac744-5755-4c02-93ba-1e9e245d2538)

**Comment by cajthamlmatej** [comment]
V další verzi opraveno, kód: ISSUES2024-THETA.
