### ISSUE TITLE
[MATERIÁL] Překlepy

### ISSUE THREAD

**Issue by Tadk0** [ssps-cajthaml/issues#307]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Úvod do webových stránek

### Popis problémů

Ve skriptu - Malware je překlep ve větě: Když máte štěstí, o data nepřijdete, ale může se stát, že randomware bude později znovu aktivován. 
Překlep je ve slově "randomware", kde by měl být "ransomware"

Ve skriptu - Prohlížeče je překlep ve větě: Nejčastější jádra jsou Gecko (Mozilal FireFox), Webkit (Safari), Blink (Google Chrome) a např. Trident (Internet Explorer). Jádra se hlavně liší v tom, jak se webové stránky vykreslují.
Překlep je ve slově "Mozilal", kde by mělo bát "Mozilla"

### Lokace

Sekce - Malware, prohlížeče

### Oprava

Z randomware na ransomware a z mozilal na mozilla

### Screenshoty

https://ctrlv.cz/W9Le
https://ctrlv.cz/YogU

### Vaše jméno

Tadeáš Rypar 2.K

**Comment by cajthamlmatej** [comment]
První chyba byla nahlášena dříve, druhou jsem opravil, děkuji. Kód pro body: ISSUES2024-THETA
