### ISSUE TITLE
[WEB] Otevření revize z upozornění se nenačte

### ISSUE THREAD

**Issue by CrispyBun** [ssps-cajthaml/issues#308]
### Popis problémů

Pokud otevřu revizi zkoušení z odkazu v upozornění, revize se nenačte. Načte se pouze pokud revize již byla otevřená přes stránku zkoušení.

### Reprodukce problému

viz výše

### Stránka

https://ssps.cajthaml.eu/4-dvop-pit-2024/exams/

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji, bude v další verzi. Kód viz minulá issue.
