### ISSUE TITLE
[NÁPAD] Přidání tlačítka upozornění a nastavení na stránku upravení profilu

### ISSUE THREAD

**Issue by luckercz** [ssps-cajthaml/issues#309]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Přidání tlačítek upozornění a nastavení(obr. 1) na stránku upravení profilu(obr. 2).
![image](https://github.com/user-attachments/assets/10c810cb-80d7-4d1f-ad0f-433cdd8c414b)
![image](https://github.com/user-attachments/assets/a544470a-61fc-4ae6-8adb-89ef299aed46)

### Zdůvodnění

Myslím, že by se zlepšil user experience, odstranila by se potřeba překlikávat ze stránky upravení profilu na hlavní stránku pro přístup do nastavení a k upozorněním.

### Vaše jméno

Lukáš Andrýsek

**Comment by cajthamlmatej** [comment]
V další verzi přidáno, děkuji. Kód: ISSUES2024-KAPPA
