### ISSUE TITLE
[WEB] Chyby při ukládání komentáře

### ISSUE THREAD

**Issue by michalhejd** [ssps-cajthaml/issues#31]
### Popis problémů

Při přidání komentáře občas vyhodí error

### Reprodukce programu

Postup k reprodukci:
1. Přidání komentáře
2. Načítání spodní části boxu
3. Chyba

### Stránka

ssps.cajthaml.eu

### Zařízení

Operační systém: iOS
Prohlížeč: Safari
Je prohlížeč aktualizován na nejnovější verzi: ano

### Chyba

\```...```

### Screenshoty

![DF04B9E7-3F64-4D2D-AEBF-420A425BAD43](https://user-images.githubusercontent.com/71251670/144831787-e55ffda4-9853-4d21-bc3f-fb0b46f5943d.jpeg)

### Vaše jméno

Michal Hejduk

**Comment by Denio21** [comment]
Můžete zkusit nyní? @michalhejd

**Comment by cajthamlmatej** [comment]
V příští verzi webu to již chybu neukáže. Ukáže to pouze popup, který lze uzavřít. Tohle se děje nejspíše kvůli nějaké DNS chybě a nedaří se mi to reprodukovat.
