### ISSUE TITLE
[WEB] Gramatická chyba 

### ISSUE THREAD

**Issue by pitrdzej** [ssps-cajthaml/issues#310]
### Popis problémů

V podstránce "Zkoušení" při rozkliknutí otázky "Co se stane, když systém obejdu nebo budu podvádět?" je gramatická chyba. V bodech "co nedělat" je dvakrát použita čárka před slovem "než", což je podle jazykové příručky nepřípustné. 
_"Následuje‑li po spojce než pouze větný člen, a to jiný než přísudek (srov. níže typ víc ležel(,) než seděl), tzn. že tato část věty neobsahuje určitý slovesný tvar, čárka před spojku nepatří" ([zdroj](https://prirucka.ujc.cas.cz/?id=154))_

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

Zkoušení - SSPŠ Cajthaml
[https://ssps.cajthaml.eu/2-pva-2024/exams/](https://ssps.cajthaml.eu/2-pva-2024/exams/)

### Zařízení

Operační systém: **MacOS**
Prohlížeč: **Arc**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/d93a713d-5580-445f-bb31-8c91c4af5e5b)

### Vaše jméno

Petr Jíša

**Comment by cajthamlmatej** [comment]
Děkuji, v další verzi opraveno, kód: ISSUES2024-THETA
