### ISSUE TITLE
Grafy ve statistikách

### ISSUE THREAD

**Issue by AntonBrodman** [ssps-cajthaml/issues#311]
### Popis problémů

Při načtení stránky s statistikami se vypíče graf reprezentující body studenta. Pokud se změní předmět tak graf se nezmění z posledního načteného. Pokud se stránka načte znovu tak se ukáže správný graf.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na hodnocení
3. Změním předmět
4. Graf se neaktualizuje podle předmětu

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf-2024/grading/

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/4a8beb01-2a0d-4175-8b38-8d179f801f5b)

**Comment by cajthamlmatej** [comment]
Opraveno v další verzi, mód: ISSUES2024-DELTA
