### ISSUE TITLE
[WEB] Popup pro otevření zkoušení se otevře i pro neaktivní zkoušení

### ISSUE THREAD

**Issue by CrispyBun** [ssps-cajthaml/issues#312]
### Popis problémů

Pokud uživatel klikne na neaktivní zkoušení (na kterém ani není žádny styl pro hover a nevypadá, že by na něj mělo jít kliknout) se otevře okno pro otevření toho zkoušení, kde ale kliknutí na potvrzení nic nedělá.

### Reprodukce problému

-

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf-2024/exams/

### Zařízení

Operační systém: Windows
Prohlížeč: Firefox
Je prohlížeč aktualizován na nejnovější verzi: ano

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno, kód: ISSUES2024-KAPPA
