### ISSUE TITLE
[MATERIÁL] V prezentaci o grafech je špatně popsaný úkol

### ISSUE THREAD

**Issue by CrispyBun** [ssps-cajthaml/issues#314]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Grafová teorie, slide 69

### Popis problémů

V zadání je napsáno "Z níže neorientovaného grafu vytvořte orientovaný graf dle předchozího schématu", i když se má vytvářet neorientovaný graf z orientovaného.

### Lokace

https://ssps.cajthaml.eu/4-dvop-pit-2024/lesson/prvni-pololeti/part/66859a7447c43c8b3ac492fc

slide 69

### Oprava

naopak

**Comment by cajthamlmatej** [comment]
Opraveno, děkuji. Kód: ISSUES2024-CHI
