### ISSUE TITLE
[MATERIÁL] DVOP4 grafy prezentace 

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#315]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Pokročilá informatika, 4. ročník

### Materiál

Grafy prezentace

### Popis problémů

slide 50, věta o existence listu --> věta o existenci listu

### Lokace

50. slide

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Děkuji, kód: ISSUES2024-CHI
