### ISSUE TITLE
[WEB] Gramaticka chyba v hodnoceni

### ISSUE THREAD

**Issue by kubrt22** [ssps-cajthaml/issues#316]
### Popis problémů

Po rozkliknutí hodnocení, je v bloku "Rozmezí hodnocení" napsáno -1000% - 40%, 85% - 1000%

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "Hodnocení"
3. Kliknout na "Celkové hodnocení"
4. Chyba

### Stránka

https://ssps.cajthaml.eu/2-pva-2024/grading/

### Zařízení

Operační systém: **Všude**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/f14d5ee9-7e4f-4feb-b76c-ad6889c2d41c)

### Vaše jméno

Viktor Štědrý

**Comment by cajthamlmatej** [comment]
Co je přesně problém? To číslo? Formát?

Takto portál ukládá rozmezí známek, můžu tam dát větší číslo, infinity není nutné teď reprezentovat.
