### ISSUE TITLE
[WEB] Nefunkční odkaz na rezervaci konzultace

### ISSUE THREAD

**Issue by Spendroslav** [ssps-cajthaml/issues#318]
### Popis problémů

Když chci v položce "Konzultace" kliknout na odkaz pro rezervaci, tak jsem přesměrován na neplatný odkaz.
Toto je odkaz, na který jsem přesměrováván: https://calendar.app.google/LJKYvJRZKPfw3txT6

### Reprodukce problému

Postup k reprodukci:
1. https://ssps.cajthaml.eu/2-wba-2024/announcements/konzultace-66bf96028a778cdb2699fb14
2. Kliknout na "odkazu [ZDE]"
3. "Schůzka byla možná odstraněna nebo je odkaz nesprávný"

### Stránka

https://ssps.cajthaml.eu/2-wba-2024/announcements/konzultace-66bf96028a778cdb2699fb14
https://calendar.app.google/LJKYvJRZKPfw3txT6

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ANO**

### Chyba

Schůzka nebyla nalezena

### Vaše jméno

Ondřej Diviš

**Comment by cajthamlmatej** [comment]
Děkuji, vím o tom, konzultace se v rámci organizace školy museli zrušit, informace o tom, jak to bude, zveřejním v pondělí. 
Prozatím uzavírám.
Kód: ISSUES2024-THETA
