### ISSUE TITLE
[WEB] Uložení vybraného předmětu

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#32]
### Popis problémů

Mobilní aplikace si nepamatuje zvolený předmět po zavření.

### Reprodukce programu

Postup k reprodukci:
1. zapnout aplikaci
2. zvolit předmět
3. zavřít aplikaci
4. znovu otevřít aplikaci

### Stránka

https://ssps.cajthaml.eu/

### Zařízení

Operační systém: **Android**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
V další verzi by mělo být opraveno. Musíme to ale reálně zkusit až v PWA aplikaci.

**Comment by cajthamlmatej** [comment]
Po dalších opravách byl problém konečně vyřešen. Děkuji! :)
