### ISSUE TITLE
[WEB] Přepínání na light mode, jakmile rozkliknu adventní kalendář

### ISSUE THREAD

**Issue by pitrdzej** [ssps-cajthaml/issues#323]
### Popis problémů

Jakmile přijdu na adventní kalendář, celý web se mi přepne na light mode, byť mám nastavený darkmode.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Přepnout na dark mode
3. Jít na adventní kalendář
4. Jít zpět

### Stránka

https://ssps.cajthaml.eu/season/advent

### Zařízení

Operační systém: **MacOS**
Prohlížeč: **Arc*
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://github.com/user-attachments/assets/8ac48502-7a93-41dc-81e1-e50dc3d65821)
![image](https://github.com/user-attachments/assets/7f1b71d6-2622-4383-bd6e-deba4d692417)
![image](https://github.com/user-attachments/assets/4323473d-f244-4886-91d7-58be3207296e)

### Vaše jméno

Petr Jíša

**Comment by cajthamlmatej** [comment]
Bohužel je to feature.

**Comment by pitrdzej** [comment]
L
