### ISSUE TITLE
[WEB] Světlý režim po návratu z adventního kalendáře

### ISSUE THREAD

**Issue by VojtechNebes** [ssps-cajthaml/issues#324]
### Popis problémů

Používám tmavý režim, ale když vlezu na adventní kalenář a pak se vrátím, mám světlý.

### Reprodukce problému

Postup k reprodukci:
1. V headeru hlavní stránky přepnout na tmavý režim
2. Kliknout na tlačítko Advent
3. Jakýmkoliv způsobem (i po zavření prohlížeče) se vrátit na hlavní stránku
4. Mám světlý režim

### Stránka

https://ssps.cajthaml.eu/
https://ssps.cajthaml.eu/season/advent

### Zařízení

Operační systém: **Linux**
Prohlížeč: **Chromium**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

![Hlavní stránka s tmavým režimem](https://github.com/user-attachments/assets/e37d76f6-2fd5-49ba-9917-9251cd5f6c0b)
![Adventní kalendář](https://github.com/user-attachments/assets/3374af28-a7ed-4787-80fb-d87166894652)
![Hlavní stránka po návratu](https://github.com/user-attachments/assets/fb4ae7a6-70d4-4c6b-9a1a-42718b18f5e8)

### Vaše jméno

Vojtěch Nebes

**Comment by cajthamlmatej** [comment]
Viz #323, chtěná feature.

**Comment by VojtechNebes** [comment]
ošklivá feature
