### ISSUE TITLE
[WEB] Světlý režim při odchodu ze sezóního adventního kalendáře

### ISSUE THREAD

**Issue by jkocman** [ssps-cajthaml/issues#325]
### Popis problémů

Když mám na webu nastavený tmavý režim a přejdu na stránku adventního kalendáře, režim se po návratu zpět změní na světlý.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Mít zapnutý tmavý režim.
3. Kliknout na tlačítko pro vstup na stránku adventního kalendáře.
4. Jít zpět na hlavní stránku.

### Stránka

hlavní stránka a stránka adventního kalendáře:

https://ssps.cajthaml.eu/
https://ssps.cajthaml.eu/season/advent

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Jakub Kocman

**Comment by cajthamlmatej** [comment]
Duplikát #323 a #324, je to feature.
