### ISSUE TITLE
[WEB] zobrazení bodování 

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#33]
### Popis problémů

Na mobilu se jednotlivé položky bodování nezobrazují na celý řádek. 

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Přejít na osobní profil 
3. Zobrazit podrobnosti o bodování daného úkolu
4. Pokud žádný z textů není dostatečně dlouhý tak se jednotlivé položky bodování nezobrazují na celý řádek (pokud je třeba slovní hodnocení na celý řádek nebo delší, pak k chybě nedochází) 

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/profile 

### Zařízení

Operační systém: **Android**
Prohlížeč: **Brave**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Screenshot_20211211_135103_com brave browser](https://user-images.githubusercontent.com/82168954/145678004-bdb9ef44-9953-42f1-8be2-32e221c94e26.jpg)

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Opraveno v následující verzi.
