### ISSUE TITLE
[WEB] [Feature Request] Síň slávy

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#36]
### Popis problémů

Vytvoření stránky se žebříčkem nejlepších studentů z každého předmětu (za pololetí). Samozřejmě pod podmínkou, že student bude souhlasit.

### Reprodukce programu

1. Vytvořit novou stránku
2. Kontaktovat mě, abych ji naprogramoval
3. Hotovo

### Stránka

ssps.cajthaml.eu/hall-of-fame

### Zařízení

Jakékoliv

### Chyba

není chyba, jen je to sen

### Vaše jméno

Sebastian

**Comment by Denio21** [comment]
😶

**Comment by Sebight** [comment]
I přes stav této issue mám pocit, že by to mohl být dobrý dodatek na portál.
