### ISSUE TITLE
[WEB] Přidat tlačítko pro zkopírování code snippetu

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#37]
### Popis problémů

Přidat tlačítko pro zkopírování kódu v snippetech.

### Reprodukce programu

#7

### Stránka

Např.: [https://ssps.cajthaml.eu/3-mvop-wbf/page/vue-ve-skole](https://ssps.cajthaml.eu/3-mvop-wbf/page/vue-ve-skole)

### Zařízení

#7

### Vaše jméno

Oldřich Krupauer

**Comment by M4TY** [comment]
Tato funkce by se hodila i k vstupům do logický úloh

**Comment by cajthamlmatej** [comment]
Možná by se to hodilo i do prezentací, ale bojím se, že takového kopírování by ještě více zjednodušilo práci studentům. ;)

**Comment by M4TY** [comment]
Myslím si, že to je spíše QoL funkce nežli zjednodušení psaní kódu. 😄

**Comment by ItsOKayCZ** [comment]
Je to takova QoL funkce jak rika @M4TY, protoze student si ten kod muze stejne zkopirovat tak ci tak, jenom musi pritom potahnout mysi a zmacknout ctrl+C, kdyz to tlacitko tam neni :D

**Comment by cajthamlmatej** [comment]
Přidáno v další verzi webu.
