### ISSUE TITLE
[WEB] Motivace na webu

### ISSUE THREAD

**Issue by lennerjiri** [ssps-cajthaml/issues#39]
### Popis problémů

POTŘEBUJU MOTIVAČNÍ ODDĚLENÍ 

- including moudra 
- motivační formulky
- A psychickou podbporu 

### Reprodukce programu

- nedostatek mentální podpory pro studenty v rámci vývoje WBA
- studenti jako já mají PTSD z velkých projektů co si naložili na talíř a nejsou schopni spracovat
- bojí se poté, že neprospějí a budou vyhoštěni ze SSPŠ s pětkou na vysvědčení

### Stránka

- chce to něco special 

### Zařízení

- všechny

### Chyba

- missing motivace

### Screenshoty

- nemam

### Vaše jméno

Pan Lenner

**Comment by cajthamlmatej** [comment]
Pokusím se provést! :)

**Comment by cajthamlmatej** [comment]
Interně stále monitorováno, portál nějaké věci již řeší.
