### ISSUE TITLE
Login formulář přetéká

### ISSUE THREAD

**Issue by Jiri-Lenner** [ssps-cajthaml/issues#41]
### Popis problémů

Přetéká formulář pro zadání kódu jenž je nám zaslán na email

### Reprodukce programu

Postup k reprodukci:
1. Přihlasit se pomocí emailu
2. Problém je následovně viditelný

### Stránka

Jsem linej se zas odhlašovat sry :)

### Zařízení

IOS (iphone)

### Chyba

Žadne

### Screenshoty

![A2EC4BB9-8F1D-4781-BDFE-C3814D3FD89C](https://user-images.githubusercontent.com/78266342/154495779-7e49d592-92fe-4db5-9b8b-7a352ea6b261.png)

### Vaše jméno

Pan Lenner

**Comment by cajthamlmatej** [comment]
Duplikát s #34
