### ISSUE TITLE
[WEB] Decimalni cisla

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#44]
### Popis problémů

Po pridani `1.1` a `0.6` se cislo spatne vypisuje.
![image](https://user-images.githubusercontent.com/19969112/156040971-1ea8cb52-886a-41d2-8d2e-253a204b915a.png)

Reseni: Zakrouhlit pouze na 2 desetinna mista :)

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Podivat se na `Osobní profil`
3. ?
4. Profit 🤔 

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/profile

### Zařízení

Operační systém: Windows
Prohlížeč: Firefox
Je prohlížeč aktualizován na nejnovější verzi: ano

### Screenshoty

![image](https://user-images.githubusercontent.com/19969112/156041236-e3b5f521-51fb-4392-a88c-e30041a3f0ce.png)

### Vaše jméno

Oldřich Krupauer

**Comment by MarekProkopec** [comment]
![image](https://user-images.githubusercontent.com/51177304/160336956-ee63c716-68ac-45cc-a08c-e90cdb8f3c9e.png)

**Comment by MarekProkopec** [comment]
![image](https://user-images.githubusercontent.com/51177304/160337161-c1ef14c7-5d41-4594-b417-6cd449b34b52.png)

**Comment by cajthamlmatej** [comment]
Mělo by být opraveno v příští verzi, prosím zkontrolujte a kdyžtak znovu otevřeme.

**Comment by cajthamlmatej** [comment]
Znovu se to zobrazilo panu Procházkovi.
