### ISSUE TITLE
[WEB] Nefunkční file selektor

### ISSUE THREAD

**Issue by Vojtysek** [ssps-cajthaml/issues#45]
### Nefunkční file selektor pro Mozilla Firefox

Při pokusu odevzdat jakýkoliv soubor pro úkol [(38.) Ynivolserp ] v prohlížeči **Mozilla Firefox** byl marný. Při kliknutí na form pro vložení filu nic neprovedl, absolutně nic se nestalo. Pomohla až změna prohlížeče.

### Reprodukce programu

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "Webové aplikace"
3. Kliknout na "Práce"
4. Vybrat "(38.) Ynivolserp"
5. Sjet dolu do sekce odevzdání
6. Kliknout na "Soubor"

### Stránka

https://ssps.cajthaml.eu/2-wba/work/38-ynivolserp

### Zařízení

Operační systém: **iOS**
Prohlížeč: **Mozilla Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Vaše jméno

Vojtěch Döme

**Comment by Sebight** [comment]
VS Code iOS version? :O
