### ISSUE TITLE
[WEB] Oznámení o nově získaných bodech botem BOTaml 

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#47]
### Popis problémů

Přidání funkce, která by poslala oznámení do DMs daného uživatele o úpravě bodů. Ideálně za co byly body odebrané či přidané, kolik byl bodový základ, percentil etc. Uživatel by si tuto funkci mohl sám vypnout, časem by to mohlo být otravné :D 

### Reprodukce programu

.

### Stránka

.

### Zařízení

.

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Asi jste určil špatnou kategorii. Tohle z bezpečnostních důvodů nechci podporovat. Je naplánované mít notifikace přímo z webu, kde by takové věci byly (spíše jen text o změně). Počet bodů, hodnocení a podobné věci se nesmí mimo web dostat.
