### ISSUE TITLE
[WEB] JavaScript playground

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#48]
### Popis problémů

Protože se na předmětu WBA nebude učit Node, znamená to, že studenti musí JS kód spouštět v DevTools.

Na jednu stranu to je dobrý practive, ale na druhou stranu to může být nepříjemné.

Navrhuji proto vytvoření **JavaScript Playground**-u na webovém portálu, kde by šlo z TextBoxu spouštět JS kód a vidět jeho output.

Potenciálně by měl být skript co bude spuštěn nějak sanitized, ale to bych ještě musel udělat research. :shipit: 

Kdyby byla potřeba jakákoliv pomoc:
1. https://github.com/
2. Jít na repo s webem
3. Manage Access
4. https://github.com/sebight
5. Profit.

### Reprodukce programu

Feature request.

### Stránka

1. ssps.cajthaml.eu
2. Vybrat předmět WBA
3. Pod **Hostingem** by byl **Playground** -> na pravém Navbaru.

### Zařízení

PC only, probably.

### Screenshoty

![obrazek](https://user-images.githubusercontent.com/59232422/158680078-924d03ab-8c12-4b04-8fb1-8b4e1df20058.png)

### Vaše jméno

Sebastian

**Comment by Sebight** [comment]
Insta close = cringe 😉

**Comment by cajthamlmatej** [comment]
V další verzi vytvořeno. Pro body se připomeňte po tom, co vytvořím účty na nový školní rok.
