### ISSUE TITLE
[WEB] Přidání možnosti zobrazit všechny úkoly v jednom listu

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#49]
### Popis problémů

Hodila by se přidat možnost si zobrazit všechny moje úkoly na jednom místě, aniž bych musel chodit do předmětu A a poté do předmětu B, není to vyloženě problém, ale spíše QoL nápad.

### Reprodukce programu

-

### Stránka

-

### Zařízení

-

### Chyba

-

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Na jakém místě by měli být? Aktuálně si můžete přidat .ical kalendář do vašeho, tam všechny úkoly uvidíte.

**Comment by M4TY** [comment]
To je právě ta věc na kterou asi úplně nevím odpověď, jediné co mě napadá je přidat nějaké tlačítko které by v pracích vypínalo a zapínalo všechny aktivní úkoly.

**Comment by cajthamlmatej** [comment]
Přidáno v další verzi webu.
