### ISSUE TITLE
[WEB] V samostudiu nefunguje procházení otázek pomocí kláves '<' '>'

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#5]
**Popis problémů**
V procházení otázek ve samostudiu nelze posouvat otázky pomocí kláves "na matematické porovnání velikosti".

**Pozice stránky**
https://ssps.cajthaml.eu/2-pva/selfstudy/test-1

**Reprodukce**
Postup k reprodukci:
1. Přihlásit se a vybrat PVA.
2. Kliknout na "Samostudium"
3. Zkusit klikat '<' '>' a zjistit, že se nic neděje.
4. Profit (bodíky Sebastian H. ❤️ ).

**Očekávané chování**
A, D otázky posouvá, ale <,> nikoliv.

**Screenshoty**
![obrazek](https://user-images.githubusercontent.com/59232422/135707368-548c852b-b2e6-4651-9d2d-f3be1c57aee4.png)

**Informace zařízení**
Operační systém: **Windows**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano*

**Comment by cajthamlmatej** [comment]
Klávesami pro menší a větší jsem myslel šipky na klávesnici. Upravím.
