### ISSUE TITLE
[WEB] přidat api na získání času 

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#53]
### Popis problémů

Chtěl bych poprosit o přidání api pro získání aktuálního času 

### Reprodukce problému

Postup k vytvoření:
1. Přihlásit se do pc
2. Kliknout na visual studio code 
3. Napsat kód
4. Uploadnout na server
5. Profit.

### Stránka

Morsmordre idk jak ta stránka je

### Zařízení

Váš server 

### Chyba

\```...```

### Vaše jméno

Lukáš Kníže

**Comment by Sebight** [comment]
A co třeba toto? http://worldtimeapi.org/

**Comment by cajthamlmatej** [comment]
> A co třeba toto? http://worldtimeapi.org/

Tohle jsme řešili. Řekl jsem mu, ať to zapíše. Morsmordre není world, ale má vlastní server a tam je čas často potřeba.

**Comment by cajthamlmatej** [comment]
Přidáno. Děkuji.
