### ISSUE TITLE
[WEB] návrh na vytvoření game library na portálu

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#54]
### Popis problémů

Navrhuji vytvořit game library kde budou jednotlivé klikačky, případně i jiné herní projekty studentů které bude možné hrát v prohlížeči. 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se k pc
2. Zapnout visual studio code 
3. Naprogramovat to
4. Nahrát na server
5. Posbírat hry/odkazy od studentů 
6. Nahrát do databáze 
7. Profit.

### Stránka

gaming.cajthaml.eu

### Zařízení

Idk

### Chyba

\```...```

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Interně stále monitorováno, portál nějaké věci již řeší.
