### ISSUE TITLE
[WEB] Nápad - Přidání filtrování vzácnosti pro itemy

### ISSUE THREAD

**Issue by ItsOKayCZ** [ssps-cajthaml/issues#55]
### Popis problémů

Přidání dropdownu v [profilu](https://ssps.cajthaml.eu/profile/customize), kde si uživatel vybere vzácnost, podle které se itemy vyfiltrují

### Reprodukce problému

#17

### Stránka

https://ssps.cajthaml.eu/profile/customize

### Zařízení

#17

### Vaše jméno

Oldřich Krupauer

**Comment by cajthamlmatej** [comment]
Přidáno v další verzi webu.
