### ISSUE TITLE
[WEB] Stránka nejde otevřít na Firefoxu

### ISSUE THREAD

**Issue by InnocentSinEternalSenia** [ssps-cajthaml/issues#58]
### Popis problémů

Stránka mi nejde otevřít na Firefoxu. Zkoušel jsem ji otevřít v Google Chrome, a tam funguje.

Restart/update Firefoxu/počítače nic nespravil.

### Reprodukce problému

Postup k reprodukci:
1. Spustit Firefox
2. Jít na stránky ssps.cajthaml.eu
3. Nic víc nejde

### Stránka

[ssps.cajthaml.eu](https://ssps.cajthaml.eu/auth/out)

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```client_error: FETCH_SUBJECTS
repository: n
api_error: AUTH_INVALID_TOKEN
api_error_description: Attached token is not valid or the request is expired.
token: 613205d541cec603a4c6f50d (2022-04-28T15:02:31.000Z)
subject: 6125304d22feeb9a7d44fcc5
platform: Win32
vendor: 
cookies: true
doNotTrack: unspecified```

### Screenshoty

![image](https://user-images.githubusercontent.com/92751077/165997837-228d8d17-1ca6-4080-97fc-3cac2743bf96.png)

### Vaše jméno

N. Jones

**Comment by cajthamlmatej** [comment]
To bude nejspíše tím, že se stránka aktualizovala a Vám během toho vypršel přihlašovací token. Interně mam tuto chybu zaevidovanou.

Návod na fixnutí:
- https://ssps.cajthaml.eu/
- otevřít DevTools (F12)
- najít záložku Application
- v podmenu Application najít Storage
- kliknout na Clear site data
- refreshnout stránku

**Comment by cajthamlmatej** [comment]
Mělo by to být fixnuté. Doufám, že to bude fungovat. :|
