### ISSUE TITLE
[WEB] Překlepy v textu

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#6]
**Popis problémů**
Pravopisné chyby v textu o aktualizaci samostudia.

**Pozice stránky**
https://ssps.cajthaml.eu/2-wba/selfstudy

**Screenshoty**

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/35110087/135711382-bb7d4545-90d6-4974-a169-f17b874e911e.png">

**Informace zařízení**
Operační systém: **Darwin Kernel Version 20.6.0 root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64**
Prohlížeč: **Safari**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

**Comment by Denio21** [comment]
Bylo by dobré dopsat, jaké chyby se ve screenshotu nachází. Já vím, že jsi to posílal na Discord, ale tady je to přeci o rrochu lepší @M4TY

**Comment by M4TY** [comment]
Samostudia typu otázek byl**a** vylepšen**a**.
