### ISSUE TITLE
[NÁPAD] Item tradeup

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#60]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Dovolil by uživatelům zkombinovat itemy stejné rarity a vylepšit ho do jednoho lepší rarity.

Combination rate by byl třeba 1 ku 10.

### Zdůvodnění

Využití pro useless nehezké itemy.

### Vaše jméno

Sebastian

**Comment by cajthamlmatej** [comment]
Přidáno v dalším updatu webu.
