### ISSUE TITLE
[NÁPAD] Tutorial na používání prezentace 

### ISSUE THREAD

**Issue by lukassuprer** [ssps-cajthaml/issues#61]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Moc by se mi líbilo kdybych zjistil dříve než po celém školním roce, co všechno se dá používat za klávesové zkratky v prezentacích. Mohl by u prezentací být například nějaký návod na jejich používání.

### Zdůvodnění

Velmi jsem se nakrkl, když jsem se o tom dozvěděl až po takové době, i když je to tak podstatné a nemohl jsem tak dlouho používat Yoka v prezentacích.

### Vaše jméno

Lukáš Procházka

**Comment by cajthamlmatej** [comment]
Vytvořeno.
