### ISSUE TITLE
[WEB] Copy button offset

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#62]
### Popis problémů

V snippetech (v zadání) je špatně položený copy button.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na úkol, který obsahuje embed souborů.
3. Kouknout se na embed souboru.
4. Profit.

### Stránka

https://ssps.cajthaml.eu/2-pva/work/60-rakvidla

### Zařízení

Jakékoliv.

### Screenshoty

![image](https://user-images.githubusercontent.com/59232422/173200800-4f266045-8813-445f-b2ad-36d7f454dca9.png)

### Vaše jméno

Sebastian

**Comment by cajthamlmatej** [comment]
Bude opraveno v následující verzi!
