### ISSUE TITLE
Oprava kopírovacího buttonu

### ISSUE THREAD

**Issue by lukassuprer** [ssps-cajthaml/issues#63]
### Popis problémů

Opravit kopírovací button na code block. 

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

Někde na webu 😅

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Vaše jméno

Lukáš Procházka

**Comment by cajthamlmatej** [comment]
Duplicate of #62

**Comment by Sebight** [comment]
Duplikát #62
