### ISSUE TITLE
Chybné řazení úkolů

### ISSUE THREAD

**Issue by lukassuprer** [ssps-cajthaml/issues#64]
### Popis problémů

Špatně se řadí zadání úkolů

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

Stránka na webu -Práce 

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Vaše jméno

Lukáš Procházka

**Comment by cajthamlmatej** [comment]
Bude opraveno v další verzi.
