### ISSUE TITLE
[WEB] Bílé pozadí u profilu

### ISSUE THREAD

**Issue by lukassuprer** [ssps-cajthaml/issues#65]
### Popis problémů

I když mám dark mode tak v pravém horním horním rohu je pozadí u profilu bílé. Používám firefox a maca.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "..."
3. ?
4. Profit.

### Stránka

Normálně hlavní stránka

### Zařízení

Operační systém: **Windows/iOS/Android**
Prohlížeč: **Google Chrome/Vivaldi/...**
Je prohlížeč aktualizován na nejnovější verzi: **ano/ne**

### Chyba

\```...```

### Screenshoty

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71251770/173234097-ae5190a5-f056-4a2f-ab96-4558bf31051d.png">

### Vaše jméno

Lukáš Procházka

**Comment by cajthamlmatej** [comment]
Mělo by být fixnuté v další verzi! :)
