### ISSUE TITLE
[WEB]  Nepřehlednost rozkliknuté známky

### ISSUE THREAD

**Issue by MarekProkopec** [ssps-cajthaml/issues#66]
### Popis problémů

Při rozkliknutí detailů známky je v darkmode velice těžké rozpoznat kde končí rozkliknutá a začíná další známka

Možné řešení:
- Zvětšit odsazení detailů
- Změnit odstín pozadí detailů

### Reprodukce problému

Postup k reprodukci:
1. Zapnout darkmode
2. Rozkliknout známku, která má detaily

### Stránka

https://ssps.cajthaml.eu/3-mvop-wbf/profile

### Zařízení

Všechna, především telefon

### Screenshoty

![problem](https://user-images.githubusercontent.com/51177304/173359799-83b7cf23-ab65-4f8e-a32d-2727401f1bdb.png)

### Vaše jméno

Marek Prokopec

**Comment by cajthamlmatej** [comment]
Celý profil byl předělán, nyní by to mělo být mnohem čitelnější. V další verzi to uvidíte. Pro body se připomeňte po tom, co vytvořím účty na nový školní rok.
