### ISSUE TITLE
[WEB] Rozbití stránky na WebKit browserech

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#67]
### Popis problémů

Při otevření osobního profilu se rozbije celý vzhled stránky, jak na iOS, tak na macOS. Chyba se netýká jen Safari, ale i Chromu a Opery GX.

**Oprava problému**:
#app > div.v-application--wrap > main > div > div.container.py-8.px-6 > div > div.mt-5.v-card.v-sheet.theme--dark.elevation-2 > div.grade-container

v případě, že na tento div dám display: grid místo display: flex, chyba se opraví.

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na osobní profil

### Stránka

https://ssps.cajthaml.eu/2-wba/profile

### Zařízení

Operační systém: **macOS & iOS**
Prohlížeč: **iOS a macOS**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Screenshoty

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/35110087/174535790-7b43b75e-5949-4cc6-bdf4-49a08eee0d76.png">

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/35110087/174535815-de0a0fc9-ba78-40a9-bc2f-754b343d80e0.png">

### Vaše jméno

Matyáš Himmer & Michal Hejduk

**Comment by cajthamlmatej** [comment]
Mělo by být opravené v další verzi. Pro body se připomeňte po tom, co vytvořím účty na nový školní rok.
