### ISSUE TITLE
[NÁPAD] Porovnání studentů mezi předměty na základě procentuální úspěšnosti

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#68]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Místo bodů bych porovnával procentuální úspěšnost z důvodu rozdílného bodového základu.

### Zdůvodnění

V tuto chvíli nemám ponětí jak na tom vlastně jsem oproti ostatním neboť nevím zda mají 200 bodů ze 150 nebo třeba z 210.

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
V další verzi by to mělo být tak, jak jste popsal. Pro body se připomeňte po tom, co vytvořím účty na nový školní rok.
