### ISSUE TITLE
[NÁPAD] Ověřovací kód na začátku emailu

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#69]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Bylo by lepší mít ověřovací kód na začátku emailu. Kód by poté byl (alespoň na iOS) vidět přímo v notifikaci a nemusí se dělat pár kroků navíc otvíráním Outlooku, ...

### Zdůvodnění

Lepší UX experience. 🚀 

### Vaše jméno

Sebastian

**Comment by M4TY** [comment]
Myslím si, že tato QoL změna by měla určitě přijít

**Comment by cajthamlmatej** [comment]
V další verzi by se měl posílat obsah e-mailu již v jiném pořadí.
