### ISSUE TITLE
[WEB] Špatný Z-Index v pískovišti

### ISSUE THREAD

**Issue by Sebight** [ssps-cajthaml/issues#70]
### Popis problémů

Itemy se překrávají.

### Reprodukce problému

Jděte na Pískoviště.

### Stránka

https://ssps.cajthaml.eu/playground

### Zařízení

Windows

### Screenshoty

![obrazek](https://user-images.githubusercontent.com/59232422/176952709-bc127a40-b4d3-4da0-97fd-2107015c57ec.png)

### Vaše jméno

Sebastian

**Comment by cajthamlmatej** [comment]
V další verzi opraveno.
