### ISSUE TITLE
[NÁPAD] Notifikace o nové známce přes Discord bota

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#71]
### V jaké aplikaci se nachází nápad?

Discord

### Popis nápadu

Uživatel by měl mí t možnost si vybrat alternativní cestu k web notifikacím. Nejlepším kandidátem je Discord bot, který by při novém hodnocení mohl poslat upozornění. (Možná i s detaily hodnocení?). Uživatel by mohl mít možnost si tuto funkci zapnout, automaticky by byla vypnuta. Bot by informace uživateli poslal do DMs.

### Zdůvodnění

Web notifikace nejsou praktické.

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Lze řešit komunitou. Nový portál zasílá upozornění nativně pomocí push notifikací. Plánuji udělat kopii i na e-mail jako možnost. Interně řešeno.
