### ISSUE TITLE
[NÁPAD] Tisknutí samostudia do PDF

### ISSUE THREAD

**Issue by lukassuprer** [ssps-cajthaml/issues#73]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Bylo by hezké míti možnost tiskutí / stažení samostudia do PDF nebo jiného čitelného souboru.

### Zdůvodnění

Chtěl jsem si stáhnout materiály ještě nepřístupné zbytku studentů a byl jsem nucen si je ručně kopírovat.

### Vaše jméno

Lukáš Procházka

**Comment by cajthamlmatej** [comment]
Přidáno v další verzi.
