### ISSUE TITLE
[WEB] Obsah stránek v samostudiu se automaticky nevrací nahoru

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#74]
### Popis problémů

Když si čtete stránku z libovolné knížky v samostudiu a její text je delší, než výška obrazovky a sescrollujete dolů, jakákoliv jiná stránka/kapitola nebude po překliknutí na ni začínat nahoře, jak by se od psaného textu čekalo, ale bude posunutá níž, do stejné úrovně jako ta minulá.
Což je značně nepříjemné pro normální čtení a studium látky, kór když jsou v dané knize obsáhlé stránky a je vždycky potřeba odscrollovat celou cestu nahoru.

### Reprodukce problému

Postup k reprodukci:
1. Navštivte libovolnou knihu v samostudiu v libovolném předmětu
2. Otevřete si kapitolu, která je delší, než co se vejde na obrazovku
3. Posuňte stránku níž (pro lepší zobrazení efektu nejlépe až dolů)
4. Překlikněte na jinou kapitolu, která je také dlouhá (nemusí být stejně, stačí aby se také dala scrollovat)
5. Zjistěte, že pro pokračování čtení musíte posunout i tu druhou stránku zpět nahoru

### Stránka

Kterákoliv kniha v samostudiu kteréhokoliv předmětu, ale pro příklad třeba https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/algoritmy-a-algoritmizace-6302169b2f6bb1446c0487be

### Zařízení

Operační systém: **Windows**, ale mělo by se to dít na kterémkoliv zařízení, kde je seznam kapitol vedle textu (ne nad ním)
Prohlížeč: **Google Chrome/Firefox/Brave...**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

N/A

### Screenshoty

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53367954/186379559-44994dcd-d36a-448f-8857-6ee8b401aa48.gif)

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
V další verzi přidáno.
