### ISSUE TITLE
[WEB] Nepřehlednost rozkliknutého accordion itemu

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#77]
### Popis problémů

Při rozkliknutí accordion itemu vždy nemusí být úplně přehledný obsah itemu.

Možná řešení: 

- Dát pozadí itemu na šedou barvu
- Boldnout nadpisy

### Reprodukce problému

- Rozkliknuti accordion itemu

### Stránka

https://ssps.cajthaml.eu/dvop-wbb/exam/list

### Zařízení

Všechna

### Screenshoty

![image](https://user-images.githubusercontent.com/35110087/187763473-70ea5a4c-dc17-43f7-a2e6-79dfa1bf9b5c.png)

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Opraveno v další verzi.
