### ISSUE TITLE
[MATERIÁL] 

### ISSUE THREAD

**Issue by Majncz** [ssps-cajthaml/issues#78]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Jak Prezentace používat

### Popis problémů

1 - v třetím bodě je dvakrát "jako"
2 - chyba ve slově možné - "monžne"

### Lokace

1 - https://api-ssps.cajthaml.eu/file/2022-2023/2-pva/presentations/index.html#/3/2
2 - https://api-ssps.cajthaml.eu/file/2022-2023/2-pva/presentations/index.html#/4

### Vaše jméno

Jakub Rana

**Comment by cajthamlmatej** [comment]
Děkuji! Opravil jsem i další chyby, kterých jste si nevšiml! :)
