### ISSUE TITLE
[MATERIÁL] Překlep v prezentaci

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#82]
### Jméno předmětu pro který byl materiál vytvořen

Ostatní

### Materiál

https://api-ssps.cajthaml.eu/file/2022-2023/dvop-wbb/presentations/2.html#/7/0/3

### Popis problémů

FPS => FTP

### Lokace

27

### Oprava

FTP

### Screenshoty

<img width="348" alt="image" src="https://user-images.githubusercontent.com/35110087/188476703-4b323dfb-1d75-4f38-ab45-bb946cdcb643.png">

### Vaše jméno

Matyáš Himmer

**Comment by cajthamlmatej** [comment]
Děkuji.
