### ISSUE TITLE
[NÁPAD] Přidat webový backend 3 a 4 do "jméno předmětu pro který byl materiál vytvořen" v templatu materialu

### ISSUE THREAD

**Issue by M4TY** [ssps-cajthaml/issues#83]
### V jaké aplikaci se nachází nápad?

ostatní

### Popis nápadu

Chybí jméno předmětu

### Zdůvodnění

Přidat DVOP 3 a 4

### Vaše jméno

Matyáš Himmer

**Comment by M4TY** [comment]
https://github.com/ssps-cajthaml/issues/pull/84

**Comment by cajthamlmatej** [comment]
Děkuji.
