### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by jaywor1** [ssps-cajthaml/issues#85]
### Popis problémů

skloňování a typo v textu
"v případě HTTP se otevírá pouze jeden port - tím pádem by na jedné IP **adresa** mohl být jeden web. To by šlo **odejít** různými dalšími porty či překonfigurace webů např. na 23.201.102.3/alza"
.... na jedné IP ~~adresa~~ --> adrese
.... To by šlo ~~odejít~~ --> obejít

### Reprodukce problému

Postup k reprodukci:
1. Otevřít odkaz vedoucí k chybě

### Stránka

https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/world-wide-web-a-dom%C3%A9ny-62dbfd7156ef17b20d755020

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Firefox**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Vaše jméno

Michal Javor

**Comment by cajthamlmatej** [comment]
Děkuji, opraveno!
