### ISSUE TITLE
Oprava překlepů a pravopisných chyb

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#86]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Prezentace 1. - 4. 

### Popis problémů

Používání prezentace
Slide 1:
        henlo —> hello
Slide 3:
	Seskupené slidy jsou po vertikální ose, obyčejné po HORIZONTÁLNÍ
Slide 4:
	zmáčknouT (poslední slovo)
Slide 8:
	na levo ( v prezentaci je na pravo)
Slide 12:
	2. řádek:  monžne —> MOŽNÉ
Slide 15: 
	“levého kliku myši”

Úvodní hodina
Slide 6:
	minulÍ studenti
Slide 11:
	různÁ zadání
Slide 12:
	náhodnÁ čísla
Slide 18:
	všechnA zkoušení

Opakování algoritmizace
Slide 18:
	porovná, zda je tvrzení platné

Opakování proměnné
Slide 27:
	potřebovali celÁ čísla
Slide 28:
	před short, int, long chybí u

### Lokace

popsáno výše

### Oprava

také popsáno výše

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Jediné "henlo" je dobře, děkuji! :)
