### ISSUE TITLE
[WEB] Možnost přepínat plochy během zkoušení

### ISSUE THREAD

**Issue by LukasKnize** [ssps-cajthaml/issues#87]
### Popis problémů

Na školních pc je možné přepínat plochy pomocí klávesové zkratky win + ctrl + left arrow aniž by tuto změnu zaregistroval

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Vytvořit novou plochu
3. Přejít do kvízu
4. klávesová zkratka 
5. SUS cheating
6. Né tak moc profit

### Stránka

https://ssps.cajthaml.eu/4-mvop-wbf/exam/list

### Zařízení

Operační systém: **Windows**
Prohlížeč: **Mozilla**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Vaše jméno

Lukáš Kníže

**Comment by cajthamlmatej** [comment]
Vyřešeno.
