### ISSUE TITLE
[WEB] - "věreřná práce"

### ISSUE THREAD

**Issue by VasAli06** [ssps-cajthaml/issues#91]
### Popis problémů

Možná překlep, nebo neresponsible pro mobil. U "kompasu počtu bodů" v záložce Statistika a kategorie je napsáno pouze "věreřná práce".

### Reprodukce problému

Postup k reprodukci:
1. Přihlásit se.
2. Kliknout na "osobní profil"
3. Přepnout záložku Statistiky a kategorie do "čtvercového" kříže, který ukazuje rozložení bodů
4. Profit.

### Stránka

https://ssps.cajthaml.eu/2-pva/profile

### Zařízení

Operační systém: **Android**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![Screenshot_20220908-135210_Chrome](https://user-images.githubusercontent.com/43419807/189117176-addfdd94-8e49-4a51-8639-ba4a49b793e0.jpg)

### Vaše jméno

Alex Naxera

**Comment by cajthamlmatej** [comment]
Tohle je limitace knihovny, už bylo spousta krát hlášeno. Ale děkuji! :)
