### ISSUE TITLE
Prezentace WBA - 2. ročník

### ISSUE THREAD

**Issue by krystinkad** [ssps-cajthaml/issues#92]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

prezentace 1. - 4.

### Popis problémů

Internet 
Slide 9:
	1969 vznikLA síť ARPANET…
	které se navzájem propojovalY
Slide 13:
	druhá odrážka 
Slide 14:
	několik částí, které jsou oddělené čárkami NEBO oddělených

Nebezpečí na internetu
Slide 20:
	rhybaření —> rybaření

Prohlížeče a ochrana
Slide 5:
	tato jádra…
Slide 21:
	veřejný klíč

### Lokace

Popsáno výše

### Vaše jméno

Kristýna Dřevikovská

**Comment by cajthamlmatej** [comment]
Rhybaření je správně! Takovej paskvil ale... :D Děkuji.
