### ISSUE TITLE
Internet a WWW Prezentace - WBA 2. Ročník

### ISSUE THREAD

**Issue by JakubHrbek** [ssps-cajthaml/issues#93]
### Jméno předmětu pro který byl materiál vytvořen

Webové aplikace, 2. ročník

### Materiál

Internet a WWW - Prezentace

### Popis problémů

pravopisná chyba v slideu číslo 9 ve větě "následovaly další sítě, které se navzájem propojovali". Správně by to mělo být "následovaly další sítě, které se navzájem propojovaly".

### Lokace

9

### Screenshoty

<img width="1440" alt="Screen Shot 2022-09-08 at 14 41 02" src="https://user-images.githubusercontent.com/94190837/189124202-37e2c45d-11f3-484f-bf11-3df093377424.png">

### Vaše jméno

Jakub Hrbek

**Comment by cajthamlmatej** [comment]
Již nahlášeno v #92 :(
