### ISSUE TITLE
Emailová notifikace po přidání hodnocení

### ISSUE THREAD

**Issue by lennerjiri** [ssps-cajthaml/issues#94]
### V jaké aplikaci se nachází nápad?

Portál (webová stránka)

### Popis nápadu

Pokaždé co lektor přidá domácí úkol či hodnocení k domácímu úkolu, přijde do emailu notifikace.
Defaultně bude tato možnost vypnutá aby neobtěžovala ty, kteří nemají rádi tento typ notifikace.
Lze zapnout v nastavení.

### Zdůvodnění

Jsem líný neustále kontrolovat portál ;)
Takto se na portál vydám vždy když to bude potřeba -> tedy bude li přídán nový ukol či přidáno hodnocení

### Vaše jméno

Jiří Lenner

**Comment by cajthamlmatej** [comment]
Částečně souvisí s #71, v létě jsem vytvořil nativní notifikace, ty se ale nelíbili.

**Comment by cajthamlmatej** [comment]
Viz. #71, částečně řešeno.
