### ISSUE TITLE
[MATERIÁL] Překlepy v lekci samostudia

### ISSUE THREAD

**Issue by 3ncy** [ssps-cajthaml/issues#95]
### Jméno předmětu pro který byl materiál vytvořen

DVOP Webový backend, 3. ročník

### Materiál

LEKCE: Opakování předmětu Webové aplikace

### Popis problémů

Překlepy a hrubky v knize samostudia.

V listu https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/z%C3%A1kladn%C3%AD-tagy-62dc11b256ef17b20d755b14 se nepodbarvuje kód u tagu `link`

### Lokace

- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/prohl%C3%AD%C5%BEe%C4%8De-62dc01e356ef17b20d7552ee
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/autorsk%C3%BD-z%C3%A1kon-62dc01e356ef17b20d7552f1
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/html-62dc11b256ef17b20d755b10
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/soubory-na-webov%C3%BDch-str%C3%A1nk%C3%A1ch-62dc11b256ef17b20d755b11
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/tag-a-atributy-62dc11b256ef17b20d755b12
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/z%C3%A1kladn%C3%AD-struktura-html-62dc11b256ef17b20d755b13
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/z%C3%A1kladn%C3%AD-tagy-62dc11b256ef17b20d755b14
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/css-62dc11b256ef17b20d755b15
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/selektory-62dc11b256ef17b20d755b17
- https://ssps.cajthaml.eu/dvop-wbb/selfstudy/lekce-opakovani-wba/z%C3%A1kladn%C3%AD-vlastnosti-62dc11b256ef17b20d755b19

### Oprava

Řazeno podle stránek, kde se problémy objevují:
###  Prohlížeče
- V druhém odstavci překlep v "**Mozilla**"
- Dole v seznamu místo "**- být rychlý a nebrat zbytečné zdroje počítače**" má být "**je rychlý a nezabírá zbytečné zdroje počítače**" aby byla osoba ve všech bodech stejná. Ale celé ty vlastnosti jsou napsány trošku zvláštně, protože to začíná "jedná se o: […] " a pak najednou přecházíte do přítomného času třetí osoby, takže by možná bylo lepší v třeba 3. bodě dát "ochranu uživatele před reklamou či sledovači" a stejně upravit i ostatní body.
<hr>

### Autorský zákon
- Začátek 2. odstavce: "Bez používáním jakékoliv věci" -> "**Před** používáním jakékoliv věci"
<hr>

### HTML
- Konec 2. odstavce: "a mohli se jednodušeji" -> "a mohl**y**", protože podmět je _ty stránky_. Možná by bylo lepší nahradit "mohly" za "daly"?
<hr>

### Soubory na webových stránkách
- Konec 3. odstavce: "a pro rastrové `.svg`." -> "a pro **vektorové**"
<hr>

### Tag a atributy
- Nebylo by lepší přejmenovat tuto stránku na "Tag**y** a atributy",  ať je obojí v množném čísle?
- 4. odstavec: "Další důležitý pojme je element." -> "**pojem**"
- Konec odstavce o atributech: "Tagy se vzdy určují u počátečního tagu." -> "**Atributy** se v**ž**dy"
<hr>

### Základní struktura HTML
- V odstavci o HTML ve větě "Pomocí HTTP se posílají různé soubory a proto definovat kořenový element." chybí mezi slovy "proto" a "definovat" slovo, jako třeba "**je potřeba**" nebo "**musíme**"
<hr>

### Základní tagy
- U nepodbarveného kódu by mělo stačit změnit html třídu toho kódu na `language-html`, nebo pokud to píšete v nějakém md -> html konvertoru, změnit to tam.
<hr>

### CSS
- Pod seznamem nevýhod: "Zcela jistě by se našlo ještě více výhody a nevýhod" -> "ještě více **výhod** a nevýhod"
- Poslední odstavec: "Jako první vlastnosti, abychom […]" -> "**vlastnost**"
<hr>

### Zápisy CSS
- 3. odstavec: "Tento způsob tedy využíváme jen zřídka a pro velmi (jinak nevyřešitelné) problémy." -> "a pro velmi **specifické**" (Nebo by také šlo úplně vypustit slovo "velmi" a vyndat ten text ze závorky)
- Odstavec o External: "Používám celé pravidla." -> "**Používáme**", protože všude jinde máte také množné číslo.
<hr>

### Selektory
- V odstavci o Selektování pomocí tříd: "a další speciálnít agy." -> "** specální tagy**", ale možná by více dávalo smysl "**znaky**"
- V odstavci o Vnořovací: "mezi tagy, identifikátory, třídy či dalšími selektory." -> "identifikátory, **třídami** či"
- O řádek níže ve stejném odstavci: "a klidně v dědí dětech," -> "a klidně v **dětech dětí**,"
- V odstavci o Seskupovací: "Seskupí více selektorů tag, že" -> buď je tohle slovní hříčka, nebo tam má být "**tak**"
- V odstavci o Násobný: "používáme již známe věci" -> "**známé**"
<hr>

### Základní vlastnosti
- Konec prvního odstavce: "HEXA: #abcxyzde, kde de značí průhlednost, stejně jakou o rgba." -> "stejně **jako u rgba**" nebo "stejně **jako `a` u rgba**"
- Nadpis sekce "Zloušťka textu" -> "**T**loušťka textu"
- V odstavci o Tloušťce textu: "Kde 100 je nejtenší typ." -> "nejten**č**í"
- V odstavci o Dekorace textu: "(přečtěte si na další stránce zde)," -> "zde" není nalinkované nikam a pokud se tím myslí nějaká jiná stránka v samostudiu, tak v DVOP3 žádná taková není.

### Screenshoty

![image](https://user-images.githubusercontent.com/53367954/189547654-2a9f646e-9558-45eb-9bde-1452d169b045.png)

### Vaše jméno

Martin Hanzlik

**Comment by cajthamlmatej** [comment]
Děkuji.
