### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by Roto83** [ssps-cajthaml/issues#96]
### Popis problémů

Překlep v "LEKCE: Opakování 1. ročníku"

### Reprodukce problému

V záložce "Proměnné a datové typy" pod odstavcem "Desetinné číslo" je překlep, je zde místo "decimal" napsáno "ulong"

### Stránka

https://ssps.cajthaml.eu/2-pva/selfstudy/lekce-opakovani-1-rocniku/prom%C4%9Bnn%C3%A9-a-datov%C3%A9-typy-6302169b2f6bb1446c0487c1

### Zařízení

Operační systém: **Windows 10**
Prohlížeč: **Google Chrome**
Je prohlížeč aktualizován na nejnovější verzi: **ano**

### Chyba

\```...```

### Screenshoty

![image](https://user-images.githubusercontent.com/112205666/189640895-f6cdc5f5-0eaa-4594-900c-c4a7f9be0586.png)

### Vaše jméno

Marian Frýba

**Comment by cajthamlmatej** [comment]
Již bylo nahlášeno v #90.
