### ISSUE TITLE
[WEB] 

### ISSUE THREAD

**Issue by JakubHrbek** [ssps-cajthaml/issues#97]
### Jméno předmětu pro který byl materiál vytvořen

Programování a vývoj aplikací, 2. ročník

### Materiál

Používání prezentace

### Popis problémů

Pravopisná chyba. Místo "Viděl si animaci?" --> "Viděl jsi animaci?"

### Lokace

3/17

### Screenshoty

<img width="1440" alt="Screen Shot 2022-09-12 at 16 35 06" src="https://user-images.githubusercontent.com/94190837/189681860-8e75b921-fa0e-405d-8762-5ccce532856e.png">

### Vaše jméno

Jakub Hrbek

**Comment by cajthamlmatej** [comment]
Děkuji.
